/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BackupUpgradeCreateBlobRequest,
    BackupUpgradeCreateBlobRequestFromJSON,
    BackupUpgradeCreateBlobRequestToJSON,
} from '../models/BackupUpgradeCreateBlobRequest';
import {
    type BackupUpgradeCreateBlobResponse,
    BackupUpgradeCreateBlobResponseFromJSON,
    BackupUpgradeCreateBlobResponseToJSON,
} from '../models/BackupUpgradeCreateBlobResponse';
import {
    type BackupUpgradeCreateDynamicChunkRequest,
    BackupUpgradeCreateDynamicChunkRequestFromJSON,
    BackupUpgradeCreateDynamicChunkRequestToJSON,
} from '../models/BackupUpgradeCreateDynamicChunkRequest';
import {
    type BackupUpgradeCreateDynamicChunkResponse,
    BackupUpgradeCreateDynamicChunkResponseFromJSON,
    BackupUpgradeCreateDynamicChunkResponseToJSON,
} from '../models/BackupUpgradeCreateDynamicChunkResponse';
import {
    type BackupUpgradeCreateDynamicCloseRequest,
    BackupUpgradeCreateDynamicCloseRequestFromJSON,
    BackupUpgradeCreateDynamicCloseRequestToJSON,
} from '../models/BackupUpgradeCreateDynamicCloseRequest';
import {
    type BackupUpgradeCreateDynamicCloseResponse,
    BackupUpgradeCreateDynamicCloseResponseFromJSON,
    BackupUpgradeCreateDynamicCloseResponseToJSON,
} from '../models/BackupUpgradeCreateDynamicCloseResponse';
import {
    type BackupUpgradeCreateDynamicIndexRequest,
    BackupUpgradeCreateDynamicIndexRequestFromJSON,
    BackupUpgradeCreateDynamicIndexRequestToJSON,
} from '../models/BackupUpgradeCreateDynamicIndexRequest';
import {
    type BackupUpgradeCreateDynamicIndexResponse,
    BackupUpgradeCreateDynamicIndexResponseFromJSON,
    BackupUpgradeCreateDynamicIndexResponseToJSON,
} from '../models/BackupUpgradeCreateDynamicIndexResponse';
import {
    type BackupUpgradeCreateFinishResponse,
    BackupUpgradeCreateFinishResponseFromJSON,
    BackupUpgradeCreateFinishResponseToJSON,
} from '../models/BackupUpgradeCreateFinishResponse';
import {
    type BackupUpgradeCreateFixedChunkRequest,
    BackupUpgradeCreateFixedChunkRequestFromJSON,
    BackupUpgradeCreateFixedChunkRequestToJSON,
} from '../models/BackupUpgradeCreateFixedChunkRequest';
import {
    type BackupUpgradeCreateFixedChunkResponse,
    BackupUpgradeCreateFixedChunkResponseFromJSON,
    BackupUpgradeCreateFixedChunkResponseToJSON,
} from '../models/BackupUpgradeCreateFixedChunkResponse';
import {
    type BackupUpgradeCreateFixedCloseRequest,
    BackupUpgradeCreateFixedCloseRequestFromJSON,
    BackupUpgradeCreateFixedCloseRequestToJSON,
} from '../models/BackupUpgradeCreateFixedCloseRequest';
import {
    type BackupUpgradeCreateFixedCloseResponse,
    BackupUpgradeCreateFixedCloseResponseFromJSON,
    BackupUpgradeCreateFixedCloseResponseToJSON,
} from '../models/BackupUpgradeCreateFixedCloseResponse';
import {
    type BackupUpgradeCreateFixedIndexRequest,
    BackupUpgradeCreateFixedIndexRequestFromJSON,
    BackupUpgradeCreateFixedIndexRequestToJSON,
} from '../models/BackupUpgradeCreateFixedIndexRequest';
import {
    type BackupUpgradeCreateFixedIndexResponse,
    BackupUpgradeCreateFixedIndexResponseFromJSON,
    BackupUpgradeCreateFixedIndexResponseToJSON,
} from '../models/BackupUpgradeCreateFixedIndexResponse';
import {
    type BackupUpgradeCreateSpeedtestResponse,
    BackupUpgradeCreateSpeedtestResponseFromJSON,
    BackupUpgradeCreateSpeedtestResponseToJSON,
} from '../models/BackupUpgradeCreateSpeedtestResponse';
import {
    type BackupUpgradeGetPreviousBackupTimeResponse,
    BackupUpgradeGetPreviousBackupTimeResponseFromJSON,
    BackupUpgradeGetPreviousBackupTimeResponseToJSON,
} from '../models/BackupUpgradeGetPreviousBackupTimeResponse';
import {
    type BackupUpgradeGetPreviousResponse,
    BackupUpgradeGetPreviousResponseFromJSON,
    BackupUpgradeGetPreviousResponseToJSON,
} from '../models/BackupUpgradeGetPreviousResponse';
import {
    type BackupUpgradeGetUpgradeResponse,
    BackupUpgradeGetUpgradeResponseFromJSON,
    BackupUpgradeGetUpgradeResponseToJSON,
} from '../models/BackupUpgradeGetUpgradeResponse';
import {
    type BackupUpgradeUpdateDynamicIndexRequest,
    BackupUpgradeUpdateDynamicIndexRequestFromJSON,
    BackupUpgradeUpdateDynamicIndexRequestToJSON,
} from '../models/BackupUpgradeUpdateDynamicIndexRequest';
import {
    type BackupUpgradeUpdateDynamicIndexResponse,
    BackupUpgradeUpdateDynamicIndexResponseFromJSON,
    BackupUpgradeUpdateDynamicIndexResponseToJSON,
} from '../models/BackupUpgradeUpdateDynamicIndexResponse';
import {
    type BackupUpgradeUpdateFixedIndexRequest,
    BackupUpgradeUpdateFixedIndexRequestFromJSON,
    BackupUpgradeUpdateFixedIndexRequestToJSON,
} from '../models/BackupUpgradeUpdateFixedIndexRequest';
import {
    type BackupUpgradeUpdateFixedIndexResponse,
    BackupUpgradeUpdateFixedIndexResponseFromJSON,
    BackupUpgradeUpdateFixedIndexResponseToJSON,
} from '../models/BackupUpgradeUpdateFixedIndexResponse';
import {
    type PbsError,
    PbsErrorFromJSON,
    PbsErrorToJSON,
} from '../models/PbsError';

export interface BackupUpgradeApiCreateBlobRequest {
    backupUpgradeCreateBlobRequest: BackupUpgradeCreateBlobRequest;
}

export interface BackupUpgradeApiCreateDynamicChunkRequest {
    backupUpgradeCreateDynamicChunkRequest: BackupUpgradeCreateDynamicChunkRequest;
}

export interface BackupUpgradeApiCreateDynamicCloseRequest {
    backupUpgradeCreateDynamicCloseRequest: BackupUpgradeCreateDynamicCloseRequest;
}

export interface BackupUpgradeApiCreateDynamicIndexRequest {
    backupUpgradeCreateDynamicIndexRequest: BackupUpgradeCreateDynamicIndexRequest;
}

export interface BackupUpgradeApiCreateFixedChunkRequest {
    backupUpgradeCreateFixedChunkRequest: BackupUpgradeCreateFixedChunkRequest;
}

export interface BackupUpgradeApiCreateFixedCloseRequest {
    backupUpgradeCreateFixedCloseRequest: BackupUpgradeCreateFixedCloseRequest;
}

export interface BackupUpgradeApiCreateFixedIndexRequest {
    backupUpgradeCreateFixedIndexRequest: BackupUpgradeCreateFixedIndexRequest;
}

export interface BackupUpgradeApiGetPreviousRequest {
    archiveName: string;
}

export interface BackupUpgradeApiUpdateDynamicIndexRequest {
    backupUpgradeUpdateDynamicIndexRequest: BackupUpgradeUpdateDynamicIndexRequest;
}

export interface BackupUpgradeApiUpdateFixedIndexRequest {
    backupUpgradeUpdateFixedIndexRequest: BackupUpgradeUpdateFixedIndexRequest;
}

/**
 * 
 */
export class BackupUpgradeApi extends runtime.BaseAPI {

    /**
     * Creates request options for createBlob without sending the request
     */
    async createBlobRequestOpts(requestParameters: BackupUpgradeApiCreateBlobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupUpgradeCreateBlobRequest'] == null) {
            throw new runtime.RequiredError(
                'backupUpgradeCreateBlobRequest',
                'Required parameter "backupUpgradeCreateBlobRequest" was null or undefined when calling createBlob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/blob`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BackupUpgradeCreateBlobRequestToJSON(requestParameters['backupUpgradeCreateBlobRequest']),
        };
    }

    /**
     * Upload binary blob file.
     * Upload binary blob file
     */
    async createBlobRaw(requestParameters: BackupUpgradeApiCreateBlobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeCreateBlobResponse>> {
        const requestOptions = await this.createBlobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeCreateBlobResponseFromJSON(jsonValue));
    }

    /**
     * Upload binary blob file.
     * Upload binary blob file
     */
    async createBlob(requestParameters: BackupUpgradeApiCreateBlobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeCreateBlobResponse> {
        const response = await this.createBlobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createDynamicChunk without sending the request
     */
    async createDynamicChunkRequestOpts(requestParameters: BackupUpgradeApiCreateDynamicChunkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupUpgradeCreateDynamicChunkRequest'] == null) {
            throw new runtime.RequiredError(
                'backupUpgradeCreateDynamicChunkRequest',
                'Required parameter "backupUpgradeCreateDynamicChunkRequest" was null or undefined when calling createDynamicChunk().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/dynamic_chunk`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BackupUpgradeCreateDynamicChunkRequestToJSON(requestParameters['backupUpgradeCreateDynamicChunkRequest']),
        };
    }

    /**
     * Upload a new chunk.
     * Upload a new chunk
     */
    async createDynamicChunkRaw(requestParameters: BackupUpgradeApiCreateDynamicChunkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeCreateDynamicChunkResponse>> {
        const requestOptions = await this.createDynamicChunkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeCreateDynamicChunkResponseFromJSON(jsonValue));
    }

    /**
     * Upload a new chunk.
     * Upload a new chunk
     */
    async createDynamicChunk(requestParameters: BackupUpgradeApiCreateDynamicChunkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeCreateDynamicChunkResponse> {
        const response = await this.createDynamicChunkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createDynamicClose without sending the request
     */
    async createDynamicCloseRequestOpts(requestParameters: BackupUpgradeApiCreateDynamicCloseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupUpgradeCreateDynamicCloseRequest'] == null) {
            throw new runtime.RequiredError(
                'backupUpgradeCreateDynamicCloseRequest',
                'Required parameter "backupUpgradeCreateDynamicCloseRequest" was null or undefined when calling createDynamicClose().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/dynamic_close`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BackupUpgradeCreateDynamicCloseRequestToJSON(requestParameters['backupUpgradeCreateDynamicCloseRequest']),
        };
    }

    /**
     * Close dynamic index writer.
     * Close dynamic index writer
     */
    async createDynamicCloseRaw(requestParameters: BackupUpgradeApiCreateDynamicCloseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeCreateDynamicCloseResponse>> {
        const requestOptions = await this.createDynamicCloseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeCreateDynamicCloseResponseFromJSON(jsonValue));
    }

    /**
     * Close dynamic index writer.
     * Close dynamic index writer
     */
    async createDynamicClose(requestParameters: BackupUpgradeApiCreateDynamicCloseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeCreateDynamicCloseResponse> {
        const response = await this.createDynamicCloseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createDynamicIndex without sending the request
     */
    async createDynamicIndexRequestOpts(requestParameters: BackupUpgradeApiCreateDynamicIndexRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupUpgradeCreateDynamicIndexRequest'] == null) {
            throw new runtime.RequiredError(
                'backupUpgradeCreateDynamicIndexRequest',
                'Required parameter "backupUpgradeCreateDynamicIndexRequest" was null or undefined when calling createDynamicIndex().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/dynamic_index`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BackupUpgradeCreateDynamicIndexRequestToJSON(requestParameters['backupUpgradeCreateDynamicIndexRequest']),
        };
    }

    /**
     * Create dynamic chunk index file.
     * Create dynamic chunk index file
     */
    async createDynamicIndexRaw(requestParameters: BackupUpgradeApiCreateDynamicIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeCreateDynamicIndexResponse>> {
        const requestOptions = await this.createDynamicIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeCreateDynamicIndexResponseFromJSON(jsonValue));
    }

    /**
     * Create dynamic chunk index file.
     * Create dynamic chunk index file
     */
    async createDynamicIndex(requestParameters: BackupUpgradeApiCreateDynamicIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeCreateDynamicIndexResponse> {
        const response = await this.createDynamicIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createFinish without sending the request
     */
    async createFinishRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/finish`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mark backup as finished.
     * Mark backup as finished
     */
    async createFinishRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeCreateFinishResponse>> {
        const requestOptions = await this.createFinishRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeCreateFinishResponseFromJSON(jsonValue));
    }

    /**
     * Mark backup as finished.
     * Mark backup as finished
     */
    async createFinish(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeCreateFinishResponse> {
        const response = await this.createFinishRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createFixedChunk without sending the request
     */
    async createFixedChunkRequestOpts(requestParameters: BackupUpgradeApiCreateFixedChunkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupUpgradeCreateFixedChunkRequest'] == null) {
            throw new runtime.RequiredError(
                'backupUpgradeCreateFixedChunkRequest',
                'Required parameter "backupUpgradeCreateFixedChunkRequest" was null or undefined when calling createFixedChunk().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/fixed_chunk`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BackupUpgradeCreateFixedChunkRequestToJSON(requestParameters['backupUpgradeCreateFixedChunkRequest']),
        };
    }

    /**
     * Upload a new chunk.
     * Upload a new chunk
     */
    async createFixedChunkRaw(requestParameters: BackupUpgradeApiCreateFixedChunkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeCreateFixedChunkResponse>> {
        const requestOptions = await this.createFixedChunkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeCreateFixedChunkResponseFromJSON(jsonValue));
    }

    /**
     * Upload a new chunk.
     * Upload a new chunk
     */
    async createFixedChunk(requestParameters: BackupUpgradeApiCreateFixedChunkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeCreateFixedChunkResponse> {
        const response = await this.createFixedChunkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createFixedClose without sending the request
     */
    async createFixedCloseRequestOpts(requestParameters: BackupUpgradeApiCreateFixedCloseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupUpgradeCreateFixedCloseRequest'] == null) {
            throw new runtime.RequiredError(
                'backupUpgradeCreateFixedCloseRequest',
                'Required parameter "backupUpgradeCreateFixedCloseRequest" was null or undefined when calling createFixedClose().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/fixed_close`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BackupUpgradeCreateFixedCloseRequestToJSON(requestParameters['backupUpgradeCreateFixedCloseRequest']),
        };
    }

    /**
     * Close fixed index writer.
     * Close fixed index writer
     */
    async createFixedCloseRaw(requestParameters: BackupUpgradeApiCreateFixedCloseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeCreateFixedCloseResponse>> {
        const requestOptions = await this.createFixedCloseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeCreateFixedCloseResponseFromJSON(jsonValue));
    }

    /**
     * Close fixed index writer.
     * Close fixed index writer
     */
    async createFixedClose(requestParameters: BackupUpgradeApiCreateFixedCloseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeCreateFixedCloseResponse> {
        const response = await this.createFixedCloseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createFixedIndex without sending the request
     */
    async createFixedIndexRequestOpts(requestParameters: BackupUpgradeApiCreateFixedIndexRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupUpgradeCreateFixedIndexRequest'] == null) {
            throw new runtime.RequiredError(
                'backupUpgradeCreateFixedIndexRequest',
                'Required parameter "backupUpgradeCreateFixedIndexRequest" was null or undefined when calling createFixedIndex().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/fixed_index`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BackupUpgradeCreateFixedIndexRequestToJSON(requestParameters['backupUpgradeCreateFixedIndexRequest']),
        };
    }

    /**
     * Create fixed chunk index file.
     * Create fixed chunk index file
     */
    async createFixedIndexRaw(requestParameters: BackupUpgradeApiCreateFixedIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeCreateFixedIndexResponse>> {
        const requestOptions = await this.createFixedIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeCreateFixedIndexResponseFromJSON(jsonValue));
    }

    /**
     * Create fixed chunk index file.
     * Create fixed chunk index file
     */
    async createFixedIndex(requestParameters: BackupUpgradeApiCreateFixedIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeCreateFixedIndexResponse> {
        const response = await this.createFixedIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSpeedtest without sending the request
     */
    async createSpeedtestRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/speedtest`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Test upload speed.
     * Test upload speed
     */
    async createSpeedtestRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeCreateSpeedtestResponse>> {
        const requestOptions = await this.createSpeedtestRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeCreateSpeedtestResponseFromJSON(jsonValue));
    }

    /**
     * Test upload speed.
     * Test upload speed
     */
    async createSpeedtest(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeCreateSpeedtestResponse> {
        const response = await this.createSpeedtestRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPrevious without sending the request
     */
    async getPreviousRequestOpts(requestParameters: BackupUpgradeApiGetPreviousRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['archiveName'] == null) {
            throw new runtime.RequiredError(
                'archiveName',
                'Required parameter "archiveName" was null or undefined when calling getPrevious().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['archiveName'] != null) {
            queryParameters['archive-name'] = requestParameters['archiveName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/previous`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download archive from previous backup.
     * Download archive from previous backup
     */
    async getPreviousRaw(requestParameters: BackupUpgradeApiGetPreviousRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeGetPreviousResponse>> {
        const requestOptions = await this.getPreviousRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeGetPreviousResponseFromJSON(jsonValue));
    }

    /**
     * Download archive from previous backup.
     * Download archive from previous backup
     */
    async getPrevious(requestParameters: BackupUpgradeApiGetPreviousRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeGetPreviousResponse> {
        const response = await this.getPreviousRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPreviousBackupTime without sending the request
     */
    async getPreviousBackupTimeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/previous_backup_time`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get previous backup time.
     * Get previous backup time
     */
    async getPreviousBackupTimeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeGetPreviousBackupTimeResponse>> {
        const requestOptions = await this.getPreviousBackupTimeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeGetPreviousBackupTimeResponseFromJSON(jsonValue));
    }

    /**
     * Get previous backup time.
     * Get previous backup time
     */
    async getPreviousBackupTime(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeGetPreviousBackupTimeResponse> {
        const response = await this.getPreviousBackupTimeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUpgrade without sending the request
     */
    async getUpgradeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Directory index.
     * Directory index
     */
    async getUpgradeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeGetUpgradeResponse>> {
        const requestOptions = await this.getUpgradeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeGetUpgradeResponseFromJSON(jsonValue));
    }

    /**
     * Directory index.
     * Directory index
     */
    async getUpgrade(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeGetUpgradeResponse> {
        const response = await this.getUpgradeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateDynamicIndex without sending the request
     */
    async updateDynamicIndexRequestOpts(requestParameters: BackupUpgradeApiUpdateDynamicIndexRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupUpgradeUpdateDynamicIndexRequest'] == null) {
            throw new runtime.RequiredError(
                'backupUpgradeUpdateDynamicIndexRequest',
                'Required parameter "backupUpgradeUpdateDynamicIndexRequest" was null or undefined when calling updateDynamicIndex().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/dynamic_index`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BackupUpgradeUpdateDynamicIndexRequestToJSON(requestParameters['backupUpgradeUpdateDynamicIndexRequest']),
        };
    }

    /**
     * Append chunk to dynamic index writer.
     * Append chunk to dynamic index writer
     */
    async updateDynamicIndexRaw(requestParameters: BackupUpgradeApiUpdateDynamicIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeUpdateDynamicIndexResponse>> {
        const requestOptions = await this.updateDynamicIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeUpdateDynamicIndexResponseFromJSON(jsonValue));
    }

    /**
     * Append chunk to dynamic index writer.
     * Append chunk to dynamic index writer
     */
    async updateDynamicIndex(requestParameters: BackupUpgradeApiUpdateDynamicIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeUpdateDynamicIndexResponse> {
        const response = await this.updateDynamicIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateFixedIndex without sending the request
     */
    async updateFixedIndexRequestOpts(requestParameters: BackupUpgradeApiUpdateFixedIndexRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupUpgradeUpdateFixedIndexRequest'] == null) {
            throw new runtime.RequiredError(
                'backupUpgradeUpdateFixedIndexRequest',
                'Required parameter "backupUpgradeUpdateFixedIndexRequest" was null or undefined when calling updateFixedIndex().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/backup/_upgrade_/fixed_index`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BackupUpgradeUpdateFixedIndexRequestToJSON(requestParameters['backupUpgradeUpdateFixedIndexRequest']),
        };
    }

    /**
     * Append chunk to fixed index writer.
     * Append chunk to fixed index writer
     */
    async updateFixedIndexRaw(requestParameters: BackupUpgradeApiUpdateFixedIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupUpgradeUpdateFixedIndexResponse>> {
        const requestOptions = await this.updateFixedIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupUpgradeUpdateFixedIndexResponseFromJSON(jsonValue));
    }

    /**
     * Append chunk to fixed index writer.
     * Append chunk to fixed index writer
     */
    async updateFixedIndex(requestParameters: BackupUpgradeApiUpdateFixedIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupUpgradeUpdateFixedIndexResponse> {
        const response = await this.updateFixedIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
