/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ConfigPruneCreatePruneRequest,
    ConfigPruneCreatePruneRequestFromJSON,
    ConfigPruneCreatePruneRequestToJSON,
} from '../models/ConfigPruneCreatePruneRequest';
import {
    type ConfigPruneCreatePruneResponse,
    ConfigPruneCreatePruneResponseFromJSON,
    ConfigPruneCreatePruneResponseToJSON,
} from '../models/ConfigPruneCreatePruneResponse';
import {
    type ConfigPruneDeletePruneResponse,
    ConfigPruneDeletePruneResponseFromJSON,
    ConfigPruneDeletePruneResponseToJSON,
} from '../models/ConfigPruneDeletePruneResponse';
import {
    type ConfigPruneGetConfigPruneByIdResponse,
    ConfigPruneGetConfigPruneByIdResponseFromJSON,
    ConfigPruneGetConfigPruneByIdResponseToJSON,
} from '../models/ConfigPruneGetConfigPruneByIdResponse';
import {
    type ConfigPruneGetPruneResponse,
    ConfigPruneGetPruneResponseFromJSON,
    ConfigPruneGetPruneResponseToJSON,
} from '../models/ConfigPruneGetPruneResponse';
import {
    type ConfigPruneUpdatePruneRequest,
    ConfigPruneUpdatePruneRequestFromJSON,
    ConfigPruneUpdatePruneRequestToJSON,
} from '../models/ConfigPruneUpdatePruneRequest';
import {
    type ConfigPruneUpdatePruneResponse,
    ConfigPruneUpdatePruneResponseFromJSON,
    ConfigPruneUpdatePruneResponseToJSON,
} from '../models/ConfigPruneUpdatePruneResponse';
import {
    type PbsError,
    PbsErrorFromJSON,
    PbsErrorToJSON,
} from '../models/PbsError';

export interface ConfigPruneApiCreatePruneRequest {
    configPruneCreatePruneRequest: ConfigPruneCreatePruneRequest;
}

export interface ConfigPruneApiDeletePruneRequest {
    id: string;
    digest?: string;
}

export interface ConfigPruneApiGetConfigPruneByIdRequest {
    id: string;
}

export interface ConfigPruneApiUpdatePruneRequest {
    id: string;
    configPruneUpdatePruneRequest?: ConfigPruneUpdatePruneRequest;
}

/**
 * 
 */
export class ConfigPruneApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPrune without sending the request
     */
    async createPruneRequestOpts(requestParameters: ConfigPruneApiCreatePruneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['configPruneCreatePruneRequest'] == null) {
            throw new runtime.RequiredError(
                'configPruneCreatePruneRequest',
                'Required parameter "configPruneCreatePruneRequest" was null or undefined when calling createPrune().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/prune`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigPruneCreatePruneRequestToJSON(requestParameters['configPruneCreatePruneRequest']),
        };
    }

    /**
     * Create a new prune job.  Permissions: Requires Datastore.Modify on job\'s datastore.
     * Create a new prune job
     */
    async createPruneRaw(requestParameters: ConfigPruneApiCreatePruneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigPruneCreatePruneResponse>> {
        const requestOptions = await this.createPruneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigPruneCreatePruneResponseFromJSON(jsonValue));
    }

    /**
     * Create a new prune job.  Permissions: Requires Datastore.Modify on job\'s datastore.
     * Create a new prune job
     */
    async createPrune(requestParameters: ConfigPruneApiCreatePruneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigPruneCreatePruneResponse> {
        const response = await this.createPruneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePrune without sending the request
     */
    async deletePruneRequestOpts(requestParameters: ConfigPruneApiDeletePruneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePrune().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['digest'] != null) {
            queryParameters['digest'] = requestParameters['digest'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/prune/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a prune job configuration  Permissions: Requires Datastore.Verify on job\'s datastore.
     * Remove a prune job configuration
     */
    async deletePruneRaw(requestParameters: ConfigPruneApiDeletePruneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigPruneDeletePruneResponse>> {
        const requestOptions = await this.deletePruneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigPruneDeletePruneResponseFromJSON(jsonValue));
    }

    /**
     * Remove a prune job configuration  Permissions: Requires Datastore.Verify on job\'s datastore.
     * Remove a prune job configuration
     */
    async deletePrune(requestParameters: ConfigPruneApiDeletePruneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigPruneDeletePruneResponse> {
        const response = await this.deletePruneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConfigPruneById without sending the request
     */
    async getConfigPruneByIdRequestOpts(requestParameters: ConfigPruneApiGetConfigPruneByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getConfigPruneById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/prune/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read a prune job configuration.  Permissions: Requires Datastore.Audit or Datastore.Verify on job\'s datastore.
     * Read a prune job configuration
     */
    async getConfigPruneByIdRaw(requestParameters: ConfigPruneApiGetConfigPruneByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigPruneGetConfigPruneByIdResponse>> {
        const requestOptions = await this.getConfigPruneByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigPruneGetConfigPruneByIdResponseFromJSON(jsonValue));
    }

    /**
     * Read a prune job configuration.  Permissions: Requires Datastore.Audit or Datastore.Verify on job\'s datastore.
     * Read a prune job configuration
     */
    async getConfigPruneById(requestParameters: ConfigPruneApiGetConfigPruneByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigPruneGetConfigPruneByIdResponse> {
        const response = await this.getConfigPruneByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPrune without sending the request
     */
    async getPruneRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/prune`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all scheduled prune jobs.  Permissions: Requires Datastore.Audit.
     * List all scheduled prune jobs
     */
    async getPruneRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigPruneGetPruneResponse>> {
        const requestOptions = await this.getPruneRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigPruneGetPruneResponseFromJSON(jsonValue));
    }

    /**
     * List all scheduled prune jobs.  Permissions: Requires Datastore.Audit.
     * List all scheduled prune jobs
     */
    async getPrune(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigPruneGetPruneResponse> {
        const response = await this.getPruneRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updatePrune without sending the request
     */
    async updatePruneRequestOpts(requestParameters: ConfigPruneApiUpdatePruneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updatePrune().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        // Optional body: only emit Content-Type when the body is actually provided.
        // PVE/PMG Perl HTTP server rejects empty bodies with Content-Type: application/json
        // ("malformed JSON string"), and other Proxmox products are equally fussy.
        if (requestParameters['configPruneUpdatePruneRequest'] != null) {
            headerParameters['Content-Type'] = 'application/json';
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/prune/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigPruneUpdatePruneRequestToJSON(requestParameters['configPruneUpdatePruneRequest']),
        };
    }

    /**
     * Update prune job config.  Permissions: Requires Datastore.Modify on job\'s datastore.
     * Update prune job config
     */
    async updatePruneRaw(requestParameters: ConfigPruneApiUpdatePruneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigPruneUpdatePruneResponse>> {
        const requestOptions = await this.updatePruneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigPruneUpdatePruneResponseFromJSON(jsonValue));
    }

    /**
     * Update prune job config.  Permissions: Requires Datastore.Modify on job\'s datastore.
     * Update prune job config
     */
    async updatePrune(requestParameters: ConfigPruneApiUpdatePruneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigPruneUpdatePruneResponse> {
        const response = await this.updatePruneRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
