/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ConfigTapeEncryptionKeysCreateTapeEncryptionKeysRequest,
    ConfigTapeEncryptionKeysCreateTapeEncryptionKeysRequestFromJSON,
    ConfigTapeEncryptionKeysCreateTapeEncryptionKeysRequestToJSON,
} from '../models/ConfigTapeEncryptionKeysCreateTapeEncryptionKeysRequest';
import {
    type ConfigTapeEncryptionKeysCreateTapeEncryptionKeysResponse,
    ConfigTapeEncryptionKeysCreateTapeEncryptionKeysResponseFromJSON,
    ConfigTapeEncryptionKeysCreateTapeEncryptionKeysResponseToJSON,
} from '../models/ConfigTapeEncryptionKeysCreateTapeEncryptionKeysResponse';
import {
    type ConfigTapeEncryptionKeysDeleteTapeEncryptionKeysResponse,
    ConfigTapeEncryptionKeysDeleteTapeEncryptionKeysResponseFromJSON,
    ConfigTapeEncryptionKeysDeleteTapeEncryptionKeysResponseToJSON,
} from '../models/ConfigTapeEncryptionKeysDeleteTapeEncryptionKeysResponse';
import {
    type ConfigTapeEncryptionKeysGetConfigTapeEncryptionKeysByFingerprintResponse,
    ConfigTapeEncryptionKeysGetConfigTapeEncryptionKeysByFingerprintResponseFromJSON,
    ConfigTapeEncryptionKeysGetConfigTapeEncryptionKeysByFingerprintResponseToJSON,
} from '../models/ConfigTapeEncryptionKeysGetConfigTapeEncryptionKeysByFingerprintResponse';
import {
    type ConfigTapeEncryptionKeysGetTapeEncryptionKeysResponse,
    ConfigTapeEncryptionKeysGetTapeEncryptionKeysResponseFromJSON,
    ConfigTapeEncryptionKeysGetTapeEncryptionKeysResponseToJSON,
} from '../models/ConfigTapeEncryptionKeysGetTapeEncryptionKeysResponse';
import {
    type ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest,
    ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequestFromJSON,
    ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequestToJSON,
} from '../models/ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest';
import {
    type ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysResponse,
    ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysResponseFromJSON,
    ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysResponseToJSON,
} from '../models/ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysResponse';
import {
    type PbsError,
    PbsErrorFromJSON,
    PbsErrorToJSON,
} from '../models/PbsError';

export interface ConfigTapeEncryptionKeysApiCreateTapeEncryptionKeysRequest {
    configTapeEncryptionKeysCreateTapeEncryptionKeysRequest: ConfigTapeEncryptionKeysCreateTapeEncryptionKeysRequest;
}

export interface ConfigTapeEncryptionKeysApiDeleteTapeEncryptionKeysRequest {
    fingerprint: string;
    digest?: string;
}

export interface ConfigTapeEncryptionKeysApiGetConfigTapeEncryptionKeysByFingerprintRequest {
    fingerprint: string;
}

export interface ConfigTapeEncryptionKeysApiUpdateTapeEncryptionKeysRequest {
    fingerprint: string;
    configTapeEncryptionKeysUpdateTapeEncryptionKeysRequest: ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest;
}

/**
 * 
 */
export class ConfigTapeEncryptionKeysApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTapeEncryptionKeys without sending the request
     */
    async createTapeEncryptionKeysRequestOpts(requestParameters: ConfigTapeEncryptionKeysApiCreateTapeEncryptionKeysRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['configTapeEncryptionKeysCreateTapeEncryptionKeysRequest'] == null) {
            throw new runtime.RequiredError(
                'configTapeEncryptionKeysCreateTapeEncryptionKeysRequest',
                'Required parameter "configTapeEncryptionKeysCreateTapeEncryptionKeysRequest" was null or undefined when calling createTapeEncryptionKeys().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/tape-encryption-keys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigTapeEncryptionKeysCreateTapeEncryptionKeysRequestToJSON(requestParameters['configTapeEncryptionKeysCreateTapeEncryptionKeysRequest']),
        };
    }

    /**
     * Create a new encryption key
     * Create a new encryption key
     */
    async createTapeEncryptionKeysRaw(requestParameters: ConfigTapeEncryptionKeysApiCreateTapeEncryptionKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigTapeEncryptionKeysCreateTapeEncryptionKeysResponse>> {
        const requestOptions = await this.createTapeEncryptionKeysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigTapeEncryptionKeysCreateTapeEncryptionKeysResponseFromJSON(jsonValue));
    }

    /**
     * Create a new encryption key
     * Create a new encryption key
     */
    async createTapeEncryptionKeys(requestParameters: ConfigTapeEncryptionKeysApiCreateTapeEncryptionKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigTapeEncryptionKeysCreateTapeEncryptionKeysResponse> {
        const response = await this.createTapeEncryptionKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTapeEncryptionKeys without sending the request
     */
    async deleteTapeEncryptionKeysRequestOpts(requestParameters: ConfigTapeEncryptionKeysApiDeleteTapeEncryptionKeysRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fingerprint'] == null) {
            throw new runtime.RequiredError(
                'fingerprint',
                'Required parameter "fingerprint" was null or undefined when calling deleteTapeEncryptionKeys().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['digest'] != null) {
            queryParameters['digest'] = requestParameters['digest'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/tape-encryption-keys/{fingerprint}`;
        urlPath = urlPath.replace('{fingerprint}', encodeURIComponent(String(requestParameters['fingerprint'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a encryption key from the database  Please note that you can no longer access tapes using this key.
     * Remove a encryption key from the database
     */
    async deleteTapeEncryptionKeysRaw(requestParameters: ConfigTapeEncryptionKeysApiDeleteTapeEncryptionKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigTapeEncryptionKeysDeleteTapeEncryptionKeysResponse>> {
        const requestOptions = await this.deleteTapeEncryptionKeysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigTapeEncryptionKeysDeleteTapeEncryptionKeysResponseFromJSON(jsonValue));
    }

    /**
     * Remove a encryption key from the database  Please note that you can no longer access tapes using this key.
     * Remove a encryption key from the database
     */
    async deleteTapeEncryptionKeys(requestParameters: ConfigTapeEncryptionKeysApiDeleteTapeEncryptionKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigTapeEncryptionKeysDeleteTapeEncryptionKeysResponse> {
        const response = await this.deleteTapeEncryptionKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConfigTapeEncryptionKeysByFingerprint without sending the request
     */
    async getConfigTapeEncryptionKeysByFingerprintRequestOpts(requestParameters: ConfigTapeEncryptionKeysApiGetConfigTapeEncryptionKeysByFingerprintRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fingerprint'] == null) {
            throw new runtime.RequiredError(
                'fingerprint',
                'Required parameter "fingerprint" was null or undefined when calling getConfigTapeEncryptionKeysByFingerprint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/tape-encryption-keys/{fingerprint}`;
        urlPath = urlPath.replace('{fingerprint}', encodeURIComponent(String(requestParameters['fingerprint'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get key config (public key part)
     * Get key config (public key part)
     */
    async getConfigTapeEncryptionKeysByFingerprintRaw(requestParameters: ConfigTapeEncryptionKeysApiGetConfigTapeEncryptionKeysByFingerprintRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigTapeEncryptionKeysGetConfigTapeEncryptionKeysByFingerprintResponse>> {
        const requestOptions = await this.getConfigTapeEncryptionKeysByFingerprintRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigTapeEncryptionKeysGetConfigTapeEncryptionKeysByFingerprintResponseFromJSON(jsonValue));
    }

    /**
     * Get key config (public key part)
     * Get key config (public key part)
     */
    async getConfigTapeEncryptionKeysByFingerprint(requestParameters: ConfigTapeEncryptionKeysApiGetConfigTapeEncryptionKeysByFingerprintRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigTapeEncryptionKeysGetConfigTapeEncryptionKeysByFingerprintResponse> {
        const response = await this.getConfigTapeEncryptionKeysByFingerprintRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTapeEncryptionKeys without sending the request
     */
    async getTapeEncryptionKeysRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/tape-encryption-keys`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List existing keys
     * List existing keys
     */
    async getTapeEncryptionKeysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigTapeEncryptionKeysGetTapeEncryptionKeysResponse>> {
        const requestOptions = await this.getTapeEncryptionKeysRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigTapeEncryptionKeysGetTapeEncryptionKeysResponseFromJSON(jsonValue));
    }

    /**
     * List existing keys
     * List existing keys
     */
    async getTapeEncryptionKeys(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigTapeEncryptionKeysGetTapeEncryptionKeysResponse> {
        const response = await this.getTapeEncryptionKeysRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTapeEncryptionKeys without sending the request
     */
    async updateTapeEncryptionKeysRequestOpts(requestParameters: ConfigTapeEncryptionKeysApiUpdateTapeEncryptionKeysRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fingerprint'] == null) {
            throw new runtime.RequiredError(
                'fingerprint',
                'Required parameter "fingerprint" was null or undefined when calling updateTapeEncryptionKeys().'
            );
        }

        if (requestParameters['configTapeEncryptionKeysUpdateTapeEncryptionKeysRequest'] == null) {
            throw new runtime.RequiredError(
                'configTapeEncryptionKeysUpdateTapeEncryptionKeysRequest',
                'Required parameter "configTapeEncryptionKeysUpdateTapeEncryptionKeysRequest" was null or undefined when calling updateTapeEncryptionKeys().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/tape-encryption-keys/{fingerprint}`;
        urlPath = urlPath.replace('{fingerprint}', encodeURIComponent(String(requestParameters['fingerprint'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequestToJSON(requestParameters['configTapeEncryptionKeysUpdateTapeEncryptionKeysRequest']),
        };
    }

    /**
     * Change the encryption key\'s password (and password hint).
     * Change the encryption key\'s password (and password hint)
     */
    async updateTapeEncryptionKeysRaw(requestParameters: ConfigTapeEncryptionKeysApiUpdateTapeEncryptionKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysResponse>> {
        const requestOptions = await this.updateTapeEncryptionKeysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysResponseFromJSON(jsonValue));
    }

    /**
     * Change the encryption key\'s password (and password hint).
     * Change the encryption key\'s password (and password hint)
     */
    async updateTapeEncryptionKeys(requestParameters: ConfigTapeEncryptionKeysApiUpdateTapeEncryptionKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysResponse> {
        const response = await this.updateTapeEncryptionKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
