/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ConfigVerifyCreateVerifyRequest,
    ConfigVerifyCreateVerifyRequestFromJSON,
    ConfigVerifyCreateVerifyRequestToJSON,
} from '../models/ConfigVerifyCreateVerifyRequest';
import {
    type ConfigVerifyCreateVerifyResponse,
    ConfigVerifyCreateVerifyResponseFromJSON,
    ConfigVerifyCreateVerifyResponseToJSON,
} from '../models/ConfigVerifyCreateVerifyResponse';
import {
    type ConfigVerifyDeleteVerifyResponse,
    ConfigVerifyDeleteVerifyResponseFromJSON,
    ConfigVerifyDeleteVerifyResponseToJSON,
} from '../models/ConfigVerifyDeleteVerifyResponse';
import {
    type ConfigVerifyGetConfigVerifyByIdResponse,
    ConfigVerifyGetConfigVerifyByIdResponseFromJSON,
    ConfigVerifyGetConfigVerifyByIdResponseToJSON,
} from '../models/ConfigVerifyGetConfigVerifyByIdResponse';
import {
    type ConfigVerifyGetVerifyResponse,
    ConfigVerifyGetVerifyResponseFromJSON,
    ConfigVerifyGetVerifyResponseToJSON,
} from '../models/ConfigVerifyGetVerifyResponse';
import {
    type ConfigVerifyUpdateVerifyRequest,
    ConfigVerifyUpdateVerifyRequestFromJSON,
    ConfigVerifyUpdateVerifyRequestToJSON,
} from '../models/ConfigVerifyUpdateVerifyRequest';
import {
    type ConfigVerifyUpdateVerifyResponse,
    ConfigVerifyUpdateVerifyResponseFromJSON,
    ConfigVerifyUpdateVerifyResponseToJSON,
} from '../models/ConfigVerifyUpdateVerifyResponse';
import {
    type PbsError,
    PbsErrorFromJSON,
    PbsErrorToJSON,
} from '../models/PbsError';

export interface ConfigVerifyApiCreateVerifyRequest {
    configVerifyCreateVerifyRequest: ConfigVerifyCreateVerifyRequest;
}

export interface ConfigVerifyApiDeleteVerifyRequest {
    id: string;
    digest?: string;
}

export interface ConfigVerifyApiGetConfigVerifyByIdRequest {
    id: string;
}

export interface ConfigVerifyApiUpdateVerifyRequest {
    id: string;
    configVerifyUpdateVerifyRequest?: ConfigVerifyUpdateVerifyRequest;
}

/**
 * 
 */
export class ConfigVerifyApi extends runtime.BaseAPI {

    /**
     * Creates request options for createVerify without sending the request
     */
    async createVerifyRequestOpts(requestParameters: ConfigVerifyApiCreateVerifyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['configVerifyCreateVerifyRequest'] == null) {
            throw new runtime.RequiredError(
                'configVerifyCreateVerifyRequest',
                'Required parameter "configVerifyCreateVerifyRequest" was null or undefined when calling createVerify().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/verify`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigVerifyCreateVerifyRequestToJSON(requestParameters['configVerifyCreateVerifyRequest']),
        };
    }

    /**
     * Create a new verification job.  Permissions: Requires Datastore.Verify on job\'s datastore.
     * Create a new verification job
     */
    async createVerifyRaw(requestParameters: ConfigVerifyApiCreateVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigVerifyCreateVerifyResponse>> {
        const requestOptions = await this.createVerifyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigVerifyCreateVerifyResponseFromJSON(jsonValue));
    }

    /**
     * Create a new verification job.  Permissions: Requires Datastore.Verify on job\'s datastore.
     * Create a new verification job
     */
    async createVerify(requestParameters: ConfigVerifyApiCreateVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigVerifyCreateVerifyResponse> {
        const response = await this.createVerifyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteVerify without sending the request
     */
    async deleteVerifyRequestOpts(requestParameters: ConfigVerifyApiDeleteVerifyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteVerify().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['digest'] != null) {
            queryParameters['digest'] = requestParameters['digest'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/verify/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a verification job configuration  Permissions: Requires Datastore.Verify on job\'s datastore.
     * Remove a verification job configuration
     */
    async deleteVerifyRaw(requestParameters: ConfigVerifyApiDeleteVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigVerifyDeleteVerifyResponse>> {
        const requestOptions = await this.deleteVerifyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigVerifyDeleteVerifyResponseFromJSON(jsonValue));
    }

    /**
     * Remove a verification job configuration  Permissions: Requires Datastore.Verify on job\'s datastore.
     * Remove a verification job configuration
     */
    async deleteVerify(requestParameters: ConfigVerifyApiDeleteVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigVerifyDeleteVerifyResponse> {
        const response = await this.deleteVerifyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConfigVerifyById without sending the request
     */
    async getConfigVerifyByIdRequestOpts(requestParameters: ConfigVerifyApiGetConfigVerifyByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getConfigVerifyById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/verify/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read a verification job configuration.  Permissions: Requires Datastore.Audit or Datastore.Verify on job\'s datastore.
     * Read a verification job configuration
     */
    async getConfigVerifyByIdRaw(requestParameters: ConfigVerifyApiGetConfigVerifyByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigVerifyGetConfigVerifyByIdResponse>> {
        const requestOptions = await this.getConfigVerifyByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigVerifyGetConfigVerifyByIdResponseFromJSON(jsonValue));
    }

    /**
     * Read a verification job configuration.  Permissions: Requires Datastore.Audit or Datastore.Verify on job\'s datastore.
     * Read a verification job configuration
     */
    async getConfigVerifyById(requestParameters: ConfigVerifyApiGetConfigVerifyByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigVerifyGetConfigVerifyByIdResponse> {
        const response = await this.getConfigVerifyByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVerify without sending the request
     */
    async getVerifyRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/verify`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all verification jobs  Permissions: Requires Datastore.Audit or Datastore.Verify on datastore.
     * List all verification jobs
     */
    async getVerifyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigVerifyGetVerifyResponse>> {
        const requestOptions = await this.getVerifyRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigVerifyGetVerifyResponseFromJSON(jsonValue));
    }

    /**
     * List all verification jobs  Permissions: Requires Datastore.Audit or Datastore.Verify on datastore.
     * List all verification jobs
     */
    async getVerify(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigVerifyGetVerifyResponse> {
        const response = await this.getVerifyRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateVerify without sending the request
     */
    async updateVerifyRequestOpts(requestParameters: ConfigVerifyApiUpdateVerifyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateVerify().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/verify/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigVerifyUpdateVerifyRequestToJSON(requestParameters['configVerifyUpdateVerifyRequest']),
        };
    }

    /**
     * Update verification job config.  Permissions: Requires Datastore.Verify on job\'s datastore.
     * Update verification job config
     */
    async updateVerifyRaw(requestParameters: ConfigVerifyApiUpdateVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigVerifyUpdateVerifyResponse>> {
        const requestOptions = await this.updateVerifyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigVerifyUpdateVerifyResponseFromJSON(jsonValue));
    }

    /**
     * Update verification job config.  Permissions: Requires Datastore.Verify on job\'s datastore.
     * Update verification job config
     */
    async updateVerify(requestParameters: ConfigVerifyApiUpdateVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigVerifyUpdateVerifyResponse> {
        const response = await this.updateVerifyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
