/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NodesNetworkCreateNetworkRequest,
    NodesNetworkCreateNetworkRequestFromJSON,
    NodesNetworkCreateNetworkRequestToJSON,
} from '../models/NodesNetworkCreateNetworkRequest';
import {
    type NodesNetworkCreateNetworkResponse,
    NodesNetworkCreateNetworkResponseFromJSON,
    NodesNetworkCreateNetworkResponseToJSON,
} from '../models/NodesNetworkCreateNetworkResponse';
import {
    type NodesNetworkDeleteNetworkResponse,
    NodesNetworkDeleteNetworkResponseFromJSON,
    NodesNetworkDeleteNetworkResponseToJSON,
} from '../models/NodesNetworkDeleteNetworkResponse';
import {
    type NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse,
    NodesNetworkDeleteNodesByNodeNetworkByIfaceResponseFromJSON,
    NodesNetworkDeleteNodesByNodeNetworkByIfaceResponseToJSON,
} from '../models/NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse';
import {
    type NodesNetworkGetNetworkResponse,
    NodesNetworkGetNetworkResponseFromJSON,
    NodesNetworkGetNetworkResponseToJSON,
} from '../models/NodesNetworkGetNetworkResponse';
import {
    type NodesNetworkGetNodesByNodeNetworkByIfaceResponse,
    NodesNetworkGetNodesByNodeNetworkByIfaceResponseFromJSON,
    NodesNetworkGetNodesByNodeNetworkByIfaceResponseToJSON,
} from '../models/NodesNetworkGetNodesByNodeNetworkByIfaceResponse';
import {
    type NodesNetworkUpdateNetworkResponse,
    NodesNetworkUpdateNetworkResponseFromJSON,
    NodesNetworkUpdateNetworkResponseToJSON,
} from '../models/NodesNetworkUpdateNetworkResponse';
import {
    type NodesNetworkUpdateNodesByNodeNetworkByIfaceRequest,
    NodesNetworkUpdateNodesByNodeNetworkByIfaceRequestFromJSON,
    NodesNetworkUpdateNodesByNodeNetworkByIfaceRequestToJSON,
} from '../models/NodesNetworkUpdateNodesByNodeNetworkByIfaceRequest';
import {
    type NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse,
    NodesNetworkUpdateNodesByNodeNetworkByIfaceResponseFromJSON,
    NodesNetworkUpdateNodesByNodeNetworkByIfaceResponseToJSON,
} from '../models/NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse';
import {
    type PbsError,
    PbsErrorFromJSON,
    PbsErrorToJSON,
} from '../models/PbsError';

export interface NodesNetworkApiCreateNetworkRequest {
    node: string;
    nodesNetworkCreateNetworkRequest: NodesNetworkCreateNetworkRequest;
}

export interface NodesNetworkApiDeleteNetworkRequest {
    node: string;
}

export interface NodesNetworkApiDeleteNodesByNodeNetworkByIfaceRequest {
    iface: string;
    node: string;
    digest?: string;
}

export interface NodesNetworkApiGetNetworkRequest {
    node: string;
}

export interface NodesNetworkApiGetNodesByNodeNetworkByIfaceRequest {
    iface: string;
    node: string;
}

export interface NodesNetworkApiUpdateNetworkRequest {
    node: string;
}

export interface NodesNetworkApiUpdateNodesByNodeNetworkByIfaceRequest {
    iface: string;
    node: string;
    nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest?: NodesNetworkUpdateNodesByNodeNetworkByIfaceRequest;
}

/**
 * 
 */
export class NodesNetworkApi extends runtime.BaseAPI {

    /**
     * Creates request options for createNetwork without sending the request
     */
    async createNetworkRequestOpts(requestParameters: NodesNetworkApiCreateNetworkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling createNetwork().'
            );
        }

        if (requestParameters['nodesNetworkCreateNetworkRequest'] == null) {
            throw new runtime.RequiredError(
                'nodesNetworkCreateNetworkRequest',
                'Required parameter "nodesNetworkCreateNetworkRequest" was null or undefined when calling createNetwork().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/network`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesNetworkCreateNetworkRequestToJSON(requestParameters['nodesNetworkCreateNetworkRequest']),
        };
    }

    /**
     * Create network interface configuration.
     * Create network interface configuration
     */
    async createNetworkRaw(requestParameters: NodesNetworkApiCreateNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesNetworkCreateNetworkResponse>> {
        const requestOptions = await this.createNetworkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesNetworkCreateNetworkResponseFromJSON(jsonValue));
    }

    /**
     * Create network interface configuration.
     * Create network interface configuration
     */
    async createNetwork(requestParameters: NodesNetworkApiCreateNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesNetworkCreateNetworkResponse> {
        const response = await this.createNetworkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteNetwork without sending the request
     */
    async deleteNetworkRequestOpts(requestParameters: NodesNetworkApiDeleteNetworkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling deleteNetwork().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/network`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revert network configuration (rm /etc/network/interfaces.new).
     * Revert network configuration (rm /etc/network/interfaces
     */
    async deleteNetworkRaw(requestParameters: NodesNetworkApiDeleteNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesNetworkDeleteNetworkResponse>> {
        const requestOptions = await this.deleteNetworkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesNetworkDeleteNetworkResponseFromJSON(jsonValue));
    }

    /**
     * Revert network configuration (rm /etc/network/interfaces.new).
     * Revert network configuration (rm /etc/network/interfaces
     */
    async deleteNetwork(requestParameters: NodesNetworkApiDeleteNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesNetworkDeleteNetworkResponse> {
        const response = await this.deleteNetworkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteNodesByNodeNetworkByIface without sending the request
     */
    async deleteNodesByNodeNetworkByIfaceRequestOpts(requestParameters: NodesNetworkApiDeleteNodesByNodeNetworkByIfaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['iface'] == null) {
            throw new runtime.RequiredError(
                'iface',
                'Required parameter "iface" was null or undefined when calling deleteNodesByNodeNetworkByIface().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling deleteNodesByNodeNetworkByIface().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['digest'] != null) {
            queryParameters['digest'] = requestParameters['digest'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/network/{iface}`;
        urlPath = urlPath.replace('{iface}', encodeURIComponent(String(requestParameters['iface'])));
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove network interface configuration.
     * Remove network interface configuration
     */
    async deleteNodesByNodeNetworkByIfaceRaw(requestParameters: NodesNetworkApiDeleteNodesByNodeNetworkByIfaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse>> {
        const requestOptions = await this.deleteNodesByNodeNetworkByIfaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesNetworkDeleteNodesByNodeNetworkByIfaceResponseFromJSON(jsonValue));
    }

    /**
     * Remove network interface configuration.
     * Remove network interface configuration
     */
    async deleteNodesByNodeNetworkByIface(requestParameters: NodesNetworkApiDeleteNodesByNodeNetworkByIfaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse> {
        const response = await this.deleteNodesByNodeNetworkByIfaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNetwork without sending the request
     */
    async getNetworkRequestOpts(requestParameters: NodesNetworkApiGetNetworkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getNetwork().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/network`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all datastores
     * List all datastores
     */
    async getNetworkRaw(requestParameters: NodesNetworkApiGetNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesNetworkGetNetworkResponse>> {
        const requestOptions = await this.getNetworkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesNetworkGetNetworkResponseFromJSON(jsonValue));
    }

    /**
     * List all datastores
     * List all datastores
     */
    async getNetwork(requestParameters: NodesNetworkApiGetNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesNetworkGetNetworkResponse> {
        const response = await this.getNetworkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNodesByNodeNetworkByIface without sending the request
     */
    async getNodesByNodeNetworkByIfaceRequestOpts(requestParameters: NodesNetworkApiGetNodesByNodeNetworkByIfaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['iface'] == null) {
            throw new runtime.RequiredError(
                'iface',
                'Required parameter "iface" was null or undefined when calling getNodesByNodeNetworkByIface().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getNodesByNodeNetworkByIface().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/network/{iface}`;
        urlPath = urlPath.replace('{iface}', encodeURIComponent(String(requestParameters['iface'])));
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read a network interface configuration.
     * Read a network interface configuration
     */
    async getNodesByNodeNetworkByIfaceRaw(requestParameters: NodesNetworkApiGetNodesByNodeNetworkByIfaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesNetworkGetNodesByNodeNetworkByIfaceResponse>> {
        const requestOptions = await this.getNodesByNodeNetworkByIfaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesNetworkGetNodesByNodeNetworkByIfaceResponseFromJSON(jsonValue));
    }

    /**
     * Read a network interface configuration.
     * Read a network interface configuration
     */
    async getNodesByNodeNetworkByIface(requestParameters: NodesNetworkApiGetNodesByNodeNetworkByIfaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesNetworkGetNodesByNodeNetworkByIfaceResponse> {
        const response = await this.getNodesByNodeNetworkByIfaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateNetwork without sending the request
     */
    async updateNetworkRequestOpts(requestParameters: NodesNetworkApiUpdateNetworkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling updateNetwork().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/network`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Reload network configuration (requires ifupdown2).
     * Reload network configuration (requires ifupdown2)
     */
    async updateNetworkRaw(requestParameters: NodesNetworkApiUpdateNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesNetworkUpdateNetworkResponse>> {
        const requestOptions = await this.updateNetworkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesNetworkUpdateNetworkResponseFromJSON(jsonValue));
    }

    /**
     * Reload network configuration (requires ifupdown2).
     * Reload network configuration (requires ifupdown2)
     */
    async updateNetwork(requestParameters: NodesNetworkApiUpdateNetworkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesNetworkUpdateNetworkResponse> {
        const response = await this.updateNetworkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateNodesByNodeNetworkByIface without sending the request
     */
    async updateNodesByNodeNetworkByIfaceRequestOpts(requestParameters: NodesNetworkApiUpdateNodesByNodeNetworkByIfaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['iface'] == null) {
            throw new runtime.RequiredError(
                'iface',
                'Required parameter "iface" was null or undefined when calling updateNodesByNodeNetworkByIface().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling updateNodesByNodeNetworkByIface().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        // Optional body: only emit Content-Type when the body is actually provided.
        // PVE/PMG Perl HTTP server rejects empty bodies with Content-Type: application/json
        // ("malformed JSON string"), and other Proxmox products are equally fussy.
        if (requestParameters['nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest'] != null) {
            headerParameters['Content-Type'] = 'application/json';
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/network/{iface}`;
        urlPath = urlPath.replace('{iface}', encodeURIComponent(String(requestParameters['iface'])));
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NodesNetworkUpdateNodesByNodeNetworkByIfaceRequestToJSON(requestParameters['nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest']),
        };
    }

    /**
     * Update network interface config.
     * Update network interface config
     */
    async updateNodesByNodeNetworkByIfaceRaw(requestParameters: NodesNetworkApiUpdateNodesByNodeNetworkByIfaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse>> {
        const requestOptions = await this.updateNodesByNodeNetworkByIfaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesNetworkUpdateNodesByNodeNetworkByIfaceResponseFromJSON(jsonValue));
    }

    /**
     * Update network interface config.
     * Update network interface config
     */
    async updateNodesByNodeNetworkByIface(requestParameters: NodesNetworkApiUpdateNodesByNodeNetworkByIfaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse> {
        const response = await this.updateNodesByNodeNetworkByIfaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
