/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NodesServicesCreateReloadResponse,
    NodesServicesCreateReloadResponseFromJSON,
    NodesServicesCreateReloadResponseToJSON,
} from '../models/NodesServicesCreateReloadResponse';
import {
    type NodesServicesCreateRestartResponse,
    NodesServicesCreateRestartResponseFromJSON,
    NodesServicesCreateRestartResponseToJSON,
} from '../models/NodesServicesCreateRestartResponse';
import {
    type NodesServicesCreateStartResponse,
    NodesServicesCreateStartResponseFromJSON,
    NodesServicesCreateStartResponseToJSON,
} from '../models/NodesServicesCreateStartResponse';
import {
    type NodesServicesCreateStopResponse,
    NodesServicesCreateStopResponseFromJSON,
    NodesServicesCreateStopResponseToJSON,
} from '../models/NodesServicesCreateStopResponse';
import {
    type NodesServicesGetNodesByNodeServicesByServiceResponse,
    NodesServicesGetNodesByNodeServicesByServiceResponseFromJSON,
    NodesServicesGetNodesByNodeServicesByServiceResponseToJSON,
} from '../models/NodesServicesGetNodesByNodeServicesByServiceResponse';
import {
    type NodesServicesGetServicesResponse,
    NodesServicesGetServicesResponseFromJSON,
    NodesServicesGetServicesResponseToJSON,
} from '../models/NodesServicesGetServicesResponse';
import {
    type NodesServicesGetStateResponse,
    NodesServicesGetStateResponseFromJSON,
    NodesServicesGetStateResponseToJSON,
} from '../models/NodesServicesGetStateResponse';
import {
    type PbsError,
    PbsErrorFromJSON,
    PbsErrorToJSON,
} from '../models/PbsError';

export interface NodesServicesApiCreateReloadRequest {
    node: string;
    service: string;
}

export interface NodesServicesApiCreateRestartRequest {
    node: string;
    service: string;
}

export interface NodesServicesApiCreateStartRequest {
    node: string;
    service: string;
}

export interface NodesServicesApiCreateStopRequest {
    node: string;
    service: string;
}

export interface NodesServicesApiGetNodesByNodeServicesByServiceRequest {
    node: string;
    service: string;
}

export interface NodesServicesApiGetServicesRequest {
    node: string;
}

export interface NodesServicesApiGetStateRequest {
    node: string;
    service: string;
}

/**
 * 
 */
export class NodesServicesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createReload without sending the request
     */
    async createReloadRequestOpts(requestParameters: NodesServicesApiCreateReloadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling createReload().'
            );
        }

        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError(
                'service',
                'Required parameter "service" was null or undefined when calling createReload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/services/{service}/reload`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{service}', encodeURIComponent(String(requestParameters['service'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Reload service.
     * Reload service
     */
    async createReloadRaw(requestParameters: NodesServicesApiCreateReloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesServicesCreateReloadResponse>> {
        const requestOptions = await this.createReloadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesServicesCreateReloadResponseFromJSON(jsonValue));
    }

    /**
     * Reload service.
     * Reload service
     */
    async createReload(requestParameters: NodesServicesApiCreateReloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesServicesCreateReloadResponse> {
        const response = await this.createReloadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createRestart without sending the request
     */
    async createRestartRequestOpts(requestParameters: NodesServicesApiCreateRestartRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling createRestart().'
            );
        }

        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError(
                'service',
                'Required parameter "service" was null or undefined when calling createRestart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/services/{service}/restart`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{service}', encodeURIComponent(String(requestParameters['service'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Restart service.
     * Restart service
     */
    async createRestartRaw(requestParameters: NodesServicesApiCreateRestartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesServicesCreateRestartResponse>> {
        const requestOptions = await this.createRestartRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesServicesCreateRestartResponseFromJSON(jsonValue));
    }

    /**
     * Restart service.
     * Restart service
     */
    async createRestart(requestParameters: NodesServicesApiCreateRestartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesServicesCreateRestartResponse> {
        const response = await this.createRestartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createStart without sending the request
     */
    async createStartRequestOpts(requestParameters: NodesServicesApiCreateStartRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling createStart().'
            );
        }

        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError(
                'service',
                'Required parameter "service" was null or undefined when calling createStart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/services/{service}/start`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{service}', encodeURIComponent(String(requestParameters['service'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Start service.
     * Start service
     */
    async createStartRaw(requestParameters: NodesServicesApiCreateStartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesServicesCreateStartResponse>> {
        const requestOptions = await this.createStartRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesServicesCreateStartResponseFromJSON(jsonValue));
    }

    /**
     * Start service.
     * Start service
     */
    async createStart(requestParameters: NodesServicesApiCreateStartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesServicesCreateStartResponse> {
        const response = await this.createStartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createStop without sending the request
     */
    async createStopRequestOpts(requestParameters: NodesServicesApiCreateStopRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling createStop().'
            );
        }

        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError(
                'service',
                'Required parameter "service" was null or undefined when calling createStop().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/services/{service}/stop`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{service}', encodeURIComponent(String(requestParameters['service'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stop service.
     * Stop service
     */
    async createStopRaw(requestParameters: NodesServicesApiCreateStopRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesServicesCreateStopResponse>> {
        const requestOptions = await this.createStopRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesServicesCreateStopResponseFromJSON(jsonValue));
    }

    /**
     * Stop service.
     * Stop service
     */
    async createStop(requestParameters: NodesServicesApiCreateStopRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesServicesCreateStopResponse> {
        const response = await this.createStopRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNodesByNodeServicesByService without sending the request
     */
    async getNodesByNodeServicesByServiceRequestOpts(requestParameters: NodesServicesApiGetNodesByNodeServicesByServiceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getNodesByNodeServicesByService().'
            );
        }

        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError(
                'service',
                'Required parameter "service" was null or undefined when calling getNodesByNodeServicesByService().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/services/{service}`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{service}', encodeURIComponent(String(requestParameters['service'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Directory index.
     * Directory index
     */
    async getNodesByNodeServicesByServiceRaw(requestParameters: NodesServicesApiGetNodesByNodeServicesByServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesServicesGetNodesByNodeServicesByServiceResponse>> {
        const requestOptions = await this.getNodesByNodeServicesByServiceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesServicesGetNodesByNodeServicesByServiceResponseFromJSON(jsonValue));
    }

    /**
     * Directory index.
     * Directory index
     */
    async getNodesByNodeServicesByService(requestParameters: NodesServicesApiGetNodesByNodeServicesByServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesServicesGetNodesByNodeServicesByServiceResponse> {
        const response = await this.getNodesByNodeServicesByServiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getServices without sending the request
     */
    async getServicesRequestOpts(requestParameters: NodesServicesApiGetServicesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getServices().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/services`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Service list.
     * Service list
     */
    async getServicesRaw(requestParameters: NodesServicesApiGetServicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesServicesGetServicesResponse>> {
        const requestOptions = await this.getServicesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesServicesGetServicesResponseFromJSON(jsonValue));
    }

    /**
     * Service list.
     * Service list
     */
    async getServices(requestParameters: NodesServicesApiGetServicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesServicesGetServicesResponse> {
        const response = await this.getServicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getState without sending the request
     */
    async getStateRequestOpts(requestParameters: NodesServicesApiGetStateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getState().'
            );
        }

        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError(
                'service',
                'Required parameter "service" was null or undefined when calling getState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/services/{service}/state`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{service}', encodeURIComponent(String(requestParameters['service'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read service properties.
     * Read service properties
     */
    async getStateRaw(requestParameters: NodesServicesApiGetStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesServicesGetStateResponse>> {
        const requestOptions = await this.getStateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesServicesGetStateResponseFromJSON(jsonValue));
    }

    /**
     * Read service properties.
     * Read service properties
     */
    async getState(requestParameters: NodesServicesApiGetStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesServicesGetStateResponse> {
        const response = await this.getStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
