/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PbsError,
    PbsErrorFromJSON,
    PbsErrorToJSON,
} from '../models/PbsError';
import {
    type PingGetPingResponse,
    PingGetPingResponseFromJSON,
    PingGetPingResponseToJSON,
} from '../models/PingGetPingResponse';

/**
 * 
 */
export class PingApi extends runtime.BaseAPI {

    /**
     * Creates request options for getPing without sending the request
     */
    async getPingRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ping`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Dummy method which replies with `{ \"pong\": True }`  Permissions: Anyone can access this, because it\'s used for a cheap check if the API daemon is online.
     * Dummy method which replies with `{ \"pong\": True }`
     */
    async getPingRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PingGetPingResponse>> {
        const requestOptions = await this.getPingRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PingGetPingResponseFromJSON(jsonValue));
    }

    /**
     * Dummy method which replies with `{ \"pong\": True }`  Permissions: Anyone can access this, because it\'s used for a cheap check if the API daemon is online.
     * Dummy method which replies with `{ \"pong\": True }`
     */
    async getPing(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PingGetPingResponse> {
        const response = await this.getPingRaw(initOverrides);
        return await response.value();
    }

}
