/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PbsError,
    PbsErrorFromJSON,
    PbsErrorToJSON,
} from '../models/PbsError';
import {
    type PullCreatePullRequest,
    PullCreatePullRequestFromJSON,
    PullCreatePullRequestToJSON,
} from '../models/PullCreatePullRequest';
import {
    type PullCreatePullResponse,
    PullCreatePullResponseFromJSON,
    PullCreatePullResponseToJSON,
} from '../models/PullCreatePullResponse';

export interface PullApiCreatePullRequest {
    pullCreatePullRequest: PullCreatePullRequest;
}

/**
 * 
 */
export class PullApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPull without sending the request
     */
    async createPullRequestOpts(requestParameters: PullApiCreatePullRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pullCreatePullRequest'] == null) {
            throw new runtime.RequiredError(
                'pullCreatePullRequest',
                'Required parameter "pullCreatePullRequest" was null or undefined when calling createPull().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/pull`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PullCreatePullRequestToJSON(requestParameters['pullCreatePullRequest']),
        };
    }

    /**
     * Sync store from other repository  Permissions: The user needs Datastore.Backup privilege on \'/datastore/{store}\', and needs to own the backup group. Remote.Read is required on \'/remote/{remote}/{remote-store}\'. The delete flag additionally requires the Datastore.Prune privilege on \'/datastore/{store}\'.
     * Sync store from other repository
     */
    async createPullRaw(requestParameters: PullApiCreatePullRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullCreatePullResponse>> {
        const requestOptions = await this.createPullRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullCreatePullResponseFromJSON(jsonValue));
    }

    /**
     * Sync store from other repository  Permissions: The user needs Datastore.Backup privilege on \'/datastore/{store}\', and needs to own the backup group. Remote.Read is required on \'/remote/{remote}/{remote-store}\'. The delete flag additionally requires the Datastore.Prune privilege on \'/datastore/{store}\'.
     * Sync store from other repository
     */
    async createPull(requestParameters: PullApiCreatePullRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullCreatePullResponse> {
        const response = await this.createPullRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
