/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PbsError,
    PbsErrorFromJSON,
    PbsErrorToJSON,
} from '../models/PbsError';
import {
    type TapeCreateRestoreRequest,
    TapeCreateRestoreRequestFromJSON,
    TapeCreateRestoreRequestToJSON,
} from '../models/TapeCreateRestoreRequest';
import {
    type TapeCreateRestoreResponse,
    TapeCreateRestoreResponseFromJSON,
    TapeCreateRestoreResponseToJSON,
} from '../models/TapeCreateRestoreResponse';
import {
    type TapeGetScanChangersResponse,
    TapeGetScanChangersResponseFromJSON,
    TapeGetScanChangersResponseToJSON,
} from '../models/TapeGetScanChangersResponse';
import {
    type TapeGetScanDrivesResponse,
    TapeGetScanDrivesResponseFromJSON,
    TapeGetScanDrivesResponseToJSON,
} from '../models/TapeGetScanDrivesResponse';
import {
    type TapeGetTapeResponse,
    TapeGetTapeResponseFromJSON,
    TapeGetTapeResponseToJSON,
} from '../models/TapeGetTapeResponse';

export interface TapeApiCreateRestoreRequest {
    tapeCreateRestoreRequest: TapeCreateRestoreRequest;
}

/**
 * 
 */
export class TapeApi extends runtime.BaseAPI {

    /**
     * Creates request options for createRestore without sending the request
     */
    async createRestoreRequestOpts(requestParameters: TapeApiCreateRestoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tapeCreateRestoreRequest'] == null) {
            throw new runtime.RequiredError(
                'tapeCreateRestoreRequest',
                'Required parameter "tapeCreateRestoreRequest" was null or undefined when calling createRestore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/tape/restore`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TapeCreateRestoreRequestToJSON(requestParameters['tapeCreateRestoreRequest']),
        };
    }

    /**
     * Restore data from media-set. Namespaces will be automatically created if necessary.  Permissions: The user needs Tape.Read privilege on /tape/pool/{pool} and /tape/drive/{drive}, Datastore.Backup privilege on /datastore/{store}/[{namespace}], Datastore.Modify privileges to create namespaces (if they don\'t exist).
     * Restore data from media-set
     */
    async createRestoreRaw(requestParameters: TapeApiCreateRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TapeCreateRestoreResponse>> {
        const requestOptions = await this.createRestoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TapeCreateRestoreResponseFromJSON(jsonValue));
    }

    /**
     * Restore data from media-set. Namespaces will be automatically created if necessary.  Permissions: The user needs Tape.Read privilege on /tape/pool/{pool} and /tape/drive/{drive}, Datastore.Backup privilege on /datastore/{store}/[{namespace}], Datastore.Modify privileges to create namespaces (if they don\'t exist).
     * Restore data from media-set
     */
    async createRestore(requestParameters: TapeApiCreateRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TapeCreateRestoreResponse> {
        const response = await this.createRestoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getScanChangers without sending the request
     */
    async getScanChangersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/tape/scan-changers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Scan for SCSI tape changers
     * Scan for SCSI tape changers
     */
    async getScanChangersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TapeGetScanChangersResponse>> {
        const requestOptions = await this.getScanChangersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TapeGetScanChangersResponseFromJSON(jsonValue));
    }

    /**
     * Scan for SCSI tape changers
     * Scan for SCSI tape changers
     */
    async getScanChangers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TapeGetScanChangersResponse> {
        const response = await this.getScanChangersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getScanDrives without sending the request
     */
    async getScanDrivesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/tape/scan-drives`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Scan tape drives
     * Scan tape drives
     */
    async getScanDrivesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TapeGetScanDrivesResponse>> {
        const requestOptions = await this.getScanDrivesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TapeGetScanDrivesResponseFromJSON(jsonValue));
    }

    /**
     * Scan tape drives
     * Scan tape drives
     */
    async getScanDrives(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TapeGetScanDrivesResponse> {
        const response = await this.getScanDrivesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTape without sending the request
     */
    async getTapeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PBSApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/tape`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Directory index.
     * Directory index
     */
    async getTapeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TapeGetTapeResponse>> {
        const requestOptions = await this.getTapeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TapeGetTapeResponseFromJSON(jsonValue));
    }

    /**
     * Directory index.
     * Directory index
     */
    async getTape(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TapeGetTapeResponse> {
        const response = await this.getTapeRaw(initOverrides);
        return await response.value();
    }

}
