/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsRoleidEnum } from './PbsRoleidEnum';
import {
    PbsRoleidEnumFromJSON,
    PbsRoleidEnumFromJSONTyped,
    PbsRoleidEnumToJSON,
    PbsRoleidEnumToJSONTyped,
} from './PbsRoleidEnum';

/**
 * 
 * @export
 * @interface AccessAclUpdateAclRequest
 */
export interface AccessAclUpdateAclRequest {

    /**
     * Authentication ID
     * @type {string}
     * @memberof AccessAclUpdateAclRequest
     */
    authId?: string;

    /**
     * Remove permissions (instead of adding it).
     * @type {boolean}
     * @memberof AccessAclUpdateAclRequest
     */
    _delete?: boolean;

    /**
     * Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof AccessAclUpdateAclRequest
     */
    digest?: string;

    /**
     * Group ID
     * @type {string}
     * @memberof AccessAclUpdateAclRequest
     */
    group?: string;

    /**
     * Access control path.
     * @type {string}
     * @memberof AccessAclUpdateAclRequest
     */
    path: string;

    /**
     * Allow to propagate (inherit) permissions.
     * @type {boolean}
     * @memberof AccessAclUpdateAclRequest
     */
    propagate?: boolean;

    /**
     * Enum representing roles via their [PRIVILEGES] combination.
     * 
     * Since privileges are implemented as bitflags, each unique combination of privileges maps to a
     * single, unique `u64` value that is used in this enum definition.
     * @type {PbsRoleidEnum}
     * @memberof AccessAclUpdateAclRequest
     */
    role: PbsRoleidEnum;

}



/**
 * Check if a given object implements the AccessAclUpdateAclRequest interface.
 */
export function instanceOfAccessAclUpdateAclRequest(value: object): value is AccessAclUpdateAclRequest {
    
    
    
    
    
    if (!('path' in value) || value['path'] === undefined) return false;
    
    
    if (!('role' in value) || value['role'] === undefined) return false;
    
    return true;
}

export function AccessAclUpdateAclRequestFromJSON(json: any): AccessAclUpdateAclRequest {
    return AccessAclUpdateAclRequestFromJSONTyped(json, false);
}

export function AccessAclUpdateAclRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessAclUpdateAclRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'authId': json['auth-id'] == null ? undefined : json['auth-id'],
        
        '_delete': json['delete'] == null ? undefined : json['delete'],
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'group': json['group'] == null ? undefined : json['group'],
        
        'path': json['path'],
        
        'propagate': json['propagate'] == null ? undefined : json['propagate'],
        
        'role': PbsRoleidEnumFromJSON(json['role']),
        
    };
}

export function AccessAclUpdateAclRequestToJSON(json: any): AccessAclUpdateAclRequest {
    return AccessAclUpdateAclRequestToJSONTyped(json, false);
}

export function AccessAclUpdateAclRequestToJSONTyped(value?: AccessAclUpdateAclRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'auth-id': value['authId'],
        
        'delete': value['_delete'],
        
        'digest': value['digest'],
        
        'group': value['group'],
        
        'path': value['path'],
        
        'propagate': value['propagate'],
        
        'role': PbsRoleidEnumToJSON(value['role']),
        
    };
}

