/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessUsersGetUsersResponseDataInnerTokensInner } from './AccessUsersGetUsersResponseDataInnerTokensInner';
import {
    AccessUsersGetUsersResponseDataInnerTokensInnerFromJSON,
    AccessUsersGetUsersResponseDataInnerTokensInnerFromJSONTyped,
    AccessUsersGetUsersResponseDataInnerTokensInnerToJSON,
    AccessUsersGetUsersResponseDataInnerTokensInnerToJSONTyped,
} from './AccessUsersGetUsersResponseDataInnerTokensInner';

/**
 * 
 * @export
 * @interface AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse
 */
export interface AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse {

    /**
     * 
     * @type {AccessUsersGetUsersResponseDataInnerTokensInner}
     * @memberof AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse
     */
    data: AccessUsersGetUsersResponseDataInnerTokensInner;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse interface.
 */
export function instanceOfAccessUsersGetAccessUsersByUseridTokenByTokenNameResponse(value: object): value is AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function AccessUsersGetAccessUsersByUseridTokenByTokenNameResponseFromJSON(json: any): AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse {
    return AccessUsersGetAccessUsersByUseridTokenByTokenNameResponseFromJSONTyped(json, false);
}

export function AccessUsersGetAccessUsersByUseridTokenByTokenNameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': AccessUsersGetUsersResponseDataInnerTokensInnerFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function AccessUsersGetAccessUsersByUseridTokenByTokenNameResponseToJSON(json: any): AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse {
    return AccessUsersGetAccessUsersByUseridTokenByTokenNameResponseToJSONTyped(json, false);
}

export function AccessUsersGetAccessUsersByUseridTokenByTokenNameResponseToJSONTyped(value?: AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': AccessUsersGetUsersResponseDataInnerTokensInnerToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

