/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessTfaUpdateTfaRequest
 */
export interface AccessTfaUpdateTfaRequest {

    /**
     * A description to distinguish multiple entries from one another
     * @type {string}
     * @memberof AccessTfaUpdateTfaRequest
     */
    description?: string;

    /**
     * Whether this entry should currently be enabled or disabled
     * @type {boolean}
     * @memberof AccessTfaUpdateTfaRequest
     */
    enable?: boolean;

    /**
     * Password.
     * @type {string}
     * @memberof AccessTfaUpdateTfaRequest
     */
    password?: string;

}

/**
 * Check if a given object implements the AccessTfaUpdateTfaRequest interface.
 */
export function instanceOfAccessTfaUpdateTfaRequest(value: object): value is AccessTfaUpdateTfaRequest {
    
    
    
    
    return true;
}

export function AccessTfaUpdateTfaRequestFromJSON(json: any): AccessTfaUpdateTfaRequest {
    return AccessTfaUpdateTfaRequestFromJSONTyped(json, false);
}

export function AccessTfaUpdateTfaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessTfaUpdateTfaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'description': json['description'] == null ? undefined : json['description'],
        
        'enable': json['enable'] == null ? undefined : json['enable'],
        
        'password': json['password'] == null ? undefined : json['password'],
        
    };
}

export function AccessTfaUpdateTfaRequestToJSON(json: any): AccessTfaUpdateTfaRequest {
    return AccessTfaUpdateTfaRequestToJSONTyped(json, false);
}

export function AccessTfaUpdateTfaRequestToJSONTyped(value?: AccessTfaUpdateTfaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'description': value['description'],
        
        'enable': value['enable'],
        
        'password': value['password'],
        
    };
}

