/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsAccessTfaTypeEnum } from './PbsAccessTfaTypeEnum';
import {
    PbsAccessTfaTypeEnumFromJSON,
    PbsAccessTfaTypeEnumFromJSONTyped,
    PbsAccessTfaTypeEnumToJSON,
    PbsAccessTfaTypeEnumToJSONTyped,
} from './PbsAccessTfaTypeEnum';

/**
 * 
 * @export
 * @interface AccessTfaGetTfaResponseDataInnerEntriesInner
 */
export interface AccessTfaGetTfaResponseDataInnerEntriesInner {

    /**
     * Creation time of this entry as unix epoch.
     * @type {number}
     * @memberof AccessTfaGetTfaResponseDataInnerEntriesInner
     */
    created: number;

    /**
     * User chosen description for this entry.
     * @type {string}
     * @memberof AccessTfaGetTfaResponseDataInnerEntriesInner
     */
    description: string;

    /**
     * Whether this TFA entry is currently enabled.
     * @type {boolean}
     * @memberof AccessTfaGetTfaResponseDataInnerEntriesInner
     */
    enable: boolean;

    /**
     * The id used to reference this entry.
     * @type {string}
     * @memberof AccessTfaGetTfaResponseDataInnerEntriesInner
     */
    id: string;

    /**
     * A TFA entry type.
     * @type {PbsAccessTfaTypeEnum}
     * @memberof AccessTfaGetTfaResponseDataInnerEntriesInner
     */
    type: PbsAccessTfaTypeEnum;

}



/**
 * Check if a given object implements the AccessTfaGetTfaResponseDataInnerEntriesInner interface.
 */
export function instanceOfAccessTfaGetTfaResponseDataInnerEntriesInner(value: object): value is AccessTfaGetTfaResponseDataInnerEntriesInner {
    
    if (!('created' in value) || value['created'] === undefined) return false;
    
    if (!('description' in value) || value['description'] === undefined) return false;
    
    if (!('enable' in value) || value['enable'] === undefined) return false;
    
    if (!('id' in value) || value['id'] === undefined) return false;
    
    if (!('type' in value) || value['type'] === undefined) return false;
    
    return true;
}

export function AccessTfaGetTfaResponseDataInnerEntriesInnerFromJSON(json: any): AccessTfaGetTfaResponseDataInnerEntriesInner {
    return AccessTfaGetTfaResponseDataInnerEntriesInnerFromJSONTyped(json, false);
}

export function AccessTfaGetTfaResponseDataInnerEntriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessTfaGetTfaResponseDataInnerEntriesInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'created': json['created'],
        
        'description': json['description'],
        
        'enable': json['enable'],
        
        'id': json['id'],
        
        'type': PbsAccessTfaTypeEnumFromJSON(json['type']),
        
    };
}

export function AccessTfaGetTfaResponseDataInnerEntriesInnerToJSON(json: any): AccessTfaGetTfaResponseDataInnerEntriesInner {
    return AccessTfaGetTfaResponseDataInnerEntriesInnerToJSONTyped(json, false);
}

export function AccessTfaGetTfaResponseDataInnerEntriesInnerToJSONTyped(value?: AccessTfaGetTfaResponseDataInnerEntriesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'created': value['created'],
        
        'description': value['description'],
        
        'enable': value['enable'],
        
        'id': value['id'],
        
        'type': PbsAccessTfaTypeEnumToJSON(value['type']),
        
    };
}

