/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminDatastoreDeleteGroupsResponseData } from './AdminDatastoreDeleteGroupsResponseData';
import {
    AdminDatastoreDeleteGroupsResponseDataFromJSON,
    AdminDatastoreDeleteGroupsResponseDataFromJSONTyped,
    AdminDatastoreDeleteGroupsResponseDataToJSON,
    AdminDatastoreDeleteGroupsResponseDataToJSONTyped,
} from './AdminDatastoreDeleteGroupsResponseData';

/**
 * 
 * @export
 * @interface AdminDatastoreDeleteGroupsResponse
 */
export interface AdminDatastoreDeleteGroupsResponse {

    /**
     * 
     * @type {AdminDatastoreDeleteGroupsResponseData}
     * @memberof AdminDatastoreDeleteGroupsResponse
     */
    data: AdminDatastoreDeleteGroupsResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof AdminDatastoreDeleteGroupsResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof AdminDatastoreDeleteGroupsResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the AdminDatastoreDeleteGroupsResponse interface.
 */
export function instanceOfAdminDatastoreDeleteGroupsResponse(value: object): value is AdminDatastoreDeleteGroupsResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function AdminDatastoreDeleteGroupsResponseFromJSON(json: any): AdminDatastoreDeleteGroupsResponse {
    return AdminDatastoreDeleteGroupsResponseFromJSONTyped(json, false);
}

export function AdminDatastoreDeleteGroupsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDatastoreDeleteGroupsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': AdminDatastoreDeleteGroupsResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function AdminDatastoreDeleteGroupsResponseToJSON(json: any): AdminDatastoreDeleteGroupsResponse {
    return AdminDatastoreDeleteGroupsResponseToJSONTyped(json, false);
}

export function AdminDatastoreDeleteGroupsResponseToJSONTyped(value?: AdminDatastoreDeleteGroupsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': AdminDatastoreDeleteGroupsResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

