/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminPruneGetAdminPruneByIdResponse
 */
export interface AdminPruneGetAdminPruneByIdResponse {

    /**
     * 
     * @type {any}
     * @memberof AdminPruneGetAdminPruneByIdResponse
     */
    data: any | null;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof AdminPruneGetAdminPruneByIdResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof AdminPruneGetAdminPruneByIdResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the AdminPruneGetAdminPruneByIdResponse interface.
 */
export function instanceOfAdminPruneGetAdminPruneByIdResponse(value: object): value is AdminPruneGetAdminPruneByIdResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function AdminPruneGetAdminPruneByIdResponseFromJSON(json: any): AdminPruneGetAdminPruneByIdResponse {
    return AdminPruneGetAdminPruneByIdResponseFromJSONTyped(json, false);
}

export function AdminPruneGetAdminPruneByIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminPruneGetAdminPruneByIdResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function AdminPruneGetAdminPruneByIdResponseToJSON(json: any): AdminPruneGetAdminPruneByIdResponse {
    return AdminPruneGetAdminPruneByIdResponseToJSONTyped(json, false);
}

export function AdminPruneGetAdminPruneByIdResponseToJSONTyped(value?: AdminPruneGetAdminPruneByIdResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

