/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsBackupTypeEnum } from './PbsBackupTypeEnum';
import {
    PbsBackupTypeEnumFromJSON,
    PbsBackupTypeEnumFromJSONTyped,
    PbsBackupTypeEnumToJSON,
    PbsBackupTypeEnumToJSONTyped,
} from './PbsBackupTypeEnum';

/**
 * 
 * @export
 * @interface AdminDatastoreUpdateProtectedRequest
 */
export interface AdminDatastoreUpdateProtectedRequest {

    /**
     * Backup ID.
     * @type {string}
     * @memberof AdminDatastoreUpdateProtectedRequest
     */
    backupId: string;

    /**
     * Backup time (Unix epoch.)
     * @type {number}
     * @memberof AdminDatastoreUpdateProtectedRequest
     */
    backupTime: bigint | string | number;

    /**
     * Backup types.
     * @type {PbsBackupTypeEnum}
     * @memberof AdminDatastoreUpdateProtectedRequest
     */
    backupType: PbsBackupTypeEnum;

    /**
     * Namespace.
     * @type {string}
     * @memberof AdminDatastoreUpdateProtectedRequest
     */
    ns?: string;

    /**
     * Enable/disable protection.
     * @type {boolean}
     * @memberof AdminDatastoreUpdateProtectedRequest
     */
    _protected: boolean;

}



/**
 * Check if a given object implements the AdminDatastoreUpdateProtectedRequest interface.
 */
export function instanceOfAdminDatastoreUpdateProtectedRequest(value: object): value is AdminDatastoreUpdateProtectedRequest {
    
    if (!('backupId' in value) || value['backupId'] === undefined) return false;
    
    if (!('backupTime' in value) || value['backupTime'] === undefined) return false;
    
    if (!('backupType' in value) || value['backupType'] === undefined) return false;
    
    
    if (!('_protected' in value) || value['_protected'] === undefined) return false;
    
    return true;
}

export function AdminDatastoreUpdateProtectedRequestFromJSON(json: any): AdminDatastoreUpdateProtectedRequest {
    return AdminDatastoreUpdateProtectedRequestFromJSONTyped(json, false);
}

export function AdminDatastoreUpdateProtectedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDatastoreUpdateProtectedRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'backupId': json['backup-id'],
        
        'backupTime': BigInt(json['backup-time']),
        
        'backupType': PbsBackupTypeEnumFromJSON(json['backup-type']),
        
        'ns': json['ns'] == null ? undefined : json['ns'],
        
        '_protected': json['protected'],
        
    };
}

export function AdminDatastoreUpdateProtectedRequestToJSON(json: any): AdminDatastoreUpdateProtectedRequest {
    return AdminDatastoreUpdateProtectedRequestToJSONTyped(json, false);
}

export function AdminDatastoreUpdateProtectedRequestToJSONTyped(value?: AdminDatastoreUpdateProtectedRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'backup-id': value['backupId'],
        
        'backup-time': String(value['backupTime']),
        
        'backup-type': PbsBackupTypeEnumToJSON(value['backupType']),
        
        'ns': value['ns'],
        
        'protected': value['_protected'],
        
    };
}

