/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminDatastoreCreatePruneResponseDataInner } from './AdminDatastoreCreatePruneResponseDataInner';
import {
    AdminDatastoreCreatePruneResponseDataInnerFromJSON,
    AdminDatastoreCreatePruneResponseDataInnerFromJSONTyped,
    AdminDatastoreCreatePruneResponseDataInnerToJSON,
    AdminDatastoreCreatePruneResponseDataInnerToJSONTyped,
} from './AdminDatastoreCreatePruneResponseDataInner';

/**
 * 
 * @export
 * @interface AdminDatastoreCreatePruneResponse
 */
export interface AdminDatastoreCreatePruneResponse {

    /**
     * 
     * @type {Array<AdminDatastoreCreatePruneResponseDataInner>}
     * @memberof AdminDatastoreCreatePruneResponse
     */
    data: Array<AdminDatastoreCreatePruneResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof AdminDatastoreCreatePruneResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof AdminDatastoreCreatePruneResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the AdminDatastoreCreatePruneResponse interface.
 */
export function instanceOfAdminDatastoreCreatePruneResponse(value: object): value is AdminDatastoreCreatePruneResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function AdminDatastoreCreatePruneResponseFromJSON(json: any): AdminDatastoreCreatePruneResponse {
    return AdminDatastoreCreatePruneResponseFromJSONTyped(json, false);
}

export function AdminDatastoreCreatePruneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDatastoreCreatePruneResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(AdminDatastoreCreatePruneResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function AdminDatastoreCreatePruneResponseToJSON(json: any): AdminDatastoreCreatePruneResponse {
    return AdminDatastoreCreatePruneResponseToJSONTyped(json, false);
}

export function AdminDatastoreCreatePruneResponseToJSONTyped(value?: AdminDatastoreCreatePruneResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(AdminDatastoreCreatePruneResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

