/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsBackupTypeEnum } from './PbsBackupTypeEnum';
import {
    PbsBackupTypeEnumFromJSON,
    PbsBackupTypeEnumFromJSONTyped,
    PbsBackupTypeEnumToJSON,
    PbsBackupTypeEnumToJSONTyped,
} from './PbsBackupTypeEnum';

/**
 * 
 * @export
 * @interface AdminDatastoreCreatePruneRequest
 */
export interface AdminDatastoreCreatePruneRequest {

    /**
     * Backup ID.
     * @type {string}
     * @memberof AdminDatastoreCreatePruneRequest
     */
    backupId: string;

    /**
     * Backup types.
     * @type {PbsBackupTypeEnum}
     * @memberof AdminDatastoreCreatePruneRequest
     */
    backupType: PbsBackupTypeEnum;

    /**
     * Just show what prune would do, but do not delete anything.
     * @type {boolean}
     * @memberof AdminDatastoreCreatePruneRequest
     */
    dryRun?: boolean;

    /**
     * Number of daily backups to keep.
     * @type {number}
     * @memberof AdminDatastoreCreatePruneRequest
     */
    keepDaily?: bigint | string | number;

    /**
     * Number of hourly backups to keep.
     * @type {number}
     * @memberof AdminDatastoreCreatePruneRequest
     */
    keepHourly?: bigint | string | number;

    /**
     * Number of backups to keep.
     * @type {number}
     * @memberof AdminDatastoreCreatePruneRequest
     */
    keepLast?: bigint | string | number;

    /**
     * Number of monthly backups to keep.
     * @type {number}
     * @memberof AdminDatastoreCreatePruneRequest
     */
    keepMonthly?: bigint | string | number;

    /**
     * Number of weekly backups to keep.
     * @type {number}
     * @memberof AdminDatastoreCreatePruneRequest
     */
    keepWeekly?: bigint | string | number;

    /**
     * Number of yearly backups to keep.
     * @type {number}
     * @memberof AdminDatastoreCreatePruneRequest
     */
    keepYearly?: bigint | string | number;

    /**
     * Namespace.
     * @type {string}
     * @memberof AdminDatastoreCreatePruneRequest
     */
    ns?: string;

    /**
     * Spins up an asynchronous task that does the work.
     * @type {boolean}
     * @memberof AdminDatastoreCreatePruneRequest
     */
    useTask?: boolean;

}



/**
 * Check if a given object implements the AdminDatastoreCreatePruneRequest interface.
 */
export function instanceOfAdminDatastoreCreatePruneRequest(value: object): value is AdminDatastoreCreatePruneRequest {
    
    if (!('backupId' in value) || value['backupId'] === undefined) return false;
    
    if (!('backupType' in value) || value['backupType'] === undefined) return false;
    
    
    
    
    
    
    
    
    
    
    return true;
}

export function AdminDatastoreCreatePruneRequestFromJSON(json: any): AdminDatastoreCreatePruneRequest {
    return AdminDatastoreCreatePruneRequestFromJSONTyped(json, false);
}

export function AdminDatastoreCreatePruneRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDatastoreCreatePruneRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'backupId': json['backup-id'],
        
        'backupType': PbsBackupTypeEnumFromJSON(json['backup-type']),
        
        'dryRun': json['dry-run'] == null ? undefined : json['dry-run'],
        
        'keepDaily': json['keep-daily'] == null ? undefined : BigInt(json['keep-daily']),
        
        'keepHourly': json['keep-hourly'] == null ? undefined : BigInt(json['keep-hourly']),
        
        'keepLast': json['keep-last'] == null ? undefined : BigInt(json['keep-last']),
        
        'keepMonthly': json['keep-monthly'] == null ? undefined : BigInt(json['keep-monthly']),
        
        'keepWeekly': json['keep-weekly'] == null ? undefined : BigInt(json['keep-weekly']),
        
        'keepYearly': json['keep-yearly'] == null ? undefined : BigInt(json['keep-yearly']),
        
        'ns': json['ns'] == null ? undefined : json['ns'],
        
        'useTask': json['use-task'] == null ? undefined : json['use-task'],
        
    };
}

export function AdminDatastoreCreatePruneRequestToJSON(json: any): AdminDatastoreCreatePruneRequest {
    return AdminDatastoreCreatePruneRequestToJSONTyped(json, false);
}

export function AdminDatastoreCreatePruneRequestToJSONTyped(value?: AdminDatastoreCreatePruneRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'backup-id': value['backupId'],
        
        'backup-type': PbsBackupTypeEnumToJSON(value['backupType']),
        
        'dry-run': value['dryRun'],
        
        'keep-daily': value['keepDaily'] == null ? undefined : String(value['keepDaily']),
        
        'keep-hourly': value['keepHourly'] == null ? undefined : String(value['keepHourly']),
        
        'keep-last': value['keepLast'] == null ? undefined : String(value['keepLast']),
        
        'keep-monthly': value['keepMonthly'] == null ? undefined : String(value['keepMonthly']),
        
        'keep-weekly': value['keepWeekly'] == null ? undefined : String(value['keepWeekly']),
        
        'keep-yearly': value['keepYearly'] == null ? undefined : String(value['keepYearly']),
        
        'ns': value['ns'],
        
        'use-task': value['useTask'],
        
    };
}

