/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminDatastoreGetGcResponseDataCacheStats } from './AdminDatastoreGetGcResponseDataCacheStats';
import {
    AdminDatastoreGetGcResponseDataCacheStatsFromJSON,
    AdminDatastoreGetGcResponseDataCacheStatsFromJSONTyped,
    AdminDatastoreGetGcResponseDataCacheStatsToJSON,
    AdminDatastoreGetGcResponseDataCacheStatsToJSONTyped,
} from './AdminDatastoreGetGcResponseDataCacheStats';

/**
 * 
 * @export
 * @interface AdminDatastoreGetGcResponseData
 */
export interface AdminDatastoreGetGcResponseData {

    /**
     * 
     * @type {AdminDatastoreGetGcResponseDataCacheStats}
     * @memberof AdminDatastoreGetGcResponseData
     */
    cacheStats?: AdminDatastoreGetGcResponseDataCacheStats;

    /**
     * Bytes used on disk.
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    diskBytes: bigint | string | number;

    /**
     * Chunks used on disk.
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    diskChunks: bigint | string | number;

    /**
     * Duration of last gc run
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    duration?: bigint | string | number;

    /**
     * Sum of bytes referred by index files.
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    indexDataBytes: bigint | string | number;

    /**
     * Number of processed index files.
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    indexFileCount: bigint | string | number;

    /**
     * Endtime of the last gc run
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    lastRunEndtime?: bigint | string | number;

    /**
     * State of the last gc run
     * @type {string}
     * @memberof AdminDatastoreGetGcResponseData
     */
    lastRunState?: string;

    /**
     * Time of the next gc run
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    nextRun?: bigint | string | number;

    /**
     * Sum of pending bytes (pending removal - kept for safety).
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    pendingBytes: bigint | string | number;

    /**
     * Number of pending chunks (pending removal - kept for safety).
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    pendingChunks: bigint | string | number;

    /**
     * Number of chunks marked as .bad by verify that have been removed by GC.
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    removedBad: bigint | string | number;

    /**
     * Sum of removed bytes.
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    removedBytes: bigint | string | number;

    /**
     * Number of removed chunks.
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    removedChunks: bigint | string | number;

    /**
     * Schedule of the gc job
     * @type {string}
     * @memberof AdminDatastoreGetGcResponseData
     */
    schedule?: string;

    /**
     * Number of chunks still marked as .bad after garbage collection.
     * @type {number}
     * @memberof AdminDatastoreGetGcResponseData
     */
    stillBad: bigint | string | number;

    /**
     * Datastore
     * @type {string}
     * @memberof AdminDatastoreGetGcResponseData
     */
    store: string;

    /**
     * Unique Process/Task Identifier
     * @type {string}
     * @memberof AdminDatastoreGetGcResponseData
     */
    upid?: string;

}

/**
 * Check if a given object implements the AdminDatastoreGetGcResponseData interface.
 */
export function instanceOfAdminDatastoreGetGcResponseData(value: object): value is AdminDatastoreGetGcResponseData {
    
    
    if (!('diskBytes' in value) || value['diskBytes'] === undefined) return false;
    
    if (!('diskChunks' in value) || value['diskChunks'] === undefined) return false;
    
    
    if (!('indexDataBytes' in value) || value['indexDataBytes'] === undefined) return false;
    
    if (!('indexFileCount' in value) || value['indexFileCount'] === undefined) return false;
    
    
    
    
    if (!('pendingBytes' in value) || value['pendingBytes'] === undefined) return false;
    
    if (!('pendingChunks' in value) || value['pendingChunks'] === undefined) return false;
    
    if (!('removedBad' in value) || value['removedBad'] === undefined) return false;
    
    if (!('removedBytes' in value) || value['removedBytes'] === undefined) return false;
    
    if (!('removedChunks' in value) || value['removedChunks'] === undefined) return false;
    
    
    if (!('stillBad' in value) || value['stillBad'] === undefined) return false;
    
    if (!('store' in value) || value['store'] === undefined) return false;
    
    
    return true;
}

export function AdminDatastoreGetGcResponseDataFromJSON(json: any): AdminDatastoreGetGcResponseData {
    return AdminDatastoreGetGcResponseDataFromJSONTyped(json, false);
}

export function AdminDatastoreGetGcResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDatastoreGetGcResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'cacheStats': json['cache-stats'] == null ? undefined : AdminDatastoreGetGcResponseDataCacheStatsFromJSON(json['cache-stats']),
        
        'diskBytes': BigInt(json['disk-bytes']),
        
        'diskChunks': BigInt(json['disk-chunks']),
        
        'duration': json['duration'] == null ? undefined : BigInt(json['duration']),
        
        'indexDataBytes': BigInt(json['index-data-bytes']),
        
        'indexFileCount': BigInt(json['index-file-count']),
        
        'lastRunEndtime': json['last-run-endtime'] == null ? undefined : BigInt(json['last-run-endtime']),
        
        'lastRunState': json['last-run-state'] == null ? undefined : json['last-run-state'],
        
        'nextRun': json['next-run'] == null ? undefined : BigInt(json['next-run']),
        
        'pendingBytes': BigInt(json['pending-bytes']),
        
        'pendingChunks': BigInt(json['pending-chunks']),
        
        'removedBad': BigInt(json['removed-bad']),
        
        'removedBytes': BigInt(json['removed-bytes']),
        
        'removedChunks': BigInt(json['removed-chunks']),
        
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        
        'stillBad': BigInt(json['still-bad']),
        
        'store': json['store'],
        
        'upid': json['upid'] == null ? undefined : json['upid'],
        
    };
}

export function AdminDatastoreGetGcResponseDataToJSON(json: any): AdminDatastoreGetGcResponseData {
    return AdminDatastoreGetGcResponseDataToJSONTyped(json, false);
}

export function AdminDatastoreGetGcResponseDataToJSONTyped(value?: AdminDatastoreGetGcResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'cache-stats': AdminDatastoreGetGcResponseDataCacheStatsToJSON(value['cacheStats']),
        
        'disk-bytes': String(value['diskBytes']),
        
        'disk-chunks': String(value['diskChunks']),
        
        'duration': value['duration'] == null ? undefined : String(value['duration']),
        
        'index-data-bytes': String(value['indexDataBytes']),
        
        'index-file-count': String(value['indexFileCount']),
        
        'last-run-endtime': value['lastRunEndtime'] == null ? undefined : String(value['lastRunEndtime']),
        
        'last-run-state': value['lastRunState'],
        
        'next-run': value['nextRun'] == null ? undefined : String(value['nextRun']),
        
        'pending-bytes': String(value['pendingBytes']),
        
        'pending-chunks': String(value['pendingChunks']),
        
        'removed-bad': String(value['removedBad']),
        
        'removed-bytes': String(value['removedBytes']),
        
        'removed-chunks': String(value['removedChunks']),
        
        'schedule': value['schedule'],
        
        'still-bad': String(value['stillBad']),
        
        'store': value['store'],
        
        'upid': value['upid'],
        
    };
}

