/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminDatastoreCreateGcResponse
 */
export interface AdminDatastoreCreateGcResponse {

    /**
     * 
     * @type {string}
     * @memberof AdminDatastoreCreateGcResponse
     */
    data: string;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof AdminDatastoreCreateGcResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof AdminDatastoreCreateGcResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the AdminDatastoreCreateGcResponse interface.
 */
export function instanceOfAdminDatastoreCreateGcResponse(value: object): value is AdminDatastoreCreateGcResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function AdminDatastoreCreateGcResponseFromJSON(json: any): AdminDatastoreCreateGcResponse {
    return AdminDatastoreCreateGcResponseFromJSONTyped(json, false);
}

export function AdminDatastoreCreateGcResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDatastoreCreateGcResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function AdminDatastoreCreateGcResponseToJSON(json: any): AdminDatastoreCreateGcResponse {
    return AdminDatastoreCreateGcResponseToJSONTyped(json, false);
}

export function AdminDatastoreCreateGcResponseToJSONTyped(value?: AdminDatastoreCreateGcResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

