/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminDatastoreGetDatastoreResponseDataInner } from './AdminDatastoreGetDatastoreResponseDataInner';
import {
    AdminDatastoreGetDatastoreResponseDataInnerFromJSON,
    AdminDatastoreGetDatastoreResponseDataInnerFromJSONTyped,
    AdminDatastoreGetDatastoreResponseDataInnerToJSON,
    AdminDatastoreGetDatastoreResponseDataInnerToJSONTyped,
} from './AdminDatastoreGetDatastoreResponseDataInner';

/**
 * 
 * @export
 * @interface AdminDatastoreGetDatastoreResponse
 */
export interface AdminDatastoreGetDatastoreResponse {

    /**
     * 
     * @type {Array<AdminDatastoreGetDatastoreResponseDataInner>}
     * @memberof AdminDatastoreGetDatastoreResponse
     */
    data: Array<AdminDatastoreGetDatastoreResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof AdminDatastoreGetDatastoreResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof AdminDatastoreGetDatastoreResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the AdminDatastoreGetDatastoreResponse interface.
 */
export function instanceOfAdminDatastoreGetDatastoreResponse(value: object): value is AdminDatastoreGetDatastoreResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function AdminDatastoreGetDatastoreResponseFromJSON(json: any): AdminDatastoreGetDatastoreResponse {
    return AdminDatastoreGetDatastoreResponseFromJSONTyped(json, false);
}

export function AdminDatastoreGetDatastoreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDatastoreGetDatastoreResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(AdminDatastoreGetDatastoreResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function AdminDatastoreGetDatastoreResponseToJSON(json: any): AdminDatastoreGetDatastoreResponse {
    return AdminDatastoreGetDatastoreResponseToJSONTyped(json, false);
}

export function AdminDatastoreGetDatastoreResponseToJSONTyped(value?: AdminDatastoreGetDatastoreResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(AdminDatastoreGetDatastoreResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

