/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsAdminDatastoreCryptModeEnum } from './PbsAdminDatastoreCryptModeEnum';
import {
    PbsAdminDatastoreCryptModeEnumFromJSON,
    PbsAdminDatastoreCryptModeEnumFromJSONTyped,
    PbsAdminDatastoreCryptModeEnumToJSON,
    PbsAdminDatastoreCryptModeEnumToJSONTyped,
} from './PbsAdminDatastoreCryptModeEnum';

/**
 * 
 * @export
 * @interface AdminDatastoreGetFilesResponseDataInner
 */
export interface AdminDatastoreGetFilesResponseDataInner {

    /**
     * Defines whether data is encrypted (using an AEAD cipher), only signed, or neither.
     * @type {PbsAdminDatastoreCryptModeEnum}
     * @memberof AdminDatastoreGetFilesResponseDataInner
     */
    cryptMode?: PbsAdminDatastoreCryptModeEnum;

    /**
     * Backup archive name.
     * @type {string}
     * @memberof AdminDatastoreGetFilesResponseDataInner
     */
    filename: string;

    /**
     * Archive size (from backup manifest).
     * @type {number}
     * @memberof AdminDatastoreGetFilesResponseDataInner
     */
    size?: bigint | string | number;

}



/**
 * Check if a given object implements the AdminDatastoreGetFilesResponseDataInner interface.
 */
export function instanceOfAdminDatastoreGetFilesResponseDataInner(value: object): value is AdminDatastoreGetFilesResponseDataInner {
    
    
    if (!('filename' in value) || value['filename'] === undefined) return false;
    
    
    return true;
}

export function AdminDatastoreGetFilesResponseDataInnerFromJSON(json: any): AdminDatastoreGetFilesResponseDataInner {
    return AdminDatastoreGetFilesResponseDataInnerFromJSONTyped(json, false);
}

export function AdminDatastoreGetFilesResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDatastoreGetFilesResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'cryptMode': json['crypt-mode'] == null ? undefined : PbsAdminDatastoreCryptModeEnumFromJSON(json['crypt-mode']),
        
        'filename': json['filename'],
        
        'size': json['size'] == null ? undefined : BigInt(json['size']),
        
    };
}

export function AdminDatastoreGetFilesResponseDataInnerToJSON(json: any): AdminDatastoreGetFilesResponseDataInner {
    return AdminDatastoreGetFilesResponseDataInnerToJSONTyped(json, false);
}

export function AdminDatastoreGetFilesResponseDataInnerToJSONTyped(value?: AdminDatastoreGetFilesResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'crypt-mode': PbsAdminDatastoreCryptModeEnumToJSON(value['cryptMode']),
        
        'filename': value['filename'],
        
        'size': value['size'] == null ? undefined : String(value['size']),
        
    };
}

