/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminDatastoreCreateMoveNamespaceRequest
 */
export interface AdminDatastoreCreateMoveNamespaceRequest {

    /**
     * Remove the source namespace after moving all contents. Defaults to true.
     * @type {boolean}
     * @memberof AdminDatastoreCreateMoveNamespaceRequest
     */
    deleteSource?: boolean;

    /**
     * How many levels of namespaces should be operated on (0 == no recursion)
     * @type {number}
     * @memberof AdminDatastoreCreateMoveNamespaceRequest
     */
    maxDepth?: number;

    /**
     * If a group with the same name already exists in the target namespace, merge snapshots into it. Requires matching ownership and non-overlapping snapshot times.
     * @type {boolean}
     * @memberof AdminDatastoreCreateMoveNamespaceRequest
     */
    mergeGroups?: boolean;

    /**
     * Namespace.
     * @type {string}
     * @memberof AdminDatastoreCreateMoveNamespaceRequest
     */
    ns: string;

    /**
     * Namespace.
     * @type {string}
     * @memberof AdminDatastoreCreateMoveNamespaceRequest
     */
    targetNs: string;

}

/**
 * Check if a given object implements the AdminDatastoreCreateMoveNamespaceRequest interface.
 */
export function instanceOfAdminDatastoreCreateMoveNamespaceRequest(value: object): value is AdminDatastoreCreateMoveNamespaceRequest {
    
    
    
    
    if (!('ns' in value) || value['ns'] === undefined) return false;
    
    if (!('targetNs' in value) || value['targetNs'] === undefined) return false;
    
    return true;
}

export function AdminDatastoreCreateMoveNamespaceRequestFromJSON(json: any): AdminDatastoreCreateMoveNamespaceRequest {
    return AdminDatastoreCreateMoveNamespaceRequestFromJSONTyped(json, false);
}

export function AdminDatastoreCreateMoveNamespaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDatastoreCreateMoveNamespaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'deleteSource': json['delete-source'] == null ? undefined : json['delete-source'],
        
        'maxDepth': json['max-depth'] == null ? undefined : json['max-depth'],
        
        'mergeGroups': json['merge-groups'] == null ? undefined : json['merge-groups'],
        
        'ns': json['ns'],
        
        'targetNs': json['target-ns'],
        
    };
}

export function AdminDatastoreCreateMoveNamespaceRequestToJSON(json: any): AdminDatastoreCreateMoveNamespaceRequest {
    return AdminDatastoreCreateMoveNamespaceRequestToJSONTyped(json, false);
}

export function AdminDatastoreCreateMoveNamespaceRequestToJSONTyped(value?: AdminDatastoreCreateMoveNamespaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'delete-source': value['deleteSource'],
        
        'max-depth': value['maxDepth'],
        
        'merge-groups': value['mergeGroups'],
        
        'ns': value['ns'],
        
        'target-ns': value['targetNs'],
        
    };
}

