/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BackupUpgradeGetUpgradeResponse
 */
export interface BackupUpgradeGetUpgradeResponse {

    /**
     * 
     * @type {any}
     * @memberof BackupUpgradeGetUpgradeResponse
     */
    data: any | null;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof BackupUpgradeGetUpgradeResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof BackupUpgradeGetUpgradeResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the BackupUpgradeGetUpgradeResponse interface.
 */
export function instanceOfBackupUpgradeGetUpgradeResponse(value: object): value is BackupUpgradeGetUpgradeResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function BackupUpgradeGetUpgradeResponseFromJSON(json: any): BackupUpgradeGetUpgradeResponse {
    return BackupUpgradeGetUpgradeResponseFromJSONTyped(json, false);
}

export function BackupUpgradeGetUpgradeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupUpgradeGetUpgradeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function BackupUpgradeGetUpgradeResponseToJSON(json: any): BackupUpgradeGetUpgradeResponse {
    return BackupUpgradeGetUpgradeResponseToJSONTyped(json, false);
}

export function BackupUpgradeGetUpgradeResponseToJSONTyped(value?: BackupUpgradeGetUpgradeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

