/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BackupUpgradeUpdateFixedIndexRequest
 */
export interface BackupUpgradeUpdateFixedIndexRequest {

    /**
     * Chunk digest list.
     * @type {Array<string>}
     * @memberof BackupUpgradeUpdateFixedIndexRequest
     */
    digestList: Array<string>;

    /**
     * Chunk offset list.
     * @type {Array<number>}
     * @memberof BackupUpgradeUpdateFixedIndexRequest
     */
    offsetList: Array<number>;

    /**
     * Fixed writer ID.
     * @type {number}
     * @memberof BackupUpgradeUpdateFixedIndexRequest
     */
    wid: number;

}

/**
 * Check if a given object implements the BackupUpgradeUpdateFixedIndexRequest interface.
 */
export function instanceOfBackupUpgradeUpdateFixedIndexRequest(value: object): value is BackupUpgradeUpdateFixedIndexRequest {
    
    if (!('digestList' in value) || value['digestList'] === undefined) return false;
    
    if (!('offsetList' in value) || value['offsetList'] === undefined) return false;
    
    if (!('wid' in value) || value['wid'] === undefined) return false;
    
    return true;
}

export function BackupUpgradeUpdateFixedIndexRequestFromJSON(json: any): BackupUpgradeUpdateFixedIndexRequest {
    return BackupUpgradeUpdateFixedIndexRequestFromJSONTyped(json, false);
}

export function BackupUpgradeUpdateFixedIndexRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupUpgradeUpdateFixedIndexRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'digestList': json['digest-list'],
        
        'offsetList': json['offset-list'],
        
        'wid': json['wid'],
        
    };
}

export function BackupUpgradeUpdateFixedIndexRequestToJSON(json: any): BackupUpgradeUpdateFixedIndexRequest {
    return BackupUpgradeUpdateFixedIndexRequestToJSONTyped(json, false);
}

export function BackupUpgradeUpdateFixedIndexRequestToJSONTyped(value?: BackupUpgradeUpdateFixedIndexRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'digest-list': value['digestList'],
        
        'offset-list': value['offsetList'],
        
        'wid': value['wid'],
        
    };
}

