/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BackupUpgradeCreateDynamicCloseRequest
 */
export interface BackupUpgradeCreateDynamicCloseRequest {

    /**
     * Chunk count. This is used to verify that the server got all chunks.
     * @type {number}
     * @memberof BackupUpgradeCreateDynamicCloseRequest
     */
    chunkCount: number;

    /**
     * Digest list checksum.
     * @type {string}
     * @memberof BackupUpgradeCreateDynamicCloseRequest
     */
    csum: string;

    /**
     * File size. This is used to verify that the server got all data.
     * @type {number}
     * @memberof BackupUpgradeCreateDynamicCloseRequest
     */
    size: number;

    /**
     * Dynamic writer ID.
     * @type {number}
     * @memberof BackupUpgradeCreateDynamicCloseRequest
     */
    wid: number;

}

/**
 * Check if a given object implements the BackupUpgradeCreateDynamicCloseRequest interface.
 */
export function instanceOfBackupUpgradeCreateDynamicCloseRequest(value: object): value is BackupUpgradeCreateDynamicCloseRequest {
    
    if (!('chunkCount' in value) || value['chunkCount'] === undefined) return false;
    
    if (!('csum' in value) || value['csum'] === undefined) return false;
    
    if (!('size' in value) || value['size'] === undefined) return false;
    
    if (!('wid' in value) || value['wid'] === undefined) return false;
    
    return true;
}

export function BackupUpgradeCreateDynamicCloseRequestFromJSON(json: any): BackupUpgradeCreateDynamicCloseRequest {
    return BackupUpgradeCreateDynamicCloseRequestFromJSONTyped(json, false);
}

export function BackupUpgradeCreateDynamicCloseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupUpgradeCreateDynamicCloseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'chunkCount': json['chunk-count'],
        
        'csum': json['csum'],
        
        'size': json['size'],
        
        'wid': json['wid'],
        
    };
}

export function BackupUpgradeCreateDynamicCloseRequestToJSON(json: any): BackupUpgradeCreateDynamicCloseRequest {
    return BackupUpgradeCreateDynamicCloseRequestToJSONTyped(json, false);
}

export function BackupUpgradeCreateDynamicCloseRequestToJSONTyped(value?: BackupUpgradeCreateDynamicCloseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'chunk-count': value['chunkCount'],
        
        'csum': value['csum'],
        
        'size': value['size'],
        
        'wid': value['wid'],
        
    };
}

