/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigAcmeCreatePluginsRequest
 */
export interface ConfigAcmeCreatePluginsRequest {

    /**
     * DNS API Plugin Id.
     * @type {string}
     * @memberof ConfigAcmeCreatePluginsRequest
     */
    api: string;

    /**
     * DNS plugin data (base64 encoded with padding).
     * @type {string}
     * @memberof ConfigAcmeCreatePluginsRequest
     */
    data: string;

    /**
     * Flag to disable the config.
     * @type {boolean}
     * @memberof ConfigAcmeCreatePluginsRequest
     */
    disable?: boolean;

    /**
     * ACME Challenge Plugin ID.
     * @type {string}
     * @memberof ConfigAcmeCreatePluginsRequest
     */
    id: string;

    /**
     * The ACME challenge plugin type.
     * @type {string}
     * @memberof ConfigAcmeCreatePluginsRequest
     */
    type: string;

    /**
     * Extra delay in seconds to wait before requesting validation.
     * 
     * Allows to cope with long TTL of DNS records.
     * @type {number}
     * @memberof ConfigAcmeCreatePluginsRequest
     */
    validationDelay?: number;

}

/**
 * Check if a given object implements the ConfigAcmeCreatePluginsRequest interface.
 */
export function instanceOfConfigAcmeCreatePluginsRequest(value: object): value is ConfigAcmeCreatePluginsRequest {
    
    if (!('api' in value) || value['api'] === undefined) return false;
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    if (!('id' in value) || value['id'] === undefined) return false;
    
    if (!('type' in value) || value['type'] === undefined) return false;
    
    
    return true;
}

export function ConfigAcmeCreatePluginsRequestFromJSON(json: any): ConfigAcmeCreatePluginsRequest {
    return ConfigAcmeCreatePluginsRequestFromJSONTyped(json, false);
}

export function ConfigAcmeCreatePluginsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigAcmeCreatePluginsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'api': json['api'],
        
        'data': json['data'],
        
        'disable': json['disable'] == null ? undefined : json['disable'],
        
        'id': json['id'],
        
        'type': json['type'],
        
        'validationDelay': json['validation-delay'] == null ? undefined : json['validation-delay'],
        
    };
}

export function ConfigAcmeCreatePluginsRequestToJSON(json: any): ConfigAcmeCreatePluginsRequest {
    return ConfigAcmeCreatePluginsRequestToJSONTyped(json, false);
}

export function ConfigAcmeCreatePluginsRequestToJSONTyped(value?: ConfigAcmeCreatePluginsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'api': value['api'],
        
        'data': value['data'],
        
        'disable': value['disable'],
        
        'id': value['id'],
        
        'type': value['type'],
        
        'validation-delay': value['validationDelay'],
        
    };
}

