/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsConfigMetricsInlineEnum } from './PbsConfigMetricsInlineEnum';
import {
    PbsConfigMetricsInlineEnumFromJSON,
    PbsConfigMetricsInlineEnumFromJSONTyped,
    PbsConfigMetricsInlineEnumToJSON,
    PbsConfigMetricsInlineEnumToJSONTyped,
} from './PbsConfigMetricsInlineEnum';

/**
 * 
 * @export
 * @interface ConfigMetricsUpdateInfluxdbHttpRequest
 */
export interface ConfigMetricsUpdateInfluxdbHttpRequest {

    /**
     * InfluxDB Bucket.
     * @type {string}
     * @memberof ConfigMetricsUpdateInfluxdbHttpRequest
     */
    bucket?: string;

    /**
     * Comment.
     * @type {string}
     * @memberof ConfigMetricsUpdateInfluxdbHttpRequest
     */
    comment?: string;

    /**
     * List of properties to delete.
     * @type {Array<PbsConfigMetricsInlineEnum>}
     * @memberof ConfigMetricsUpdateInfluxdbHttpRequest
     */
    _delete?: Array<PbsConfigMetricsInlineEnum>;

    /**
     * Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof ConfigMetricsUpdateInfluxdbHttpRequest
     */
    digest?: string;

    /**
     * Enables or disables the metrics server
     * @type {boolean}
     * @memberof ConfigMetricsUpdateInfluxdbHttpRequest
     */
    enable?: boolean;

    /**
     * The (optional) maximum body size
     * @type {number}
     * @memberof ConfigMetricsUpdateInfluxdbHttpRequest
     */
    maxBodySize?: bigint | string | number;

    /**
     * InfluxDB Organization.
     * @type {string}
     * @memberof ConfigMetricsUpdateInfluxdbHttpRequest
     */
    organization?: string;

    /**
     * The (optional) API token
     * @type {string}
     * @memberof ConfigMetricsUpdateInfluxdbHttpRequest
     */
    token?: string;

    /**
     * HTTP(s) url with optional port.
     * @type {string}
     * @memberof ConfigMetricsUpdateInfluxdbHttpRequest
     */
    url?: string;

    /**
     * If true, the certificate will be validated.
     * @type {boolean}
     * @memberof ConfigMetricsUpdateInfluxdbHttpRequest
     */
    verifyTls?: boolean;

}

/**
 * Check if a given object implements the ConfigMetricsUpdateInfluxdbHttpRequest interface.
 */
export function instanceOfConfigMetricsUpdateInfluxdbHttpRequest(value: object): value is ConfigMetricsUpdateInfluxdbHttpRequest {
    
    
    
    
    
    
    
    
    
    
    
    return true;
}

export function ConfigMetricsUpdateInfluxdbHttpRequestFromJSON(json: any): ConfigMetricsUpdateInfluxdbHttpRequest {
    return ConfigMetricsUpdateInfluxdbHttpRequestFromJSONTyped(json, false);
}

export function ConfigMetricsUpdateInfluxdbHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigMetricsUpdateInfluxdbHttpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'bucket': json['bucket'] == null ? undefined : json['bucket'],
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        '_delete': json['delete'] == null ? undefined : ((json['delete'] as Array<any>).map(PbsConfigMetricsInlineEnumFromJSON)),
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'enable': json['enable'] == null ? undefined : json['enable'],
        
        'maxBodySize': json['max-body-size'] == null ? undefined : BigInt(json['max-body-size']),
        
        'organization': json['organization'] == null ? undefined : json['organization'],
        
        'token': json['token'] == null ? undefined : json['token'],
        
        'url': json['url'] == null ? undefined : json['url'],
        
        'verifyTls': json['verify-tls'] == null ? undefined : json['verify-tls'],
        
    };
}

export function ConfigMetricsUpdateInfluxdbHttpRequestToJSON(json: any): ConfigMetricsUpdateInfluxdbHttpRequest {
    return ConfigMetricsUpdateInfluxdbHttpRequestToJSONTyped(json, false);
}

export function ConfigMetricsUpdateInfluxdbHttpRequestToJSONTyped(value?: ConfigMetricsUpdateInfluxdbHttpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'bucket': value['bucket'],
        
        'comment': value['comment'],
        
        'delete': value['_delete'] == null ? undefined : ((value['_delete'] as Array<any>).map(PbsConfigMetricsInlineEnumToJSON)),
        
        'digest': value['digest'],
        
        'enable': value['enable'],
        
        'max-body-size': value['maxBodySize'] == null ? undefined : String(value['maxBodySize']),
        
        'organization': value['organization'],
        
        'token': value['token'],
        
        'url': value['url'],
        
        'verify-tls': value['verifyTls'],
        
    };
}

