/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigDatastoreGetDatastoreResponseDataInner } from './ConfigDatastoreGetDatastoreResponseDataInner';
import {
    ConfigDatastoreGetDatastoreResponseDataInnerFromJSON,
    ConfigDatastoreGetDatastoreResponseDataInnerFromJSONTyped,
    ConfigDatastoreGetDatastoreResponseDataInnerToJSON,
    ConfigDatastoreGetDatastoreResponseDataInnerToJSONTyped,
} from './ConfigDatastoreGetDatastoreResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigDatastoreGetConfigDatastoreByNameResponse
 */
export interface ConfigDatastoreGetConfigDatastoreByNameResponse {

    /**
     * 
     * @type {ConfigDatastoreGetDatastoreResponseDataInner}
     * @memberof ConfigDatastoreGetConfigDatastoreByNameResponse
     */
    data: ConfigDatastoreGetDatastoreResponseDataInner;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigDatastoreGetConfigDatastoreByNameResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigDatastoreGetConfigDatastoreByNameResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigDatastoreGetConfigDatastoreByNameResponse interface.
 */
export function instanceOfConfigDatastoreGetConfigDatastoreByNameResponse(value: object): value is ConfigDatastoreGetConfigDatastoreByNameResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigDatastoreGetConfigDatastoreByNameResponseFromJSON(json: any): ConfigDatastoreGetConfigDatastoreByNameResponse {
    return ConfigDatastoreGetConfigDatastoreByNameResponseFromJSONTyped(json, false);
}

export function ConfigDatastoreGetConfigDatastoreByNameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDatastoreGetConfigDatastoreByNameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ConfigDatastoreGetDatastoreResponseDataInnerFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigDatastoreGetConfigDatastoreByNameResponseToJSON(json: any): ConfigDatastoreGetConfigDatastoreByNameResponse {
    return ConfigDatastoreGetConfigDatastoreByNameResponseToJSONTyped(json, false);
}

export function ConfigDatastoreGetConfigDatastoreByNameResponseToJSONTyped(value?: ConfigDatastoreGetConfigDatastoreByNameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ConfigDatastoreGetDatastoreResponseDataInnerToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

