/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigNotificationsGetSmtpResponseDataInner } from './ConfigNotificationsGetSmtpResponseDataInner';
import {
    ConfigNotificationsGetSmtpResponseDataInnerFromJSON,
    ConfigNotificationsGetSmtpResponseDataInnerFromJSONTyped,
    ConfigNotificationsGetSmtpResponseDataInnerToJSON,
    ConfigNotificationsGetSmtpResponseDataInnerToJSONTyped,
} from './ConfigNotificationsGetSmtpResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigNotificationsGetSmtpResponse
 */
export interface ConfigNotificationsGetSmtpResponse {

    /**
     * 
     * @type {Array<ConfigNotificationsGetSmtpResponseDataInner>}
     * @memberof ConfigNotificationsGetSmtpResponse
     */
    data: Array<ConfigNotificationsGetSmtpResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigNotificationsGetSmtpResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigNotificationsGetSmtpResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigNotificationsGetSmtpResponse interface.
 */
export function instanceOfConfigNotificationsGetSmtpResponse(value: object): value is ConfigNotificationsGetSmtpResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigNotificationsGetSmtpResponseFromJSON(json: any): ConfigNotificationsGetSmtpResponse {
    return ConfigNotificationsGetSmtpResponseFromJSONTyped(json, false);
}

export function ConfigNotificationsGetSmtpResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigNotificationsGetSmtpResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigNotificationsGetSmtpResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigNotificationsGetSmtpResponseToJSON(json: any): ConfigNotificationsGetSmtpResponse {
    return ConfigNotificationsGetSmtpResponseToJSONTyped(json, false);
}

export function ConfigNotificationsGetSmtpResponseToJSONTyped(value?: ConfigNotificationsGetSmtpResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigNotificationsGetSmtpResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

