/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigMetricsGetInfluxdbUdpResponseDataInner } from './ConfigMetricsGetInfluxdbUdpResponseDataInner';
import {
    ConfigMetricsGetInfluxdbUdpResponseDataInnerFromJSON,
    ConfigMetricsGetInfluxdbUdpResponseDataInnerFromJSONTyped,
    ConfigMetricsGetInfluxdbUdpResponseDataInnerToJSON,
    ConfigMetricsGetInfluxdbUdpResponseDataInnerToJSONTyped,
} from './ConfigMetricsGetInfluxdbUdpResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse
 */
export interface ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse {

    /**
     * 
     * @type {ConfigMetricsGetInfluxdbUdpResponseDataInner}
     * @memberof ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse
     */
    data: ConfigMetricsGetInfluxdbUdpResponseDataInner;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse interface.
 */
export function instanceOfConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse(value: object): value is ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponseFromJSON(json: any): ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse {
    return ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponseFromJSONTyped(json, false);
}

export function ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ConfigMetricsGetInfluxdbUdpResponseDataInnerFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponseToJSON(json: any): ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse {
    return ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponseToJSONTyped(json, false);
}

export function ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponseToJSONTyped(value?: ConfigMetricsGetConfigMetricsInfluxdbUdpByNameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ConfigMetricsGetInfluxdbUdpResponseDataInnerToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

