/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsScopesField } from './PbsScopesField';
import {
    PbsScopesFieldFromJSON,
    PbsScopesFieldFromJSONTyped,
    PbsScopesFieldToJSON,
    PbsScopesFieldToJSONTyped,
} from './PbsScopesField';
import type { PbsAcrValuesField } from './PbsAcrValuesField';
import {
    PbsAcrValuesFieldFromJSON,
    PbsAcrValuesFieldFromJSONTyped,
    PbsAcrValuesFieldToJSON,
    PbsAcrValuesFieldToJSONTyped,
} from './PbsAcrValuesField';

/**
 * 
 * @export
 * @interface ConfigAccessGetOpenidResponseDataInner
 */
export interface ConfigAccessGetOpenidResponseDataInner {

    /**
     * OpenID ACR List
     * @type {PbsAcrValuesField}
     * @memberof ConfigAccessGetOpenidResponseDataInner
     */
    acrValues?: PbsAcrValuesField;

    /**
     * Automatically create users if they do not exist.
     * @type {boolean}
     * @memberof ConfigAccessGetOpenidResponseDataInner
     */
    autocreate?: boolean;

    /**
     * OpenID Client ID
     * @type {string}
     * @memberof ConfigAccessGetOpenidResponseDataInner
     */
    clientId: string;

    /**
     * OpenID Client Key
     * @type {string}
     * @memberof ConfigAccessGetOpenidResponseDataInner
     */
    clientKey?: string;

    /**
     * Comment.
     * @type {string}
     * @memberof ConfigAccessGetOpenidResponseDataInner
     */
    comment?: string;

    /**
     * True if you want this to be the default realm selected on login.
     * @type {boolean}
     * @memberof ConfigAccessGetOpenidResponseDataInner
     */
    _default?: boolean;

    /**
     * OpenID Issuer Url
     * @type {string}
     * @memberof ConfigAccessGetOpenidResponseDataInner
     */
    issuerUrl: string;

    /**
     * OpenID Prompt
     * @type {string}
     * @memberof ConfigAccessGetOpenidResponseDataInner
     */
    prompt?: string;

    /**
     * Realm name.
     * @type {string}
     * @memberof ConfigAccessGetOpenidResponseDataInner
     */
    realm: string;

    /**
     * OpenID Scope List
     * @type {PbsScopesField}
     * @memberof ConfigAccessGetOpenidResponseDataInner
     */
    scopes?: PbsScopesField;

    /**
     * Use the value of this attribute/claim as unique user name. It is up to the identity provider to guarantee the uniqueness. The OpenID specification only guarantees that Subject ('sub') is unique. Also make sure that the user is not allowed to change that attribute by himself!
     * @type {string}
     * @memberof ConfigAccessGetOpenidResponseDataInner
     */
    usernameClaim?: string;

}

/**
 * Check if a given object implements the ConfigAccessGetOpenidResponseDataInner interface.
 */
export function instanceOfConfigAccessGetOpenidResponseDataInner(value: object): value is ConfigAccessGetOpenidResponseDataInner {
    
    
    
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    
    
    
    
    if (!('issuerUrl' in value) || value['issuerUrl'] === undefined) return false;
    
    
    if (!('realm' in value) || value['realm'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigAccessGetOpenidResponseDataInnerFromJSON(json: any): ConfigAccessGetOpenidResponseDataInner {
    return ConfigAccessGetOpenidResponseDataInnerFromJSONTyped(json, false);
}

export function ConfigAccessGetOpenidResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigAccessGetOpenidResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'acrValues': json['acr-values'] == null ? undefined : PbsAcrValuesFieldFromJSON(json['acr-values']),
        
        'autocreate': json['autocreate'] == null ? undefined : json['autocreate'],
        
        'clientId': json['client-id'],
        
        'clientKey': json['client-key'] == null ? undefined : json['client-key'],
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        '_default': json['default'] == null ? undefined : json['default'],
        
        'issuerUrl': json['issuer-url'],
        
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        
        'realm': json['realm'],
        
        'scopes': json['scopes'] == null ? undefined : PbsScopesFieldFromJSON(json['scopes']),
        
        'usernameClaim': json['username-claim'] == null ? undefined : json['username-claim'],
        
    };
}

export function ConfigAccessGetOpenidResponseDataInnerToJSON(json: any): ConfigAccessGetOpenidResponseDataInner {
    return ConfigAccessGetOpenidResponseDataInnerToJSONTyped(json, false);
}

export function ConfigAccessGetOpenidResponseDataInnerToJSONTyped(value?: ConfigAccessGetOpenidResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'acr-values': PbsAcrValuesFieldToJSON(value['acrValues']),
        
        'autocreate': value['autocreate'],
        
        'client-id': value['clientId'],
        
        'client-key': value['clientKey'],
        
        'comment': value['comment'],
        
        'default': value['_default'],
        
        'issuer-url': value['issuerUrl'],
        
        'prompt': value['prompt'],
        
        'realm': value['realm'],
        
        'scopes': PbsScopesFieldToJSON(value['scopes']),
        
        'username-claim': value['usernameClaim'],
        
    };
}

