/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsNotificationModeEnum } from './PbsNotificationModeEnum';
import {
    PbsNotificationModeEnumFromJSON,
    PbsNotificationModeEnumFromJSONTyped,
    PbsNotificationModeEnumToJSON,
    PbsNotificationModeEnumToJSONTyped,
} from './PbsNotificationModeEnum';
import type { PbsConfigTapeBackupJobInlineEnum } from './PbsConfigTapeBackupJobInlineEnum';
import {
    PbsConfigTapeBackupJobInlineEnumFromJSON,
    PbsConfigTapeBackupJobInlineEnumFromJSONTyped,
    PbsConfigTapeBackupJobInlineEnumToJSON,
    PbsConfigTapeBackupJobInlineEnumToJSONTyped,
} from './PbsConfigTapeBackupJobInlineEnum';

/**
 * 
 * @export
 * @interface ConfigTapeBackupJobUpdateTapeBackupJobRequest
 */
export interface ConfigTapeBackupJobUpdateTapeBackupJobRequest {

    /**
     * Comment.
     * @type {string}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    comment?: string;

    /**
     * List of properties to delete.
     * @type {Array<PbsConfigTapeBackupJobInlineEnum>}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    _delete?: Array<PbsConfigTapeBackupJobInlineEnum>;

    /**
     * Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    digest?: string;

    /**
     * Drive Identifier.
     * @type {string}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    drive?: string;

    /**
     * Eject media upon job completion.
     * @type {boolean}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    ejectMedia?: boolean;

    /**
     * Export media set upon job completion.
     * @type {boolean}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    exportMediaSet?: boolean;

    /**
     * List of group filters.
     * @type {Array<string>}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    groupFilter?: Array<string>;

    /**
     * Backup latest snapshots only.
     * @type {boolean}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    latestOnly?: boolean;

    /**
     * How many levels of namespaces should be operated on (0 == no recursion)
     * @type {number}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    maxDepth?: number;

    /**
     * Configure how notifications for this datastore should be sent.
     * `legacy-sendmail` sends email notifications to the user configured
     * in `notify-user` via the system's `sendmail` executable.
     * `notification-system` emits matchable notification events to the
     * notification system.
     * @type {PbsNotificationModeEnum}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    notificationMode?: PbsNotificationModeEnum;

    /**
     * User ID
     * @type {string}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    notifyUser?: string;

    /**
     * Namespace.
     * @type {string}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    ns?: string;

    /**
     * Media pool name.
     * @type {string}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    pool?: string;

    /**
     * Run sync job at specified schedule.
     * @type {string}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    schedule?: string;

    /**
     * Datastore name.
     * @type {string}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    store?: string;

    /**
     * The number of threads to use for the tape backup job.
     * @type {number}
     * @memberof ConfigTapeBackupJobUpdateTapeBackupJobRequest
     */
    workerThreads?: number;

}



/**
 * Check if a given object implements the ConfigTapeBackupJobUpdateTapeBackupJobRequest interface.
 */
export function instanceOfConfigTapeBackupJobUpdateTapeBackupJobRequest(value: object): value is ConfigTapeBackupJobUpdateTapeBackupJobRequest {
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    return true;
}

export function ConfigTapeBackupJobUpdateTapeBackupJobRequestFromJSON(json: any): ConfigTapeBackupJobUpdateTapeBackupJobRequest {
    return ConfigTapeBackupJobUpdateTapeBackupJobRequestFromJSONTyped(json, false);
}

export function ConfigTapeBackupJobUpdateTapeBackupJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTapeBackupJobUpdateTapeBackupJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        '_delete': json['delete'] == null ? undefined : ((json['delete'] as Array<any>).map(PbsConfigTapeBackupJobInlineEnumFromJSON)),
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'drive': json['drive'] == null ? undefined : json['drive'],
        
        'ejectMedia': json['eject-media'] == null ? undefined : json['eject-media'],
        
        'exportMediaSet': json['export-media-set'] == null ? undefined : json['export-media-set'],
        
        'groupFilter': json['group-filter'] == null ? undefined : json['group-filter'],
        
        'latestOnly': json['latest-only'] == null ? undefined : json['latest-only'],
        
        'maxDepth': json['max-depth'] == null ? undefined : json['max-depth'],
        
        'notificationMode': json['notification-mode'] == null ? undefined : PbsNotificationModeEnumFromJSON(json['notification-mode']),
        
        'notifyUser': json['notify-user'] == null ? undefined : json['notify-user'],
        
        'ns': json['ns'] == null ? undefined : json['ns'],
        
        'pool': json['pool'] == null ? undefined : json['pool'],
        
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        
        'store': json['store'] == null ? undefined : json['store'],
        
        'workerThreads': json['worker-threads'] == null ? undefined : json['worker-threads'],
        
    };
}

export function ConfigTapeBackupJobUpdateTapeBackupJobRequestToJSON(json: any): ConfigTapeBackupJobUpdateTapeBackupJobRequest {
    return ConfigTapeBackupJobUpdateTapeBackupJobRequestToJSONTyped(json, false);
}

export function ConfigTapeBackupJobUpdateTapeBackupJobRequestToJSONTyped(value?: ConfigTapeBackupJobUpdateTapeBackupJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'comment': value['comment'],
        
        'delete': value['_delete'] == null ? undefined : ((value['_delete'] as Array<any>).map(PbsConfigTapeBackupJobInlineEnumToJSON)),
        
        'digest': value['digest'],
        
        'drive': value['drive'],
        
        'eject-media': value['ejectMedia'],
        
        'export-media-set': value['exportMediaSet'],
        
        'group-filter': value['groupFilter'],
        
        'latest-only': value['latestOnly'],
        
        'max-depth': value['maxDepth'],
        
        'notification-mode': PbsNotificationModeEnumToJSON(value['notificationMode']),
        
        'notify-user': value['notifyUser'],
        
        'ns': value['ns'],
        
        'pool': value['pool'],
        
        'schedule': value['schedule'],
        
        'store': value['store'],
        
        'worker-threads': value['workerThreads'],
        
    };
}

