/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigVerifyGetVerifyResponseDataInner } from './ConfigVerifyGetVerifyResponseDataInner';
import {
    ConfigVerifyGetVerifyResponseDataInnerFromJSON,
    ConfigVerifyGetVerifyResponseDataInnerFromJSONTyped,
    ConfigVerifyGetVerifyResponseDataInnerToJSON,
    ConfigVerifyGetVerifyResponseDataInnerToJSONTyped,
} from './ConfigVerifyGetVerifyResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigVerifyGetConfigVerifyByIdResponse
 */
export interface ConfigVerifyGetConfigVerifyByIdResponse {

    /**
     * 
     * @type {ConfigVerifyGetVerifyResponseDataInner}
     * @memberof ConfigVerifyGetConfigVerifyByIdResponse
     */
    data: ConfigVerifyGetVerifyResponseDataInner;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigVerifyGetConfigVerifyByIdResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigVerifyGetConfigVerifyByIdResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigVerifyGetConfigVerifyByIdResponse interface.
 */
export function instanceOfConfigVerifyGetConfigVerifyByIdResponse(value: object): value is ConfigVerifyGetConfigVerifyByIdResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigVerifyGetConfigVerifyByIdResponseFromJSON(json: any): ConfigVerifyGetConfigVerifyByIdResponse {
    return ConfigVerifyGetConfigVerifyByIdResponseFromJSONTyped(json, false);
}

export function ConfigVerifyGetConfigVerifyByIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigVerifyGetConfigVerifyByIdResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ConfigVerifyGetVerifyResponseDataInnerFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigVerifyGetConfigVerifyByIdResponseToJSON(json: any): ConfigVerifyGetConfigVerifyByIdResponse {
    return ConfigVerifyGetConfigVerifyByIdResponseToJSONTyped(json, false);
}

export function ConfigVerifyGetConfigVerifyByIdResponseToJSONTyped(value?: ConfigVerifyGetConfigVerifyByIdResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ConfigVerifyGetVerifyResponseDataInnerToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

