/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsConfigAccessInlineEnum } from './PbsConfigAccessInlineEnum';
import {
    PbsConfigAccessInlineEnumFromJSON,
    PbsConfigAccessInlineEnumFromJSONTyped,
    PbsConfigAccessInlineEnumToJSON,
    PbsConfigAccessInlineEnumToJSONTyped,
} from './PbsConfigAccessInlineEnum';
import type { PbsScopesField } from './PbsScopesField';
import {
    PbsScopesFieldFromJSON,
    PbsScopesFieldFromJSONTyped,
    PbsScopesFieldToJSON,
    PbsScopesFieldToJSONTyped,
} from './PbsScopesField';
import type { PbsAcrValuesField } from './PbsAcrValuesField';
import {
    PbsAcrValuesFieldFromJSON,
    PbsAcrValuesFieldFromJSONTyped,
    PbsAcrValuesFieldToJSON,
    PbsAcrValuesFieldToJSONTyped,
} from './PbsAcrValuesField';

/**
 * 
 * @export
 * @interface ConfigAccessUpdateOpenidRequest
 */
export interface ConfigAccessUpdateOpenidRequest {

    /**
     * OpenID ACR List
     * @type {PbsAcrValuesField}
     * @memberof ConfigAccessUpdateOpenidRequest
     */
    acrValues?: PbsAcrValuesField;

    /**
     * Automatically create users if they do not exist.
     * @type {boolean}
     * @memberof ConfigAccessUpdateOpenidRequest
     */
    autocreate?: boolean;

    /**
     * OpenID Client ID
     * @type {string}
     * @memberof ConfigAccessUpdateOpenidRequest
     */
    clientId?: string;

    /**
     * OpenID Client Key
     * @type {string}
     * @memberof ConfigAccessUpdateOpenidRequest
     */
    clientKey?: string;

    /**
     * Comment.
     * @type {string}
     * @memberof ConfigAccessUpdateOpenidRequest
     */
    comment?: string;

    /**
     * True if you want this to be the default realm selected on login.
     * @type {boolean}
     * @memberof ConfigAccessUpdateOpenidRequest
     */
    _default?: boolean;

    /**
     * List of properties to delete.
     * @type {Array<PbsConfigAccessInlineEnum>}
     * @memberof ConfigAccessUpdateOpenidRequest
     */
    _delete?: Array<PbsConfigAccessInlineEnum>;

    /**
     * Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof ConfigAccessUpdateOpenidRequest
     */
    digest?: string;

    /**
     * OpenID Issuer Url
     * @type {string}
     * @memberof ConfigAccessUpdateOpenidRequest
     */
    issuerUrl?: string;

    /**
     * OpenID Prompt
     * @type {string}
     * @memberof ConfigAccessUpdateOpenidRequest
     */
    prompt?: string;

    /**
     * OpenID Scope List
     * @type {PbsScopesField}
     * @memberof ConfigAccessUpdateOpenidRequest
     */
    scopes?: PbsScopesField;

}

/**
 * Check if a given object implements the ConfigAccessUpdateOpenidRequest interface.
 */
export function instanceOfConfigAccessUpdateOpenidRequest(value: object): value is ConfigAccessUpdateOpenidRequest {
    
    
    
    
    
    
    
    
    
    
    
    
    return true;
}

export function ConfigAccessUpdateOpenidRequestFromJSON(json: any): ConfigAccessUpdateOpenidRequest {
    return ConfigAccessUpdateOpenidRequestFromJSONTyped(json, false);
}

export function ConfigAccessUpdateOpenidRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigAccessUpdateOpenidRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'acrValues': json['acr-values'] == null ? undefined : PbsAcrValuesFieldFromJSON(json['acr-values']),
        
        'autocreate': json['autocreate'] == null ? undefined : json['autocreate'],
        
        'clientId': json['client-id'] == null ? undefined : json['client-id'],
        
        'clientKey': json['client-key'] == null ? undefined : json['client-key'],
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        '_default': json['default'] == null ? undefined : json['default'],
        
        '_delete': json['delete'] == null ? undefined : ((json['delete'] as Array<any>).map(PbsConfigAccessInlineEnumFromJSON)),
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'issuerUrl': json['issuer-url'] == null ? undefined : json['issuer-url'],
        
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        
        'scopes': json['scopes'] == null ? undefined : PbsScopesFieldFromJSON(json['scopes']),
        
    };
}

export function ConfigAccessUpdateOpenidRequestToJSON(json: any): ConfigAccessUpdateOpenidRequest {
    return ConfigAccessUpdateOpenidRequestToJSONTyped(json, false);
}

export function ConfigAccessUpdateOpenidRequestToJSONTyped(value?: ConfigAccessUpdateOpenidRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'acr-values': PbsAcrValuesFieldToJSON(value['acrValues']),
        
        'autocreate': value['autocreate'],
        
        'client-id': value['clientId'],
        
        'client-key': value['clientKey'],
        
        'comment': value['comment'],
        
        'default': value['_default'],
        
        'delete': value['_delete'] == null ? undefined : ((value['_delete'] as Array<any>).map(PbsConfigAccessInlineEnumToJSON)),
        
        'digest': value['digest'],
        
        'issuer-url': value['issuerUrl'],
        
        'prompt': value['prompt'],
        
        'scopes': PbsScopesFieldToJSON(value['scopes']),
        
    };
}

