/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsMethodEnum } from './PbsMethodEnum';
import {
    PbsMethodEnumFromJSON,
    PbsMethodEnumFromJSONTyped,
    PbsMethodEnumToJSON,
    PbsMethodEnumToJSONTyped,
} from './PbsMethodEnum';
import type { PbsOriginEnum } from './PbsOriginEnum';
import {
    PbsOriginEnumFromJSON,
    PbsOriginEnumFromJSONTyped,
    PbsOriginEnumToJSON,
    PbsOriginEnumToJSONTyped,
} from './PbsOriginEnum';
import type { ConfigNotificationsGetWebhookResponseDataInnerHeaderInner } from './ConfigNotificationsGetWebhookResponseDataInnerHeaderInner';
import {
    ConfigNotificationsGetWebhookResponseDataInnerHeaderInnerFromJSON,
    ConfigNotificationsGetWebhookResponseDataInnerHeaderInnerFromJSONTyped,
    ConfigNotificationsGetWebhookResponseDataInnerHeaderInnerToJSON,
    ConfigNotificationsGetWebhookResponseDataInnerHeaderInnerToJSONTyped,
} from './ConfigNotificationsGetWebhookResponseDataInnerHeaderInner';

/**
 * 
 * @export
 * @interface ConfigNotificationsGetWebhookResponseDataInner
 */
export interface ConfigNotificationsGetWebhookResponseDataInner {

    /**
     * The HTTP body to send. Supports templating.
     * @type {string}
     * @memberof ConfigNotificationsGetWebhookResponseDataInner
     */
    body?: string;

    /**
     * Comment.
     * @type {string}
     * @memberof ConfigNotificationsGetWebhookResponseDataInner
     */
    comment?: string;

    /**
     * Disable this target.
     * @type {boolean}
     * @memberof ConfigNotificationsGetWebhookResponseDataInner
     */
    disable?: boolean;

    /**
     * Array of HTTP headers. Each entry is a property string with a name and a value.
     * The value property contains the header in base64 encoding. Supports templating.
     * @type {Array<ConfigNotificationsGetWebhookResponseDataInnerHeaderInner>}
     * @memberof ConfigNotificationsGetWebhookResponseDataInner
     */
    header?: Array<ConfigNotificationsGetWebhookResponseDataInnerHeaderInner>;

    /**
     * HTTP Method to use.
     * @type {PbsMethodEnum}
     * @memberof ConfigNotificationsGetWebhookResponseDataInner
     */
    method: PbsMethodEnum;

    /**
     * Name schema for targets and matchers
     * @type {string}
     * @memberof ConfigNotificationsGetWebhookResponseDataInner
     */
    name: string;

    /**
     * The origin of a notification configuration entry.
     * @type {PbsOriginEnum}
     * @memberof ConfigNotificationsGetWebhookResponseDataInner
     */
    origin?: PbsOriginEnum;

    /**
     * Array of secrets. Each entry is a property string with a name and an optional value.
     * The value property contains the secret in base64 encoding.
     * For any API endpoints returning the endpoint config,
     * only the secret name but not the value will be returned.
     * When updating the config, also send all secrets that you want
     * to keep, setting only the name but not the value. Can be accessed from templates.
     * @type {Array<ConfigNotificationsGetWebhookResponseDataInnerHeaderInner>}
     * @memberof ConfigNotificationsGetWebhookResponseDataInner
     */
    secret?: Array<ConfigNotificationsGetWebhookResponseDataInnerHeaderInner>;

    /**
     * HTTP(s) url with optional port.
     * @type {string}
     * @memberof ConfigNotificationsGetWebhookResponseDataInner
     */
    url: string;

}



/**
 * Check if a given object implements the ConfigNotificationsGetWebhookResponseDataInner interface.
 */
export function instanceOfConfigNotificationsGetWebhookResponseDataInner(value: object): value is ConfigNotificationsGetWebhookResponseDataInner {
    
    
    
    
    
    if (!('method' in value) || value['method'] === undefined) return false;
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    
    
    if (!('url' in value) || value['url'] === undefined) return false;
    
    return true;
}

export function ConfigNotificationsGetWebhookResponseDataInnerFromJSON(json: any): ConfigNotificationsGetWebhookResponseDataInner {
    return ConfigNotificationsGetWebhookResponseDataInnerFromJSONTyped(json, false);
}

export function ConfigNotificationsGetWebhookResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigNotificationsGetWebhookResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'body': json['body'] == null ? undefined : json['body'],
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        'disable': json['disable'] == null ? undefined : json['disable'],
        
        'header': json['header'] == null ? undefined : ((json['header'] as Array<any>).map(ConfigNotificationsGetWebhookResponseDataInnerHeaderInnerFromJSON)),
        
        'method': PbsMethodEnumFromJSON(json['method']),
        
        'name': json['name'],
        
        'origin': json['origin'] == null ? undefined : PbsOriginEnumFromJSON(json['origin']),
        
        'secret': json['secret'] == null ? undefined : ((json['secret'] as Array<any>).map(ConfigNotificationsGetWebhookResponseDataInnerHeaderInnerFromJSON)),
        
        'url': json['url'],
        
    };
}

export function ConfigNotificationsGetWebhookResponseDataInnerToJSON(json: any): ConfigNotificationsGetWebhookResponseDataInner {
    return ConfigNotificationsGetWebhookResponseDataInnerToJSONTyped(json, false);
}

export function ConfigNotificationsGetWebhookResponseDataInnerToJSONTyped(value?: ConfigNotificationsGetWebhookResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'body': value['body'],
        
        'comment': value['comment'],
        
        'disable': value['disable'],
        
        'header': value['header'] == null ? undefined : ((value['header'] as Array<any>).map(ConfigNotificationsGetWebhookResponseDataInnerHeaderInnerToJSON)),
        
        'method': PbsMethodEnumToJSON(value['method']),
        
        'name': value['name'],
        
        'origin': PbsOriginEnumToJSON(value['origin']),
        
        'secret': value['secret'] == null ? undefined : ((value['secret'] as Array<any>).map(ConfigNotificationsGetWebhookResponseDataInnerHeaderInnerToJSON)),
        
        'url': value['url'],
        
    };
}

