/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsKdfEnum } from './PbsKdfEnum';
import {
    PbsKdfEnumFromJSON,
    PbsKdfEnumFromJSONTyped,
    PbsKdfEnumToJSON,
    PbsKdfEnumToJSONTyped,
} from './PbsKdfEnum';

/**
 * 
 * @export
 * @interface ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest
 */
export interface ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest {

    /**
     * Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest
     */
    digest?: string;

    /**
     * Reset the passphrase for a tape key, using the root-only accessible copy.
     * @type {boolean}
     * @memberof ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest
     */
    force?: boolean;

    /**
     * Password hint.
     * @type {string}
     * @memberof ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest
     */
    hint: string;

    /**
     * Key derivation function for password protected encryption keys.
     * @type {PbsKdfEnum}
     * @memberof ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest
     */
    kdf?: PbsKdfEnum;

    /**
     * The new password.
     * @type {string}
     * @memberof ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest
     */
    newPassword: string;

    /**
     * The current password.
     * @type {string}
     * @memberof ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest
     */
    password?: string;

}



/**
 * Check if a given object implements the ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest interface.
 */
export function instanceOfConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest(value: object): value is ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest {
    
    
    
    if (!('hint' in value) || value['hint'] === undefined) return false;
    
    
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    
    
    return true;
}

export function ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequestFromJSON(json: any): ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest {
    return ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequestFromJSONTyped(json, false);
}

export function ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'force': json['force'] == null ? undefined : json['force'],
        
        'hint': json['hint'],
        
        'kdf': json['kdf'] == null ? undefined : PbsKdfEnumFromJSON(json['kdf']),
        
        'newPassword': json['new-password'],
        
        'password': json['password'] == null ? undefined : json['password'],
        
    };
}

export function ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequestToJSON(json: any): ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest {
    return ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequestToJSONTyped(json, false);
}

export function ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequestToJSONTyped(value?: ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'digest': value['digest'],
        
        'force': value['force'],
        
        'hint': value['hint'],
        
        'kdf': PbsKdfEnumToJSON(value['kdf']),
        
        'new-password': value['newPassword'],
        
        'password': value['password'],
        
    };
}

