/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigTrafficControlGetTrafficControlResponseDataInner } from './ConfigTrafficControlGetTrafficControlResponseDataInner';
import {
    ConfigTrafficControlGetTrafficControlResponseDataInnerFromJSON,
    ConfigTrafficControlGetTrafficControlResponseDataInnerFromJSONTyped,
    ConfigTrafficControlGetTrafficControlResponseDataInnerToJSON,
    ConfigTrafficControlGetTrafficControlResponseDataInnerToJSONTyped,
} from './ConfigTrafficControlGetTrafficControlResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigTrafficControlGetTrafficControlResponse
 */
export interface ConfigTrafficControlGetTrafficControlResponse {

    /**
     * 
     * @type {Array<ConfigTrafficControlGetTrafficControlResponseDataInner>}
     * @memberof ConfigTrafficControlGetTrafficControlResponse
     */
    data: Array<ConfigTrafficControlGetTrafficControlResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigTrafficControlGetTrafficControlResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigTrafficControlGetTrafficControlResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigTrafficControlGetTrafficControlResponse interface.
 */
export function instanceOfConfigTrafficControlGetTrafficControlResponse(value: object): value is ConfigTrafficControlGetTrafficControlResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigTrafficControlGetTrafficControlResponseFromJSON(json: any): ConfigTrafficControlGetTrafficControlResponse {
    return ConfigTrafficControlGetTrafficControlResponseFromJSONTyped(json, false);
}

export function ConfigTrafficControlGetTrafficControlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTrafficControlGetTrafficControlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigTrafficControlGetTrafficControlResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigTrafficControlGetTrafficControlResponseToJSON(json: any): ConfigTrafficControlGetTrafficControlResponse {
    return ConfigTrafficControlGetTrafficControlResponseToJSONTyped(json, false);
}

export function ConfigTrafficControlGetTrafficControlResponseToJSONTyped(value?: ConfigTrafficControlGetTrafficControlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigTrafficControlGetTrafficControlResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

