/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigAcmeGetChallengeSchemaResponseDataInner
 */
export interface ConfigAcmeGetChallengeSchemaResponseDataInner {

    /**
     * Plugin ID.
     * @type {string}
     * @memberof ConfigAcmeGetChallengeSchemaResponseDataInner
     */
    id: string;

    /**
     * Human readable name, falls back to id.
     * @type {string}
     * @memberof ConfigAcmeGetChallengeSchemaResponseDataInner
     */
    name: string;

    /**
     * The plugin's parameter schema.
     * @type {object}
     * @memberof ConfigAcmeGetChallengeSchemaResponseDataInner
     */
    schema: object;

    /**
     * Plugin Type.
     * @type {string}
     * @memberof ConfigAcmeGetChallengeSchemaResponseDataInner
     */
    type: string;

}

/**
 * Check if a given object implements the ConfigAcmeGetChallengeSchemaResponseDataInner interface.
 */
export function instanceOfConfigAcmeGetChallengeSchemaResponseDataInner(value: object): value is ConfigAcmeGetChallengeSchemaResponseDataInner {
    
    if (!('id' in value) || value['id'] === undefined) return false;
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    if (!('schema' in value) || value['schema'] === undefined) return false;
    
    if (!('type' in value) || value['type'] === undefined) return false;
    
    return true;
}

export function ConfigAcmeGetChallengeSchemaResponseDataInnerFromJSON(json: any): ConfigAcmeGetChallengeSchemaResponseDataInner {
    return ConfigAcmeGetChallengeSchemaResponseDataInnerFromJSONTyped(json, false);
}

export function ConfigAcmeGetChallengeSchemaResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigAcmeGetChallengeSchemaResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'id': json['id'],
        
        'name': json['name'],
        
        'schema': json['schema'],
        
        'type': json['type'],
        
    };
}

export function ConfigAcmeGetChallengeSchemaResponseDataInnerToJSON(json: any): ConfigAcmeGetChallengeSchemaResponseDataInner {
    return ConfigAcmeGetChallengeSchemaResponseDataInnerToJSONTyped(json, false);
}

export function ConfigAcmeGetChallengeSchemaResponseDataInnerToJSONTyped(value?: ConfigAcmeGetChallengeSchemaResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'id': value['id'],
        
        'name': value['name'],
        
        'schema': value['schema'],
        
        'type': value['type'],
        
    };
}

