/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsConfigVerifyInlineEnum } from './PbsConfigVerifyInlineEnum';
import {
    PbsConfigVerifyInlineEnumFromJSON,
    PbsConfigVerifyInlineEnumFromJSONTyped,
    PbsConfigVerifyInlineEnumToJSON,
    PbsConfigVerifyInlineEnumToJSONTyped,
} from './PbsConfigVerifyInlineEnum';

/**
 * 
 * @export
 * @interface ConfigVerifyUpdateVerifyRequest
 */
export interface ConfigVerifyUpdateVerifyRequest {

    /**
     * Comment.
     * @type {string}
     * @memberof ConfigVerifyUpdateVerifyRequest
     */
    comment?: string;

    /**
     * List of properties to delete.
     * @type {Array<PbsConfigVerifyInlineEnum>}
     * @memberof ConfigVerifyUpdateVerifyRequest
     */
    _delete?: Array<PbsConfigVerifyInlineEnum>;

    /**
     * Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof ConfigVerifyUpdateVerifyRequest
     */
    digest?: string;

    /**
     * Do not verify backups that are already verified if their verification is not outdated.
     * @type {boolean}
     * @memberof ConfigVerifyUpdateVerifyRequest
     */
    ignoreVerified?: boolean;

    /**
     * How many levels of namespaces should be operated on (0 == no recursion)
     * @type {number}
     * @memberof ConfigVerifyUpdateVerifyRequest
     */
    maxDepth?: number;

    /**
     * Namespace.
     * @type {string}
     * @memberof ConfigVerifyUpdateVerifyRequest
     */
    ns?: string;

    /**
     * Days after that a verification becomes outdated. (0 is deprecated)'
     * @type {number}
     * @memberof ConfigVerifyUpdateVerifyRequest
     */
    outdatedAfter?: number;

    /**
     * The number of threads to use for reading chunks in verify job.
     * @type {number}
     * @memberof ConfigVerifyUpdateVerifyRequest
     */
    readThreads?: number;

    /**
     * Run verify job at specified schedule.
     * @type {string}
     * @memberof ConfigVerifyUpdateVerifyRequest
     */
    schedule?: string;

    /**
     * Datastore name.
     * @type {string}
     * @memberof ConfigVerifyUpdateVerifyRequest
     */
    store?: string;

    /**
     * The number of threads to use for verifying chunks in verify job.
     * @type {number}
     * @memberof ConfigVerifyUpdateVerifyRequest
     */
    verifyThreads?: number;

}

/**
 * Check if a given object implements the ConfigVerifyUpdateVerifyRequest interface.
 */
export function instanceOfConfigVerifyUpdateVerifyRequest(value: object): value is ConfigVerifyUpdateVerifyRequest {
    
    
    
    
    
    
    
    
    
    
    
    
    return true;
}

export function ConfigVerifyUpdateVerifyRequestFromJSON(json: any): ConfigVerifyUpdateVerifyRequest {
    return ConfigVerifyUpdateVerifyRequestFromJSONTyped(json, false);
}

export function ConfigVerifyUpdateVerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigVerifyUpdateVerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        '_delete': json['delete'] == null ? undefined : ((json['delete'] as Array<any>).map(PbsConfigVerifyInlineEnumFromJSON)),
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'ignoreVerified': json['ignore-verified'] == null ? undefined : json['ignore-verified'],
        
        'maxDepth': json['max-depth'] == null ? undefined : json['max-depth'],
        
        'ns': json['ns'] == null ? undefined : json['ns'],
        
        'outdatedAfter': json['outdated-after'] == null ? undefined : json['outdated-after'],
        
        'readThreads': json['read-threads'] == null ? undefined : json['read-threads'],
        
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        
        'store': json['store'] == null ? undefined : json['store'],
        
        'verifyThreads': json['verify-threads'] == null ? undefined : json['verify-threads'],
        
    };
}

export function ConfigVerifyUpdateVerifyRequestToJSON(json: any): ConfigVerifyUpdateVerifyRequest {
    return ConfigVerifyUpdateVerifyRequestToJSONTyped(json, false);
}

export function ConfigVerifyUpdateVerifyRequestToJSONTyped(value?: ConfigVerifyUpdateVerifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'comment': value['comment'],
        
        'delete': value['_delete'] == null ? undefined : ((value['_delete'] as Array<any>).map(PbsConfigVerifyInlineEnumToJSON)),
        
        'digest': value['digest'],
        
        'ignore-verified': value['ignoreVerified'],
        
        'max-depth': value['maxDepth'],
        
        'ns': value['ns'],
        
        'outdated-after': value['outdatedAfter'],
        
        'read-threads': value['readThreads'],
        
        'schedule': value['schedule'],
        
        'store': value['store'],
        
        'verify-threads': value['verifyThreads'],
        
    };
}

