/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigMetricsGetInfluxdbUdpResponseDataInner } from './ConfigMetricsGetInfluxdbUdpResponseDataInner';
import {
    ConfigMetricsGetInfluxdbUdpResponseDataInnerFromJSON,
    ConfigMetricsGetInfluxdbUdpResponseDataInnerFromJSONTyped,
    ConfigMetricsGetInfluxdbUdpResponseDataInnerToJSON,
    ConfigMetricsGetInfluxdbUdpResponseDataInnerToJSONTyped,
} from './ConfigMetricsGetInfluxdbUdpResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigMetricsGetInfluxdbUdpResponse
 */
export interface ConfigMetricsGetInfluxdbUdpResponse {

    /**
     * 
     * @type {Array<ConfigMetricsGetInfluxdbUdpResponseDataInner>}
     * @memberof ConfigMetricsGetInfluxdbUdpResponse
     */
    data: Array<ConfigMetricsGetInfluxdbUdpResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigMetricsGetInfluxdbUdpResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigMetricsGetInfluxdbUdpResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigMetricsGetInfluxdbUdpResponse interface.
 */
export function instanceOfConfigMetricsGetInfluxdbUdpResponse(value: object): value is ConfigMetricsGetInfluxdbUdpResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigMetricsGetInfluxdbUdpResponseFromJSON(json: any): ConfigMetricsGetInfluxdbUdpResponse {
    return ConfigMetricsGetInfluxdbUdpResponseFromJSONTyped(json, false);
}

export function ConfigMetricsGetInfluxdbUdpResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigMetricsGetInfluxdbUdpResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigMetricsGetInfluxdbUdpResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigMetricsGetInfluxdbUdpResponseToJSON(json: any): ConfigMetricsGetInfluxdbUdpResponse {
    return ConfigMetricsGetInfluxdbUdpResponseToJSONTyped(json, false);
}

export function ConfigMetricsGetInfluxdbUdpResponseToJSONTyped(value?: ConfigMetricsGetInfluxdbUdpResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigMetricsGetInfluxdbUdpResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

