/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigS3GetS3ResponseDataInner } from './ConfigS3GetS3ResponseDataInner';
import {
    ConfigS3GetS3ResponseDataInnerFromJSON,
    ConfigS3GetS3ResponseDataInnerFromJSONTyped,
    ConfigS3GetS3ResponseDataInnerToJSON,
    ConfigS3GetS3ResponseDataInnerToJSONTyped,
} from './ConfigS3GetS3ResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigS3GetS3Response
 */
export interface ConfigS3GetS3Response {

    /**
     * 
     * @type {Array<ConfigS3GetS3ResponseDataInner>}
     * @memberof ConfigS3GetS3Response
     */
    data: Array<ConfigS3GetS3ResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigS3GetS3Response
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigS3GetS3Response
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigS3GetS3Response interface.
 */
export function instanceOfConfigS3GetS3Response(value: object): value is ConfigS3GetS3Response {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigS3GetS3ResponseFromJSON(json: any): ConfigS3GetS3Response {
    return ConfigS3GetS3ResponseFromJSONTyped(json, false);
}

export function ConfigS3GetS3ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigS3GetS3Response {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigS3GetS3ResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigS3GetS3ResponseToJSON(json: any): ConfigS3GetS3Response {
    return ConfigS3GetS3ResponseToJSONTyped(json, false);
}

export function ConfigS3GetS3ResponseToJSONTyped(value?: ConfigS3GetS3Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigS3GetS3ResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

