/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigAccessGetLdapResponseDataInner } from './ConfigAccessGetLdapResponseDataInner';
import {
    ConfigAccessGetLdapResponseDataInnerFromJSON,
    ConfigAccessGetLdapResponseDataInnerFromJSONTyped,
    ConfigAccessGetLdapResponseDataInnerToJSON,
    ConfigAccessGetLdapResponseDataInnerToJSONTyped,
} from './ConfigAccessGetLdapResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigAccessGetLdapResponse
 */
export interface ConfigAccessGetLdapResponse {

    /**
     * 
     * @type {Array<ConfigAccessGetLdapResponseDataInner>}
     * @memberof ConfigAccessGetLdapResponse
     */
    data: Array<ConfigAccessGetLdapResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigAccessGetLdapResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigAccessGetLdapResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigAccessGetLdapResponse interface.
 */
export function instanceOfConfigAccessGetLdapResponse(value: object): value is ConfigAccessGetLdapResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigAccessGetLdapResponseFromJSON(json: any): ConfigAccessGetLdapResponse {
    return ConfigAccessGetLdapResponseFromJSONTyped(json, false);
}

export function ConfigAccessGetLdapResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigAccessGetLdapResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigAccessGetLdapResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigAccessGetLdapResponseToJSON(json: any): ConfigAccessGetLdapResponse {
    return ConfigAccessGetLdapResponseToJSONTyped(json, false);
}

export function ConfigAccessGetLdapResponseToJSONTyped(value?: ConfigAccessGetLdapResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigAccessGetLdapResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

