/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigTrafficControlGetTrafficControlResponseDataInner
 */
export interface ConfigTrafficControlGetTrafficControlResponseDataInner {

    /**
     * Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
     * @type {string}
     * @memberof ConfigTrafficControlGetTrafficControlResponseDataInner
     */
    burstIn?: string;

    /**
     * Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
     * @type {string}
     * @memberof ConfigTrafficControlGetTrafficControlResponseDataInner
     */
    burstOut?: string;

    /**
     * Comment.
     * @type {string}
     * @memberof ConfigTrafficControlGetTrafficControlResponseDataInner
     */
    comment?: string;

    /**
     * Rule ID.
     * @type {string}
     * @memberof ConfigTrafficControlGetTrafficControlResponseDataInner
     */
    name: string;

    /**
     * Rule applies to Source IPs within this networks
     * @type {Array<string>}
     * @memberof ConfigTrafficControlGetTrafficControlResponseDataInner
     */
    network: Array<string>;

    /**
     * Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
     * @type {string}
     * @memberof ConfigTrafficControlGetTrafficControlResponseDataInner
     */
    rateIn?: string;

    /**
     * Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
     * @type {string}
     * @memberof ConfigTrafficControlGetTrafficControlResponseDataInner
     */
    rateOut?: string;

    /**
     * Enable the rule at specific times
     * @type {Array<string>}
     * @memberof ConfigTrafficControlGetTrafficControlResponseDataInner
     */
    timeframe?: Array<string>;

    /**
     * Rule applies to authenticated API requests of any of these users (overrides IP-only rules)
     * @type {Array<string>}
     * @memberof ConfigTrafficControlGetTrafficControlResponseDataInner
     */
    users?: Array<string>;

}

/**
 * Check if a given object implements the ConfigTrafficControlGetTrafficControlResponseDataInner interface.
 */
export function instanceOfConfigTrafficControlGetTrafficControlResponseDataInner(value: object): value is ConfigTrafficControlGetTrafficControlResponseDataInner {
    
    
    
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    if (!('network' in value) || value['network'] === undefined) return false;
    
    
    
    
    
    return true;
}

export function ConfigTrafficControlGetTrafficControlResponseDataInnerFromJSON(json: any): ConfigTrafficControlGetTrafficControlResponseDataInner {
    return ConfigTrafficControlGetTrafficControlResponseDataInnerFromJSONTyped(json, false);
}

export function ConfigTrafficControlGetTrafficControlResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTrafficControlGetTrafficControlResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'burstIn': json['burst-in'] == null ? undefined : json['burst-in'],
        
        'burstOut': json['burst-out'] == null ? undefined : json['burst-out'],
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        'name': json['name'],
        
        'network': json['network'],
        
        'rateIn': json['rate-in'] == null ? undefined : json['rate-in'],
        
        'rateOut': json['rate-out'] == null ? undefined : json['rate-out'],
        
        'timeframe': json['timeframe'] == null ? undefined : json['timeframe'],
        
        'users': json['users'] == null ? undefined : json['users'],
        
    };
}

export function ConfigTrafficControlGetTrafficControlResponseDataInnerToJSON(json: any): ConfigTrafficControlGetTrafficControlResponseDataInner {
    return ConfigTrafficControlGetTrafficControlResponseDataInnerToJSONTyped(json, false);
}

export function ConfigTrafficControlGetTrafficControlResponseDataInnerToJSONTyped(value?: ConfigTrafficControlGetTrafficControlResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'burst-in': value['burstIn'],
        
        'burst-out': value['burstOut'],
        
        'comment': value['comment'],
        
        'name': value['name'],
        
        'network': value['network'],
        
        'rate-in': value['rateIn'],
        
        'rate-out': value['rateOut'],
        
        'timeframe': value['timeframe'],
        
        'users': value['users'],
        
    };
}

