/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodesTimeGetTimeResponseData } from './NodesTimeGetTimeResponseData';
import {
    NodesTimeGetTimeResponseDataFromJSON,
    NodesTimeGetTimeResponseDataFromJSONTyped,
    NodesTimeGetTimeResponseDataToJSON,
    NodesTimeGetTimeResponseDataToJSONTyped,
} from './NodesTimeGetTimeResponseData';

/**
 * 
 * @export
 * @interface NodesTimeGetTimeResponse
 */
export interface NodesTimeGetTimeResponse {

    /**
     * 
     * @type {NodesTimeGetTimeResponseData}
     * @memberof NodesTimeGetTimeResponse
     */
    data: NodesTimeGetTimeResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesTimeGetTimeResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesTimeGetTimeResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesTimeGetTimeResponse interface.
 */
export function instanceOfNodesTimeGetTimeResponse(value: object): value is NodesTimeGetTimeResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesTimeGetTimeResponseFromJSON(json: any): NodesTimeGetTimeResponse {
    return NodesTimeGetTimeResponseFromJSONTyped(json, false);
}

export function NodesTimeGetTimeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesTimeGetTimeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': NodesTimeGetTimeResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesTimeGetTimeResponseToJSON(json: any): NodesTimeGetTimeResponse {
    return NodesTimeGetTimeResponseToJSONTyped(json, false);
}

export function NodesTimeGetTimeResponseToJSONTyped(value?: NodesTimeGetTimeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': NodesTimeGetTimeResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

