/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsNodesStatusModeEnum } from './PbsNodesStatusModeEnum';
import {
    PbsNodesStatusModeEnumFromJSON,
    PbsNodesStatusModeEnumFromJSONTyped,
    PbsNodesStatusModeEnumToJSON,
    PbsNodesStatusModeEnumToJSONTyped,
} from './PbsNodesStatusModeEnum';

/**
 * Holds the Bootmodes
 * @export
 * @interface NodesStatusGetStatusResponseDataBootInfo
 */
export interface NodesStatusGetStatusResponseDataBootInfo {

    /**
     * The possible BootModes
     * @type {PbsNodesStatusModeEnum}
     * @memberof NodesStatusGetStatusResponseDataBootInfo
     */
    mode: PbsNodesStatusModeEnum;

    /**
     * SecureBoot status
     * @type {boolean}
     * @memberof NodesStatusGetStatusResponseDataBootInfo
     */
    secureboot: boolean;

}



/**
 * Check if a given object implements the NodesStatusGetStatusResponseDataBootInfo interface.
 */
export function instanceOfNodesStatusGetStatusResponseDataBootInfo(value: object): value is NodesStatusGetStatusResponseDataBootInfo {
    
    if (!('mode' in value) || value['mode'] === undefined) return false;
    
    if (!('secureboot' in value) || value['secureboot'] === undefined) return false;
    
    return true;
}

export function NodesStatusGetStatusResponseDataBootInfoFromJSON(json: any): NodesStatusGetStatusResponseDataBootInfo {
    return NodesStatusGetStatusResponseDataBootInfoFromJSONTyped(json, false);
}

export function NodesStatusGetStatusResponseDataBootInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesStatusGetStatusResponseDataBootInfo {
    if (json == null) {
        return json;
    }
    return {
        
        
        'mode': PbsNodesStatusModeEnumFromJSON(json['mode']),
        
        'secureboot': json['secureboot'],
        
    };
}

export function NodesStatusGetStatusResponseDataBootInfoToJSON(json: any): NodesStatusGetStatusResponseDataBootInfo {
    return NodesStatusGetStatusResponseDataBootInfoToJSONTyped(json, false);
}

export function NodesStatusGetStatusResponseDataBootInfoToJSONTyped(value?: NodesStatusGetStatusResponseDataBootInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'mode': PbsNodesStatusModeEnumToJSON(value['mode']),
        
        'secureboot': value['secureboot'],
        
    };
}

