/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsNodesDisksDiskTypeEnum } from './PbsNodesDisksDiskTypeEnum';
import {
    PbsNodesDisksDiskTypeEnumFromJSON,
    PbsNodesDisksDiskTypeEnumFromJSONTyped,
    PbsNodesDisksDiskTypeEnumToJSON,
    PbsNodesDisksDiskTypeEnumToJSONTyped,
} from './PbsNodesDisksDiskTypeEnum';
import type { PbsUsageTypeEnum } from './PbsUsageTypeEnum';
import {
    PbsUsageTypeEnumFromJSON,
    PbsUsageTypeEnumFromJSONTyped,
    PbsUsageTypeEnumToJSON,
    PbsUsageTypeEnumToJSONTyped,
} from './PbsUsageTypeEnum';
import type { NodesDisksGetListResponseDataInnerPartitionsInner } from './NodesDisksGetListResponseDataInnerPartitionsInner';
import {
    NodesDisksGetListResponseDataInnerPartitionsInnerFromJSON,
    NodesDisksGetListResponseDataInnerPartitionsInnerFromJSONTyped,
    NodesDisksGetListResponseDataInnerPartitionsInnerToJSON,
    NodesDisksGetListResponseDataInnerPartitionsInnerToJSONTyped,
} from './NodesDisksGetListResponseDataInnerPartitionsInner';
import type { PbsStatusEnum } from './PbsStatusEnum';
import {
    PbsStatusEnumFromJSON,
    PbsStatusEnumFromJSONTyped,
    PbsStatusEnumToJSON,
    PbsStatusEnumToJSONTyped,
} from './PbsStatusEnum';

/**
 * 
 * @export
 * @interface NodesDisksGetListResponseDataInner
 */
export interface NodesDisksGetListResponseDataInner {

    /**
     * Linux device path (/dev/xxx)
     * @type {string}
     * @memberof NodesDisksGetListResponseDataInner
     */
    devpath?: string;

    /**
     * This is just a rough estimate for a "type" of disk.
     * @type {PbsNodesDisksDiskTypeEnum}
     * @memberof NodesDisksGetListResponseDataInner
     */
    diskType: PbsNodesDisksDiskTypeEnum;

    /**
     * Set if disk contains a GPT partition table
     * @type {boolean}
     * @memberof NodesDisksGetListResponseDataInner
     */
    gpt: boolean;

    /**
     * Model
     * @type {string}
     * @memberof NodesDisksGetListResponseDataInner
     */
    model?: string;

    /**
     * Disk name (`/sys/block/<name>`)
     * @type {string}
     * @memberof NodesDisksGetListResponseDataInner
     */
    name: string;

    /**
     * Partitions on the device
     * @type {Array<NodesDisksGetListResponseDataInnerPartitionsInner>}
     * @memberof NodesDisksGetListResponseDataInner
     */
    partitions?: Array<NodesDisksGetListResponseDataInnerPartitionsInner>;

    /**
     * RPM
     * @type {number}
     * @memberof NodesDisksGetListResponseDataInner
     */
    rpm?: number;

    /**
     * Serisal number
     * @type {string}
     * @memberof NodesDisksGetListResponseDataInner
     */
    serial?: string;

    /**
     * Disk size
     * @type {number}
     * @memberof NodesDisksGetListResponseDataInner
     */
    size: number;

    /**
     * SMART status
     * @type {PbsStatusEnum}
     * @memberof NodesDisksGetListResponseDataInner
     */
    status: PbsStatusEnum;

    /**
     * What a block device (disk) is used for.
     * @type {PbsUsageTypeEnum}
     * @memberof NodesDisksGetListResponseDataInner
     */
    used: PbsUsageTypeEnum;

    /**
     * Vendor
     * @type {string}
     * @memberof NodesDisksGetListResponseDataInner
     */
    vendor?: string;

    /**
     * Disk wearout
     * @type {number}
     * @memberof NodesDisksGetListResponseDataInner
     */
    wearout?: number;

    /**
     * WWN
     * @type {string}
     * @memberof NodesDisksGetListResponseDataInner
     */
    wwn?: string;

}



/**
 * Check if a given object implements the NodesDisksGetListResponseDataInner interface.
 */
export function instanceOfNodesDisksGetListResponseDataInner(value: object): value is NodesDisksGetListResponseDataInner {
    
    
    if (!('diskType' in value) || value['diskType'] === undefined) return false;
    
    if (!('gpt' in value) || value['gpt'] === undefined) return false;
    
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    
    
    
    if (!('size' in value) || value['size'] === undefined) return false;
    
    if (!('status' in value) || value['status'] === undefined) return false;
    
    if (!('used' in value) || value['used'] === undefined) return false;
    
    
    
    
    return true;
}

export function NodesDisksGetListResponseDataInnerFromJSON(json: any): NodesDisksGetListResponseDataInner {
    return NodesDisksGetListResponseDataInnerFromJSONTyped(json, false);
}

export function NodesDisksGetListResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesDisksGetListResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'devpath': json['devpath'] == null ? undefined : json['devpath'],
        
        'diskType': PbsNodesDisksDiskTypeEnumFromJSON(json['disk-type']),
        
        'gpt': json['gpt'],
        
        'model': json['model'] == null ? undefined : json['model'],
        
        'name': json['name'],
        
        'partitions': json['partitions'] == null ? undefined : ((json['partitions'] as Array<any>).map(NodesDisksGetListResponseDataInnerPartitionsInnerFromJSON)),
        
        'rpm': json['rpm'] == null ? undefined : json['rpm'],
        
        'serial': json['serial'] == null ? undefined : json['serial'],
        
        'size': json['size'],
        
        'status': PbsStatusEnumFromJSON(json['status']),
        
        'used': PbsUsageTypeEnumFromJSON(json['used']),
        
        'vendor': json['vendor'] == null ? undefined : json['vendor'],
        
        'wearout': json['wearout'] == null ? undefined : json['wearout'],
        
        'wwn': json['wwn'] == null ? undefined : json['wwn'],
        
    };
}

export function NodesDisksGetListResponseDataInnerToJSON(json: any): NodesDisksGetListResponseDataInner {
    return NodesDisksGetListResponseDataInnerToJSONTyped(json, false);
}

export function NodesDisksGetListResponseDataInnerToJSONTyped(value?: NodesDisksGetListResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'devpath': value['devpath'],
        
        'disk-type': PbsNodesDisksDiskTypeEnumToJSON(value['diskType']),
        
        'gpt': value['gpt'],
        
        'model': value['model'],
        
        'name': value['name'],
        
        'partitions': value['partitions'] == null ? undefined : ((value['partitions'] as Array<any>).map(NodesDisksGetListResponseDataInnerPartitionsInnerToJSON)),
        
        'rpm': value['rpm'],
        
        'serial': value['serial'],
        
        'size': value['size'],
        
        'status': PbsStatusEnumToJSON(value['status']),
        
        'used': PbsUsageTypeEnumToJSON(value['used']),
        
        'vendor': value['vendor'],
        
        'wearout': value['wearout'],
        
        'wwn': value['wwn'],
        
    };
}

