/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesDisksGetSmartResponseDataAttributesInner
 */
export interface NodesDisksGetSmartResponseDataAttributesInner {

    /**
     * ATA Flags
     * @type {string}
     * @memberof NodesDisksGetSmartResponseDataAttributesInner
     */
    flags?: string;

    /**
     * ATA Attribute ID
     * @type {number}
     * @memberof NodesDisksGetSmartResponseDataAttributesInner
     */
    id?: bigint | string | number;

    /**
     * Attribute name
     * @type {string}
     * @memberof NodesDisksGetSmartResponseDataAttributesInner
     */
    name: string;

    /**
     * ATA normalized value (0..100)
     * @type {number}
     * @memberof NodesDisksGetSmartResponseDataAttributesInner
     */
    normalized?: number;

    /**
     * Attribute raw value
     * @type {string}
     * @memberof NodesDisksGetSmartResponseDataAttributesInner
     */
    raw: string;

    /**
     * ATA threshold
     * @type {number}
     * @memberof NodesDisksGetSmartResponseDataAttributesInner
     */
    threshold?: number;

    /**
     * duplicate of raw - kept for API stability
     * @type {string}
     * @memberof NodesDisksGetSmartResponseDataAttributesInner
     */
    value: string;

    /**
     * ATA worst
     * @type {number}
     * @memberof NodesDisksGetSmartResponseDataAttributesInner
     */
    worst?: number;

}

/**
 * Check if a given object implements the NodesDisksGetSmartResponseDataAttributesInner interface.
 */
export function instanceOfNodesDisksGetSmartResponseDataAttributesInner(value: object): value is NodesDisksGetSmartResponseDataAttributesInner {
    
    
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    
    if (!('raw' in value) || value['raw'] === undefined) return false;
    
    
    if (!('value' in value) || value['value'] === undefined) return false;
    
    
    return true;
}

export function NodesDisksGetSmartResponseDataAttributesInnerFromJSON(json: any): NodesDisksGetSmartResponseDataAttributesInner {
    return NodesDisksGetSmartResponseDataAttributesInnerFromJSONTyped(json, false);
}

export function NodesDisksGetSmartResponseDataAttributesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesDisksGetSmartResponseDataAttributesInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'flags': json['flags'] == null ? undefined : json['flags'],
        
        'id': json['id'] == null ? undefined : BigInt(json['id']),
        
        'name': json['name'],
        
        'normalized': json['normalized'] == null ? undefined : json['normalized'],
        
        'raw': json['raw'],
        
        'threshold': json['threshold'] == null ? undefined : json['threshold'],
        
        'value': json['value'],
        
        'worst': json['worst'] == null ? undefined : json['worst'],
        
    };
}

export function NodesDisksGetSmartResponseDataAttributesInnerToJSON(json: any): NodesDisksGetSmartResponseDataAttributesInner {
    return NodesDisksGetSmartResponseDataAttributesInnerToJSONTyped(json, false);
}

export function NodesDisksGetSmartResponseDataAttributesInnerToJSONTyped(value?: NodesDisksGetSmartResponseDataAttributesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'flags': value['flags'],
        
        'id': value['id'] == null ? undefined : String(value['id']),
        
        'name': value['name'],
        
        'normalized': value['normalized'],
        
        'raw': value['raw'],
        
        'threshold': value['threshold'],
        
        'value': value['value'],
        
        'worst': value['worst'],
        
    };
}

