/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesServicesCreateRestartResponse
 */
export interface NodesServicesCreateRestartResponse {

    /**
     * 
     * @type {any}
     * @memberof NodesServicesCreateRestartResponse
     */
    data: any | null;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesServicesCreateRestartResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesServicesCreateRestartResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesServicesCreateRestartResponse interface.
 */
export function instanceOfNodesServicesCreateRestartResponse(value: object): value is NodesServicesCreateRestartResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesServicesCreateRestartResponseFromJSON(json: any): NodesServicesCreateRestartResponse {
    return NodesServicesCreateRestartResponseFromJSONTyped(json, false);
}

export function NodesServicesCreateRestartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesServicesCreateRestartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesServicesCreateRestartResponseToJSON(json: any): NodesServicesCreateRestartResponse {
    return NodesServicesCreateRestartResponseToJSONTyped(json, false);
}

export function NodesServicesCreateRestartResponseToJSONTyped(value?: NodesServicesCreateRestartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

