/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodesNetworkGetNetworkResponseDataInner } from './NodesNetworkGetNetworkResponseDataInner';
import {
    NodesNetworkGetNetworkResponseDataInnerFromJSON,
    NodesNetworkGetNetworkResponseDataInnerFromJSONTyped,
    NodesNetworkGetNetworkResponseDataInnerToJSON,
    NodesNetworkGetNetworkResponseDataInnerToJSONTyped,
} from './NodesNetworkGetNetworkResponseDataInner';

/**
 * 
 * @export
 * @interface NodesNetworkGetNodesByNodeNetworkByIfaceResponse
 */
export interface NodesNetworkGetNodesByNodeNetworkByIfaceResponse {

    /**
     * 
     * @type {NodesNetworkGetNetworkResponseDataInner}
     * @memberof NodesNetworkGetNodesByNodeNetworkByIfaceResponse
     */
    data: NodesNetworkGetNetworkResponseDataInner;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesNetworkGetNodesByNodeNetworkByIfaceResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesNetworkGetNodesByNodeNetworkByIfaceResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesNetworkGetNodesByNodeNetworkByIfaceResponse interface.
 */
export function instanceOfNodesNetworkGetNodesByNodeNetworkByIfaceResponse(value: object): value is NodesNetworkGetNodesByNodeNetworkByIfaceResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesNetworkGetNodesByNodeNetworkByIfaceResponseFromJSON(json: any): NodesNetworkGetNodesByNodeNetworkByIfaceResponse {
    return NodesNetworkGetNodesByNodeNetworkByIfaceResponseFromJSONTyped(json, false);
}

export function NodesNetworkGetNodesByNodeNetworkByIfaceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesNetworkGetNodesByNodeNetworkByIfaceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': NodesNetworkGetNetworkResponseDataInnerFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesNetworkGetNodesByNodeNetworkByIfaceResponseToJSON(json: any): NodesNetworkGetNodesByNodeNetworkByIfaceResponse {
    return NodesNetworkGetNodesByNodeNetworkByIfaceResponseToJSONTyped(json, false);
}

export function NodesNetworkGetNodesByNodeNetworkByIfaceResponseToJSONTyped(value?: NodesNetworkGetNodesByNodeNetworkByIfaceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': NodesNetworkGetNetworkResponseDataInnerToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

