/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesCreateTermproxyResponseData
 */
export interface NodesCreateTermproxyResponseData {

    /**
     * port used to bind termproxy to
     * @type {number}
     * @memberof NodesCreateTermproxyResponseData
     */
    port: bigint | string | number;

    /**
     * ticket used to verifiy websocket connection
     * @type {string}
     * @memberof NodesCreateTermproxyResponseData
     */
    ticket: string;

    /**
     * UPID for termproxy worker task
     * @type {string}
     * @memberof NodesCreateTermproxyResponseData
     */
    upid: string;

    /**
     * user or authid encoded in the ticket
     * @type {string}
     * @memberof NodesCreateTermproxyResponseData
     */
    user: string;

}

/**
 * Check if a given object implements the NodesCreateTermproxyResponseData interface.
 */
export function instanceOfNodesCreateTermproxyResponseData(value: object): value is NodesCreateTermproxyResponseData {
    
    if (!('port' in value) || value['port'] === undefined) return false;
    
    if (!('ticket' in value) || value['ticket'] === undefined) return false;
    
    if (!('upid' in value) || value['upid'] === undefined) return false;
    
    if (!('user' in value) || value['user'] === undefined) return false;
    
    return true;
}

export function NodesCreateTermproxyResponseDataFromJSON(json: any): NodesCreateTermproxyResponseData {
    return NodesCreateTermproxyResponseDataFromJSONTyped(json, false);
}

export function NodesCreateTermproxyResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesCreateTermproxyResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'port': BigInt(json['port']),
        
        'ticket': json['ticket'],
        
        'upid': json['upid'],
        
        'user': json['user'],
        
    };
}

export function NodesCreateTermproxyResponseDataToJSON(json: any): NodesCreateTermproxyResponseData {
    return NodesCreateTermproxyResponseDataToJSONTyped(json, false);
}

export function NodesCreateTermproxyResponseDataToJSONTyped(value?: NodesCreateTermproxyResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'port': String(value['port']),
        
        'ticket': value['ticket'],
        
        'upid': value['upid'],
        
        'user': value['user'],
        
    };
}

