/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesGetJournalResponse
 */
export interface NodesGetJournalResponse {

    /**
     * 
     * @type {Array<string>}
     * @memberof NodesGetJournalResponse
     */
    data: Array<string>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesGetJournalResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesGetJournalResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesGetJournalResponse interface.
 */
export function instanceOfNodesGetJournalResponse(value: object): value is NodesGetJournalResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesGetJournalResponseFromJSON(json: any): NodesGetJournalResponse {
    return NodesGetJournalResponseFromJSONTyped(json, false);
}

export function NodesGetJournalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesGetJournalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesGetJournalResponseToJSON(json: any): NodesGetJournalResponse {
    return NodesGetJournalResponseToJSONTyped(json, false);
}

export function NodesGetJournalResponseToJSONTyped(value?: NodesGetJournalResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

