/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesCertificatesCreateCertificateRequest
 */
export interface NodesCertificatesCreateCertificateRequest {

    /**
     * Force replacement of existing files.
     * @type {boolean}
     * @memberof NodesCertificatesCreateCertificateRequest
     */
    force?: boolean;

}

/**
 * Check if a given object implements the NodesCertificatesCreateCertificateRequest interface.
 */
export function instanceOfNodesCertificatesCreateCertificateRequest(value: object): value is NodesCertificatesCreateCertificateRequest {
    
    
    return true;
}

export function NodesCertificatesCreateCertificateRequestFromJSON(json: any): NodesCertificatesCreateCertificateRequest {
    return NodesCertificatesCreateCertificateRequestFromJSONTyped(json, false);
}

export function NodesCertificatesCreateCertificateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesCertificatesCreateCertificateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'force': json['force'] == null ? undefined : json['force'],
        
    };
}

export function NodesCertificatesCreateCertificateRequestToJSON(json: any): NodesCertificatesCreateCertificateRequest {
    return NodesCertificatesCreateCertificateRequestToJSONTyped(json, false);
}

export function NodesCertificatesCreateCertificateRequestToJSONTyped(value?: NodesCertificatesCreateCertificateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'force': value['force'],
        
    };
}

