/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesAptGetUpdateResponseDataInner
 */
export interface NodesAptGetUpdateResponseDataInner {

    /**
     * Package architecture
     * @type {string}
     * @memberof NodesAptGetUpdateResponseDataInner
     */
    arch: string;

    /**
     * Human readable package description
     * @type {string}
     * @memberof NodesAptGetUpdateResponseDataInner
     */
    description: string;

    /**
     * Custom extra field for additional package information
     * @type {string}
     * @memberof NodesAptGetUpdateResponseDataInner
     */
    extraInfo?: string;

    /**
     * Old version currently installed
     * @type {string}
     * @memberof NodesAptGetUpdateResponseDataInner
     */
    oldVersion?: string;

    /**
     * Package origin
     * @type {string}
     * @memberof NodesAptGetUpdateResponseDataInner
     */
    origin: string;

    /**
     * Package name
     * @type {string}
     * @memberof NodesAptGetUpdateResponseDataInner
     */
    _package: string;

    /**
     * Package priority in human-readable form
     * @type {string}
     * @memberof NodesAptGetUpdateResponseDataInner
     */
    priority: string;

    /**
     * Package section
     * @type {string}
     * @memberof NodesAptGetUpdateResponseDataInner
     */
    section: string;

    /**
     * Package title
     * @type {string}
     * @memberof NodesAptGetUpdateResponseDataInner
     */
    title: string;

    /**
     * New version to be updated to
     * @type {string}
     * @memberof NodesAptGetUpdateResponseDataInner
     */
    version: string;

}

/**
 * Check if a given object implements the NodesAptGetUpdateResponseDataInner interface.
 */
export function instanceOfNodesAptGetUpdateResponseDataInner(value: object): value is NodesAptGetUpdateResponseDataInner {
    
    if (!('arch' in value) || value['arch'] === undefined) return false;
    
    if (!('description' in value) || value['description'] === undefined) return false;
    
    
    
    if (!('origin' in value) || value['origin'] === undefined) return false;
    
    if (!('_package' in value) || value['_package'] === undefined) return false;
    
    if (!('priority' in value) || value['priority'] === undefined) return false;
    
    if (!('section' in value) || value['section'] === undefined) return false;
    
    if (!('title' in value) || value['title'] === undefined) return false;
    
    if (!('version' in value) || value['version'] === undefined) return false;
    
    return true;
}

export function NodesAptGetUpdateResponseDataInnerFromJSON(json: any): NodesAptGetUpdateResponseDataInner {
    return NodesAptGetUpdateResponseDataInnerFromJSONTyped(json, false);
}

export function NodesAptGetUpdateResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesAptGetUpdateResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'arch': json['Arch'],
        
        'description': json['Description'],
        
        'extraInfo': json['ExtraInfo'] == null ? undefined : json['ExtraInfo'],
        
        'oldVersion': json['OldVersion'] == null ? undefined : json['OldVersion'],
        
        'origin': json['Origin'],
        
        '_package': json['Package'],
        
        'priority': json['Priority'],
        
        'section': json['Section'],
        
        'title': json['Title'],
        
        'version': json['Version'],
        
    };
}

export function NodesAptGetUpdateResponseDataInnerToJSON(json: any): NodesAptGetUpdateResponseDataInner {
    return NodesAptGetUpdateResponseDataInnerToJSONTyped(json, false);
}

export function NodesAptGetUpdateResponseDataInnerToJSONTyped(value?: NodesAptGetUpdateResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'Arch': value['arch'],
        
        'Description': value['description'],
        
        'ExtraInfo': value['extraInfo'],
        
        'OldVersion': value['oldVersion'],
        
        'Origin': value['origin'],
        
        'Package': value['_package'],
        
        'Priority': value['priority'],
        
        'Section': value['section'],
        
        'Title': value['title'],
        
        'Version': value['version'],
        
    };
}

