/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsDevicesField } from './PbsDevicesField';
import {
    PbsDevicesFieldFromJSON,
    PbsDevicesFieldFromJSONTyped,
    PbsDevicesFieldToJSON,
    PbsDevicesFieldToJSONTyped,
} from './PbsDevicesField';
import type { PbsNodesDisksRaidlevelEnum } from './PbsNodesDisksRaidlevelEnum';
import {
    PbsNodesDisksRaidlevelEnumFromJSON,
    PbsNodesDisksRaidlevelEnumFromJSONTyped,
    PbsNodesDisksRaidlevelEnumToJSON,
    PbsNodesDisksRaidlevelEnumToJSONTyped,
} from './PbsNodesDisksRaidlevelEnum';
import type { PbsNodesDisksCompressionEnum } from './PbsNodesDisksCompressionEnum';
import {
    PbsNodesDisksCompressionEnumFromJSON,
    PbsNodesDisksCompressionEnumFromJSONTyped,
    PbsNodesDisksCompressionEnumToJSON,
    PbsNodesDisksCompressionEnumToJSONTyped,
} from './PbsNodesDisksCompressionEnum';

/**
 * 
 * @export
 * @interface NodesDisksCreateZfsRequest
 */
export interface NodesDisksCreateZfsRequest {

    /**
     * Configure a datastore using the zpool.
     * @type {boolean}
     * @memberof NodesDisksCreateZfsRequest
     */
    addDatastore?: boolean;

    /**
     * Pool sector size exponent.
     * @type {number}
     * @memberof NodesDisksCreateZfsRequest
     */
    ashift?: number;

    /**
     * The ZFS compression algorithm to use.
     * @type {PbsNodesDisksCompressionEnum}
     * @memberof NodesDisksCreateZfsRequest
     */
    compression?: PbsNodesDisksCompressionEnum;

    /**
     * A list of disk names, comma separated.
     * @type {PbsDevicesField}
     * @memberof NodesDisksCreateZfsRequest
     */
    devices: PbsDevicesField;

    /**
     * Datastore name.
     * @type {string}
     * @memberof NodesDisksCreateZfsRequest
     */
    name: string;

    /**
     * The ZFS RAID level to use.
     * @type {PbsNodesDisksRaidlevelEnum}
     * @memberof NodesDisksCreateZfsRequest
     */
    raidlevel: PbsNodesDisksRaidlevelEnum;

}



/**
 * Check if a given object implements the NodesDisksCreateZfsRequest interface.
 */
export function instanceOfNodesDisksCreateZfsRequest(value: object): value is NodesDisksCreateZfsRequest {
    
    
    
    
    if (!('devices' in value) || value['devices'] === undefined) return false;
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    if (!('raidlevel' in value) || value['raidlevel'] === undefined) return false;
    
    return true;
}

export function NodesDisksCreateZfsRequestFromJSON(json: any): NodesDisksCreateZfsRequest {
    return NodesDisksCreateZfsRequestFromJSONTyped(json, false);
}

export function NodesDisksCreateZfsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesDisksCreateZfsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'addDatastore': json['add-datastore'] == null ? undefined : json['add-datastore'],
        
        'ashift': json['ashift'] == null ? undefined : json['ashift'],
        
        'compression': json['compression'] == null ? undefined : PbsNodesDisksCompressionEnumFromJSON(json['compression']),
        
        'devices': PbsDevicesFieldFromJSON(json['devices']),
        
        'name': json['name'],
        
        'raidlevel': PbsNodesDisksRaidlevelEnumFromJSON(json['raidlevel']),
        
    };
}

export function NodesDisksCreateZfsRequestToJSON(json: any): NodesDisksCreateZfsRequest {
    return NodesDisksCreateZfsRequestToJSONTyped(json, false);
}

export function NodesDisksCreateZfsRequestToJSONTyped(value?: NodesDisksCreateZfsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'add-datastore': value['addDatastore'],
        
        'ashift': value['ashift'],
        
        'compression': PbsNodesDisksCompressionEnumToJSON(value['compression']),
        
        'devices': PbsDevicesFieldToJSON(value['devices']),
        
        'name': value['name'],
        
        'raidlevel': PbsNodesDisksRaidlevelEnumToJSON(value['raidlevel']),
        
    };
}

