/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Storage space usage information.
 * @export
 * @interface NodesStatusGetStatusResponseDataRoot
 */
export interface NodesStatusGetStatusResponseDataRoot {

    /**
     * Available space (bytes).
     * @type {number}
     * @memberof NodesStatusGetStatusResponseDataRoot
     */
    avail: bigint | string | number;

    /**
     * Total space (bytes).
     * @type {number}
     * @memberof NodesStatusGetStatusResponseDataRoot
     */
    total: bigint | string | number;

    /**
     * Used space (bytes).
     * @type {number}
     * @memberof NodesStatusGetStatusResponseDataRoot
     */
    used: bigint | string | number;

}

/**
 * Check if a given object implements the NodesStatusGetStatusResponseDataRoot interface.
 */
export function instanceOfNodesStatusGetStatusResponseDataRoot(value: object): value is NodesStatusGetStatusResponseDataRoot {
    
    if (!('avail' in value) || value['avail'] === undefined) return false;
    
    if (!('total' in value) || value['total'] === undefined) return false;
    
    if (!('used' in value) || value['used'] === undefined) return false;
    
    return true;
}

export function NodesStatusGetStatusResponseDataRootFromJSON(json: any): NodesStatusGetStatusResponseDataRoot {
    return NodesStatusGetStatusResponseDataRootFromJSONTyped(json, false);
}

export function NodesStatusGetStatusResponseDataRootFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesStatusGetStatusResponseDataRoot {
    if (json == null) {
        return json;
    }
    return {
        
        
        'avail': BigInt(json['avail']),
        
        'total': BigInt(json['total']),
        
        'used': BigInt(json['used']),
        
    };
}

export function NodesStatusGetStatusResponseDataRootToJSON(json: any): NodesStatusGetStatusResponseDataRoot {
    return NodesStatusGetStatusResponseDataRootToJSONTyped(json, false);
}

export function NodesStatusGetStatusResponseDataRootToJSONTyped(value?: NodesStatusGetStatusResponseDataRoot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'avail': String(value['avail']),
        
        'total': String(value['total']),
        
        'used': String(value['used']),
        
    };
}

