/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PbsConfigNotificationsInlineEnum = {
    Comment: 'comment',
    Disable: 'disable'
} as const;
export type PbsConfigNotificationsInlineEnum = typeof PbsConfigNotificationsInlineEnum[keyof typeof PbsConfigNotificationsInlineEnum];


export function instanceOfPbsConfigNotificationsInlineEnum(value: any): boolean {
    for (const key in PbsConfigNotificationsInlineEnum) {
        if (Object.prototype.hasOwnProperty.call(PbsConfigNotificationsInlineEnum, key)) {
            if (PbsConfigNotificationsInlineEnum[key as keyof typeof PbsConfigNotificationsInlineEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PbsConfigNotificationsInlineEnumFromJSON(json: any): PbsConfigNotificationsInlineEnum {
    return PbsConfigNotificationsInlineEnumFromJSONTyped(json, false);
}

export function PbsConfigNotificationsInlineEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsConfigNotificationsInlineEnum {

    return json as PbsConfigNotificationsInlineEnum;

}

export function PbsConfigNotificationsInlineEnumToJSON(value?: PbsConfigNotificationsInlineEnum | null): any {
    return value as any;
}

export function PbsConfigNotificationsInlineEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PbsConfigNotificationsInlineEnum {
    return value as PbsConfigNotificationsInlineEnum;
}

