/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PbsConfigPruneInlineEnum = {
    Comment: 'comment',
    Disable: 'disable',
    Ns: 'ns',
    MaxDepth: 'max-depth',
    KeepLast: 'keep-last',
    KeepHourly: 'keep-hourly',
    KeepDaily: 'keep-daily',
    KeepWeekly: 'keep-weekly',
    KeepMonthly: 'keep-monthly',
    KeepYearly: 'keep-yearly'
} as const;
export type PbsConfigPruneInlineEnum = typeof PbsConfigPruneInlineEnum[keyof typeof PbsConfigPruneInlineEnum];


export function instanceOfPbsConfigPruneInlineEnum(value: any): boolean {
    for (const key in PbsConfigPruneInlineEnum) {
        if (Object.prototype.hasOwnProperty.call(PbsConfigPruneInlineEnum, key)) {
            if (PbsConfigPruneInlineEnum[key as keyof typeof PbsConfigPruneInlineEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PbsConfigPruneInlineEnumFromJSON(json: any): PbsConfigPruneInlineEnum {
    return PbsConfigPruneInlineEnumFromJSONTyped(json, false);
}

export function PbsConfigPruneInlineEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsConfigPruneInlineEnum {
    return json as PbsConfigPruneInlineEnum;
}

export function PbsConfigPruneInlineEnumToJSON(value?: PbsConfigPruneInlineEnum | null): any {
    return value as any;
}

export function PbsConfigPruneInlineEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PbsConfigPruneInlineEnum {
    return value as PbsConfigPruneInlineEnum;
}

