/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PbsConfigAccessInlineEnum = {
    ClientKey: 'client-key',
    Comment: 'comment',
    Default: 'default',
    Autocreate: 'autocreate',
    Scopes: 'scopes',
    Prompt: 'prompt',
    AcrValues: 'acr-values'
} as const;
export type PbsConfigAccessInlineEnum = typeof PbsConfigAccessInlineEnum[keyof typeof PbsConfigAccessInlineEnum];


export function instanceOfPbsConfigAccessInlineEnum(value: any): boolean {
    for (const key in PbsConfigAccessInlineEnum) {
        if (Object.prototype.hasOwnProperty.call(PbsConfigAccessInlineEnum, key)) {
            if (PbsConfigAccessInlineEnum[key as keyof typeof PbsConfigAccessInlineEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PbsConfigAccessInlineEnumFromJSON(json: any): PbsConfigAccessInlineEnum {
    return PbsConfigAccessInlineEnumFromJSONTyped(json, false);
}

export function PbsConfigAccessInlineEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsConfigAccessInlineEnum {
    return json as PbsConfigAccessInlineEnum;
}

export function PbsConfigAccessInlineEnumToJSON(value?: PbsConfigAccessInlineEnum | null): any {
    return value as any;
}

export function PbsConfigAccessInlineEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PbsConfigAccessInlineEnum {
    return value as PbsConfigAccessInlineEnum;
}

