/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PbsConfigChangerInlineEnum = {
    ExportSlots: 'export-slots',
    EjectBeforeUnload: 'eject-before-unload'
} as const;
export type PbsConfigChangerInlineEnum = typeof PbsConfigChangerInlineEnum[keyof typeof PbsConfigChangerInlineEnum];


export function instanceOfPbsConfigChangerInlineEnum(value: any): boolean {
    for (const key in PbsConfigChangerInlineEnum) {
        if (Object.prototype.hasOwnProperty.call(PbsConfigChangerInlineEnum, key)) {
            if (PbsConfigChangerInlineEnum[key as keyof typeof PbsConfigChangerInlineEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PbsConfigChangerInlineEnumFromJSON(json: any): PbsConfigChangerInlineEnum {
    return PbsConfigChangerInlineEnumFromJSONTyped(json, false);
}

export function PbsConfigChangerInlineEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsConfigChangerInlineEnum {

    return json as PbsConfigChangerInlineEnum;

}

export function PbsConfigChangerInlineEnumToJSON(value?: PbsConfigChangerInlineEnum | null): any {
    return value as any;
}

export function PbsConfigChangerInlineEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PbsConfigChangerInlineEnum {
    return value as PbsConfigChangerInlineEnum;
}

