/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PbsConfigNotificationsTypeEnum = {
    Sendmail: 'sendmail',
    Smtp: 'smtp',
    Gotify: 'gotify',
    Webhook: 'webhook'
} as const;
export type PbsConfigNotificationsTypeEnum = typeof PbsConfigNotificationsTypeEnum[keyof typeof PbsConfigNotificationsTypeEnum];


export function instanceOfPbsConfigNotificationsTypeEnum(value: any): boolean {
    for (const key in PbsConfigNotificationsTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(PbsConfigNotificationsTypeEnum, key)) {
            if (PbsConfigNotificationsTypeEnum[key as keyof typeof PbsConfigNotificationsTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PbsConfigNotificationsTypeEnumFromJSON(json: any): PbsConfigNotificationsTypeEnum {
    return PbsConfigNotificationsTypeEnumFromJSONTyped(json, false);
}

export function PbsConfigNotificationsTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsConfigNotificationsTypeEnum {

    return json as PbsConfigNotificationsTypeEnum;

}

export function PbsConfigNotificationsTypeEnumToJSON(value?: PbsConfigNotificationsTypeEnum | null): any {
    return value as any;
}

export function PbsConfigNotificationsTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PbsConfigNotificationsTypeEnum {
    return value as PbsConfigNotificationsTypeEnum;
}

