/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PbsConfigDriveInlineEnum = {
    Changer: 'changer',
    ChangerDrivenum: 'changer-drivenum'
} as const;
export type PbsConfigDriveInlineEnum = typeof PbsConfigDriveInlineEnum[keyof typeof PbsConfigDriveInlineEnum];


export function instanceOfPbsConfigDriveInlineEnum(value: any): boolean {
    for (const key in PbsConfigDriveInlineEnum) {
        if (Object.prototype.hasOwnProperty.call(PbsConfigDriveInlineEnum, key)) {
            if (PbsConfigDriveInlineEnum[key as keyof typeof PbsConfigDriveInlineEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PbsConfigDriveInlineEnumFromJSON(json: any): PbsConfigDriveInlineEnum {
    return PbsConfigDriveInlineEnumFromJSONTyped(json, false);
}

export function PbsConfigDriveInlineEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsConfigDriveInlineEnum {
    return json as PbsConfigDriveInlineEnum;
}

export function PbsConfigDriveInlineEnumToJSON(value?: PbsConfigDriveInlineEnum | null): any {
    return value as any;
}

export function PbsConfigDriveInlineEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PbsConfigDriveInlineEnum {
    return value as PbsConfigDriveInlineEnum;
}

