/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PbsConfigNotificationsInlineEnum5 = {
    Comment: 'comment',
    Disable: 'disable',
    InvertMatch: 'invert-match',
    MatchCalendar: 'match-calendar',
    MatchField: 'match-field',
    MatchSeverity: 'match-severity',
    Mode: 'mode',
    Target: 'target'
} as const;
export type PbsConfigNotificationsInlineEnum5 = typeof PbsConfigNotificationsInlineEnum5[keyof typeof PbsConfigNotificationsInlineEnum5];


export function instanceOfPbsConfigNotificationsInlineEnum5(value: any): boolean {
    for (const key in PbsConfigNotificationsInlineEnum5) {
        if (Object.prototype.hasOwnProperty.call(PbsConfigNotificationsInlineEnum5, key)) {
            if (PbsConfigNotificationsInlineEnum5[key as keyof typeof PbsConfigNotificationsInlineEnum5] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PbsConfigNotificationsInlineEnum5FromJSON(json: any): PbsConfigNotificationsInlineEnum5 {
    return PbsConfigNotificationsInlineEnum5FromJSONTyped(json, false);
}

export function PbsConfigNotificationsInlineEnum5FromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsConfigNotificationsInlineEnum5 {
    return json as PbsConfigNotificationsInlineEnum5;
}

export function PbsConfigNotificationsInlineEnum5ToJSON(value?: PbsConfigNotificationsInlineEnum5 | null): any {
    return value as any;
}

export function PbsConfigNotificationsInlineEnum5ToJSONTyped(value: any, ignoreDiscriminator: boolean): PbsConfigNotificationsInlineEnum5 {
    return value as PbsConfigNotificationsInlineEnum5;
}

