/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PbsConfigNotificationsInlineEnum2 = {
    Author: 'author',
    Comment: 'comment',
    Disable: 'disable',
    FromAddress: 'from-address',
    Mailto: 'mailto',
    MailtoUser: 'mailto-user'
} as const;
export type PbsConfigNotificationsInlineEnum2 = typeof PbsConfigNotificationsInlineEnum2[keyof typeof PbsConfigNotificationsInlineEnum2];


export function instanceOfPbsConfigNotificationsInlineEnum2(value: any): boolean {
    for (const key in PbsConfigNotificationsInlineEnum2) {
        if (Object.prototype.hasOwnProperty.call(PbsConfigNotificationsInlineEnum2, key)) {
            if (PbsConfigNotificationsInlineEnum2[key as keyof typeof PbsConfigNotificationsInlineEnum2] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PbsConfigNotificationsInlineEnum2FromJSON(json: any): PbsConfigNotificationsInlineEnum2 {
    return PbsConfigNotificationsInlineEnum2FromJSONTyped(json, false);
}

export function PbsConfigNotificationsInlineEnum2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsConfigNotificationsInlineEnum2 {

    return json as PbsConfigNotificationsInlineEnum2;

}

export function PbsConfigNotificationsInlineEnum2ToJSON(value?: PbsConfigNotificationsInlineEnum2 | null): any {
    return value as any;
}

export function PbsConfigNotificationsInlineEnum2ToJSONTyped(value: any, ignoreDiscriminator: boolean): PbsConfigNotificationsInlineEnum2 {
    return value as PbsConfigNotificationsInlineEnum2;
}

