/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PbsConfigMediaPoolInlineEnum = {
    Allocation: 'allocation',
    Retention: 'retention',
    Template: 'template',
    Encrypt: 'encrypt',
    Comment: 'comment'
} as const;
export type PbsConfigMediaPoolInlineEnum = typeof PbsConfigMediaPoolInlineEnum[keyof typeof PbsConfigMediaPoolInlineEnum];


export function instanceOfPbsConfigMediaPoolInlineEnum(value: any): boolean {
    for (const key in PbsConfigMediaPoolInlineEnum) {
        if (Object.prototype.hasOwnProperty.call(PbsConfigMediaPoolInlineEnum, key)) {
            if (PbsConfigMediaPoolInlineEnum[key as keyof typeof PbsConfigMediaPoolInlineEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PbsConfigMediaPoolInlineEnumFromJSON(json: any): PbsConfigMediaPoolInlineEnum {
    return PbsConfigMediaPoolInlineEnumFromJSONTyped(json, false);
}

export function PbsConfigMediaPoolInlineEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsConfigMediaPoolInlineEnum {

    return json as PbsConfigMediaPoolInlineEnum;

}

export function PbsConfigMediaPoolInlineEnumToJSON(value?: PbsConfigMediaPoolInlineEnum | null): any {
    return value as any;
}

export function PbsConfigMediaPoolInlineEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PbsConfigMediaPoolInlineEnum {
    return value as PbsConfigMediaPoolInlineEnum;
}

