/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PbsMaintenanceConfig } from './PbsMaintenanceConfig';
import {
    instanceOfPbsMaintenanceConfig,
    PbsMaintenanceConfigFromJSON,
    PbsMaintenanceConfigFromJSONTyped,
    PbsMaintenanceConfigToJSON,
} from './PbsMaintenanceConfig';

/**
 * @type PbsMaintenanceField
 * 
 * @export
 */
export type PbsMaintenanceField = PbsMaintenanceConfig | string;

export function PbsMaintenanceFieldFromJSON(json: any): PbsMaintenanceField {
    return PbsMaintenanceFieldFromJSONTyped(json, false);
}

export function PbsMaintenanceFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsMaintenanceField {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfPbsMaintenanceConfig(json)) {
        return PbsMaintenanceConfigFromJSONTyped(json, true);
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function PbsMaintenanceFieldToJSON(json: any): any {
    return PbsMaintenanceFieldToJSONTyped(json, false);
}

export function PbsMaintenanceFieldToJSONTyped(value?: PbsMaintenanceField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPbsMaintenanceConfig(value)) {
        return PbsMaintenanceConfigToJSON(value as PbsMaintenanceConfig);
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

