/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PbsNodesConfigInlineEnum = {
    Acme: 'acme',
    Acmedomain0: 'acmedomain0',
    Acmedomain1: 'acmedomain1',
    Acmedomain2: 'acmedomain2',
    Acmedomain3: 'acmedomain3',
    Acmedomain4: 'acmedomain4',
    HttpProxy: 'http-proxy',
    EmailFrom: 'email-from',
    CiphersTls13: 'ciphers-tls-1.3',
    CiphersTls12: 'ciphers-tls-1.2',
    DefaultLang: 'default-lang',
    Description: 'description',
    TaskLogMaxDays: 'task-log-max-days',
    ConsentText: 'consent-text'
} as const;
export type PbsNodesConfigInlineEnum = typeof PbsNodesConfigInlineEnum[keyof typeof PbsNodesConfigInlineEnum];


export function instanceOfPbsNodesConfigInlineEnum(value: any): boolean {
    for (const key in PbsNodesConfigInlineEnum) {
        if (Object.prototype.hasOwnProperty.call(PbsNodesConfigInlineEnum, key)) {
            if (PbsNodesConfigInlineEnum[key as keyof typeof PbsNodesConfigInlineEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PbsNodesConfigInlineEnumFromJSON(json: any): PbsNodesConfigInlineEnum {
    return PbsNodesConfigInlineEnumFromJSONTyped(json, false);
}

export function PbsNodesConfigInlineEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsNodesConfigInlineEnum {
    return json as PbsNodesConfigInlineEnum;
}

export function PbsNodesConfigInlineEnumToJSON(value?: PbsNodesConfigInlineEnum | null): any {
    return value as any;
}

export function PbsNodesConfigInlineEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PbsNodesConfigInlineEnum {
    return value as PbsNodesConfigInlineEnum;
}

