/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PbsScopesConfig
 */
export interface PbsScopesConfig {

    /**
     * 
     * @type {any}
     * @memberof PbsScopesConfig
     */
    description: any | null;

    /**
     * OpenID Scope Name.
     * @type {string}
     * @memberof PbsScopesConfig
     */
    items: string;

    /**
     * 
     * @type {any}
     * @memberof PbsScopesConfig
     */
    type: any | null;

}

/**
 * Check if a given object implements the PbsScopesConfig interface.
 */
export function instanceOfPbsScopesConfig(value: object): value is PbsScopesConfig {
    
    if (!('description' in value) || value['description'] === undefined) return false;
    
    if (!('items' in value) || value['items'] === undefined) return false;
    
    if (!('type' in value) || value['type'] === undefined) return false;
    
    return true;
}

export function PbsScopesConfigFromJSON(json: any): PbsScopesConfig {
    return PbsScopesConfigFromJSONTyped(json, false);
}

export function PbsScopesConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsScopesConfig {
    if (json == null) {
        return json;
    }
    return {
        
        
        'description': json['description'],
        
        'items': json['items'],
        
        'type': json['type'],
        
    };
}

export function PbsScopesConfigToJSON(json: any): PbsScopesConfig {
    return PbsScopesConfigToJSONTyped(json, false);
}

export function PbsScopesConfigToJSONTyped(value?: PbsScopesConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'description': value['description'],
        
        'items': value['items'],
        
        'type': value['type'],
        
    };
}

