/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PbsTapeChangerEntryKindEnum = {
    Drive: 'drive',
    Slot: 'slot',
    ImportExport: 'import-export'
} as const;
export type PbsTapeChangerEntryKindEnum = typeof PbsTapeChangerEntryKindEnum[keyof typeof PbsTapeChangerEntryKindEnum];


export function instanceOfPbsTapeChangerEntryKindEnum(value: any): boolean {
    for (const key in PbsTapeChangerEntryKindEnum) {
        if (Object.prototype.hasOwnProperty.call(PbsTapeChangerEntryKindEnum, key)) {
            if (PbsTapeChangerEntryKindEnum[key as keyof typeof PbsTapeChangerEntryKindEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PbsTapeChangerEntryKindEnumFromJSON(json: any): PbsTapeChangerEntryKindEnum {
    return PbsTapeChangerEntryKindEnumFromJSONTyped(json, false);
}

export function PbsTapeChangerEntryKindEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbsTapeChangerEntryKindEnum {

    return json as PbsTapeChangerEntryKindEnum;

}

export function PbsTapeChangerEntryKindEnumToJSON(value?: PbsTapeChangerEntryKindEnum | null): any {
    return value as any;
}

export function PbsTapeChangerEntryKindEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PbsTapeChangerEntryKindEnum {
    return value as PbsTapeChangerEntryKindEnum;
}

