/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsMountStatusEnum } from './PbsMountStatusEnum';
import {
    PbsMountStatusEnumFromJSON,
    PbsMountStatusEnumFromJSONTyped,
    PbsMountStatusEnumToJSON,
    PbsMountStatusEnumToJSONTyped,
} from './PbsMountStatusEnum';
import type { AdminDatastoreGetStatusResponseDataGcStatus } from './AdminDatastoreGetStatusResponseDataGcStatus';
import {
    AdminDatastoreGetStatusResponseDataGcStatusFromJSON,
    AdminDatastoreGetStatusResponseDataGcStatusFromJSONTyped,
    AdminDatastoreGetStatusResponseDataGcStatusToJSON,
    AdminDatastoreGetStatusResponseDataGcStatusToJSONTyped,
} from './AdminDatastoreGetStatusResponseDataGcStatus';
import type { PbsBackendTypeEnum } from './PbsBackendTypeEnum';
import {
    PbsBackendTypeEnumFromJSON,
    PbsBackendTypeEnumFromJSONTyped,
    PbsBackendTypeEnumToJSON,
    PbsBackendTypeEnumToJSONTyped,
} from './PbsBackendTypeEnum';

/**
 * 
 * @export
 * @interface StatusGetDatastoreUsageResponseDataInner
 */
export interface StatusGetDatastoreUsageResponseDataInner {

    /**
     * The available bytes of the underlying storage. (-1 on error)
     * @type {number}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    avail?: number;

    /**
     * Datastore backend type
     * @type {PbsBackendTypeEnum}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    backendType: PbsBackendTypeEnum;

    /**
     * An error description, for example, when the datastore could not be looked up
     * @type {string}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    error?: string;

    /**
     * Estimation of the UNIX epoch when the storage will be full.
     * It's calculated via a simple Linear Regression (Least Squares) over the RRD data of the
     * last Month. Missing if not enough data points are available yet. An estimate in the past
     * means that usage is declining or not changing.
     * @type {number}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    estimatedFullDate?: number;

    /**
     * 
     * @type {AdminDatastoreGetStatusResponseDataGcStatus}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    gcStatus?: AdminDatastoreGetStatusResponseDataGcStatus;

    /**
     * A list of usages of the past (last Month).
     * @type {Array<number>}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    history?: Array<number>;

    /**
     * History resolution (seconds)
     * @type {number}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    historyDelta?: number;

    /**
     * History start time (epoch)
     * @type {number}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    historyStart?: number;

    /**
     * Current mounting status of a datastore, useful for removable datastores.
     * @type {PbsMountStatusEnum}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    mountStatus: PbsMountStatusEnum;

    /**
     * Datastore name.
     * @type {string}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    store: string;

    /**
     * The Size of the underlying storage in bytes.
     * @type {number}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    total?: number;

    /**
     * The used bytes of the underlying storage.
     * @type {number}
     * @memberof StatusGetDatastoreUsageResponseDataInner
     */
    used?: number;

}



/**
 * Check if a given object implements the StatusGetDatastoreUsageResponseDataInner interface.
 */
export function instanceOfStatusGetDatastoreUsageResponseDataInner(value: object): value is StatusGetDatastoreUsageResponseDataInner {
    
    
    if (!('backendType' in value) || value['backendType'] === undefined) return false;
    
    
    
    
    
    
    
    if (!('mountStatus' in value) || value['mountStatus'] === undefined) return false;
    
    if (!('store' in value) || value['store'] === undefined) return false;
    
    
    
    return true;
}

export function StatusGetDatastoreUsageResponseDataInnerFromJSON(json: any): StatusGetDatastoreUsageResponseDataInner {
    return StatusGetDatastoreUsageResponseDataInnerFromJSONTyped(json, false);
}

export function StatusGetDatastoreUsageResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusGetDatastoreUsageResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'avail': json['avail'] == null ? undefined : json['avail'],
        
        'backendType': PbsBackendTypeEnumFromJSON(json['backend-type']),
        
        'error': json['error'] == null ? undefined : json['error'],
        
        'estimatedFullDate': json['estimated-full-date'] == null ? undefined : json['estimated-full-date'],
        
        'gcStatus': json['gc-status'] == null ? undefined : AdminDatastoreGetStatusResponseDataGcStatusFromJSON(json['gc-status']),
        
        'history': json['history'] == null ? undefined : json['history'],
        
        'historyDelta': json['history-delta'] == null ? undefined : json['history-delta'],
        
        'historyStart': json['history-start'] == null ? undefined : json['history-start'],
        
        'mountStatus': PbsMountStatusEnumFromJSON(json['mount-status']),
        
        'store': json['store'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'used': json['used'] == null ? undefined : json['used'],
        
    };
}

export function StatusGetDatastoreUsageResponseDataInnerToJSON(json: any): StatusGetDatastoreUsageResponseDataInner {
    return StatusGetDatastoreUsageResponseDataInnerToJSONTyped(json, false);
}

export function StatusGetDatastoreUsageResponseDataInnerToJSONTyped(value?: StatusGetDatastoreUsageResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'avail': value['avail'],
        
        'backend-type': PbsBackendTypeEnumToJSON(value['backendType']),
        
        'error': value['error'],
        
        'estimated-full-date': value['estimatedFullDate'],
        
        'gc-status': AdminDatastoreGetStatusResponseDataGcStatusToJSON(value['gcStatus']),
        
        'history': value['history'],
        
        'history-delta': value['historyDelta'],
        
        'history-start': value['historyStart'],
        
        'mount-status': PbsMountStatusEnumToJSON(value['mountStatus']),
        
        'store': value['store'],
        
        'total': value['total'],
        
        'used': value['used'],
        
    };
}

