/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TapeMediaGetContentResponseDataInner
 */
export interface TapeMediaGetContentResponseDataInner {

    /**
     * Snapshot creation time (epoch)
     * @type {number}
     * @memberof TapeMediaGetContentResponseDataInner
     */
    backupTime: number;

    /**
     * Media label text (or Barcode)
     * @type {string}
     * @memberof TapeMediaGetContentResponseDataInner
     */
    labelText: string;

    /**
     * MediaSet Creation time stamp
     * @type {number}
     * @memberof TapeMediaGetContentResponseDataInner
     */
    mediaSetCtime: number;

    /**
     * Media set name
     * @type {string}
     * @memberof TapeMediaGetContentResponseDataInner
     */
    mediaSetName: string;

    /**
     * MediaSet Uuid (We use the all-zero Uuid to reserve an empty media for a specific pool).
     * @type {string}
     * @memberof TapeMediaGetContentResponseDataInner
     */
    mediaSetUuid: string;

    /**
     * Media Pool
     * @type {string}
     * @memberof TapeMediaGetContentResponseDataInner
     */
    pool: string;

    /**
     * Media set seq_nr
     * @type {number}
     * @memberof TapeMediaGetContentResponseDataInner
     */
    seqNr: number;

    /**
     * Backup snapshot
     * @type {string}
     * @memberof TapeMediaGetContentResponseDataInner
     */
    snapshot: string;

    /**
     * Datastore Name
     * @type {string}
     * @memberof TapeMediaGetContentResponseDataInner
     */
    store: string;

    /**
     * Media Uuid.
     * @type {string}
     * @memberof TapeMediaGetContentResponseDataInner
     */
    uuid: string;

}

/**
 * Check if a given object implements the TapeMediaGetContentResponseDataInner interface.
 */
export function instanceOfTapeMediaGetContentResponseDataInner(value: object): value is TapeMediaGetContentResponseDataInner {
    
    if (!('backupTime' in value) || value['backupTime'] === undefined) return false;
    
    if (!('labelText' in value) || value['labelText'] === undefined) return false;
    
    if (!('mediaSetCtime' in value) || value['mediaSetCtime'] === undefined) return false;
    
    if (!('mediaSetName' in value) || value['mediaSetName'] === undefined) return false;
    
    if (!('mediaSetUuid' in value) || value['mediaSetUuid'] === undefined) return false;
    
    if (!('pool' in value) || value['pool'] === undefined) return false;
    
    if (!('seqNr' in value) || value['seqNr'] === undefined) return false;
    
    if (!('snapshot' in value) || value['snapshot'] === undefined) return false;
    
    if (!('store' in value) || value['store'] === undefined) return false;
    
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    
    return true;
}

export function TapeMediaGetContentResponseDataInnerFromJSON(json: any): TapeMediaGetContentResponseDataInner {
    return TapeMediaGetContentResponseDataInnerFromJSONTyped(json, false);
}

export function TapeMediaGetContentResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TapeMediaGetContentResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'backupTime': json['backup-time'],
        
        'labelText': json['label-text'],
        
        'mediaSetCtime': json['media-set-ctime'],
        
        'mediaSetName': json['media-set-name'],
        
        'mediaSetUuid': json['media-set-uuid'],
        
        'pool': json['pool'],
        
        'seqNr': json['seq-nr'],
        
        'snapshot': json['snapshot'],
        
        'store': json['store'],
        
        'uuid': json['uuid'],
        
    };
}

export function TapeMediaGetContentResponseDataInnerToJSON(json: any): TapeMediaGetContentResponseDataInner {
    return TapeMediaGetContentResponseDataInnerToJSONTyped(json, false);
}

export function TapeMediaGetContentResponseDataInnerToJSONTyped(value?: TapeMediaGetContentResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'backup-time': value['backupTime'],
        
        'label-text': value['labelText'],
        
        'media-set-ctime': value['mediaSetCtime'],
        
        'media-set-name': value['mediaSetName'],
        
        'media-set-uuid': value['mediaSetUuid'],
        
        'pool': value['pool'],
        
        'seq-nr': value['seqNr'],
        
        'snapshot': value['snapshot'],
        
        'store': value['store'],
        
        'uuid': value['uuid'],
        
    };
}

