/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsTapeChangerEntryKindEnum } from './PbsTapeChangerEntryKindEnum';
import {
    PbsTapeChangerEntryKindEnumFromJSON,
    PbsTapeChangerEntryKindEnumFromJSONTyped,
    PbsTapeChangerEntryKindEnumToJSON,
    PbsTapeChangerEntryKindEnumToJSONTyped,
} from './PbsTapeChangerEntryKindEnum';

/**
 * 
 * @export
 * @interface TapeChangerGetStatusResponseDataInner
 */
export interface TapeChangerGetStatusResponseDataInner {

    /**
     * The ID of the slot or drive
     * @type {number}
     * @memberof TapeChangerGetStatusResponseDataInner
     */
    entryId: bigint | string | number;

    /**
     * Mtx Entry Kind
     * @type {PbsTapeChangerEntryKindEnum}
     * @memberof TapeChangerGetStatusResponseDataInner
     */
    entryKind: PbsTapeChangerEntryKindEnum;

    /**
     * Media Label/Barcode.
     * @type {string}
     * @memberof TapeChangerGetStatusResponseDataInner
     */
    labelText?: string;

    /**
     * The slot the drive was loaded from
     * @type {number}
     * @memberof TapeChangerGetStatusResponseDataInner
     */
    loadedSlot?: bigint | string | number;

    /**
     * The current state of the drive
     * @type {string}
     * @memberof TapeChangerGetStatusResponseDataInner
     */
    state?: string;

}



/**
 * Check if a given object implements the TapeChangerGetStatusResponseDataInner interface.
 */
export function instanceOfTapeChangerGetStatusResponseDataInner(value: object): value is TapeChangerGetStatusResponseDataInner {
    
    if (!('entryId' in value) || value['entryId'] === undefined) return false;
    
    if (!('entryKind' in value) || value['entryKind'] === undefined) return false;
    
    
    
    
    return true;
}

export function TapeChangerGetStatusResponseDataInnerFromJSON(json: any): TapeChangerGetStatusResponseDataInner {
    return TapeChangerGetStatusResponseDataInnerFromJSONTyped(json, false);
}

export function TapeChangerGetStatusResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TapeChangerGetStatusResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'entryId': BigInt(json['entry-id']),
        
        'entryKind': PbsTapeChangerEntryKindEnumFromJSON(json['entry-kind']),
        
        'labelText': json['label-text'] == null ? undefined : json['label-text'],
        
        'loadedSlot': json['loaded-slot'] == null ? undefined : BigInt(json['loaded-slot']),
        
        'state': json['state'] == null ? undefined : json['state'],
        
    };
}

export function TapeChangerGetStatusResponseDataInnerToJSON(json: any): TapeChangerGetStatusResponseDataInner {
    return TapeChangerGetStatusResponseDataInnerToJSONTyped(json, false);
}

export function TapeChangerGetStatusResponseDataInnerToJSONTyped(value?: TapeChangerGetStatusResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'entry-id': String(value['entryId']),
        
        'entry-kind': PbsTapeChangerEntryKindEnumToJSON(value['entryKind']),
        
        'label-text': value['labelText'],
        
        'loaded-slot': value['loadedSlot'] == null ? undefined : String(value['loadedSlot']),
        
        'state': value['state'],
        
    };
}

