/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsNotificationModeEnum } from './PbsNotificationModeEnum';
import {
    PbsNotificationModeEnumFromJSON,
    PbsNotificationModeEnumFromJSONTyped,
    PbsNotificationModeEnumToJSON,
    PbsNotificationModeEnumToJSONTyped,
} from './PbsNotificationModeEnum';
import type { PbsStoreField } from './PbsStoreField';
import {
    PbsStoreFieldFromJSON,
    PbsStoreFieldFromJSONTyped,
    PbsStoreFieldToJSON,
    PbsStoreFieldToJSONTyped,
} from './PbsStoreField';
import type { TapeCreateRestoreRequestNamespacesInner } from './TapeCreateRestoreRequestNamespacesInner';
import {
    TapeCreateRestoreRequestNamespacesInnerFromJSON,
    TapeCreateRestoreRequestNamespacesInnerFromJSONTyped,
    TapeCreateRestoreRequestNamespacesInnerToJSON,
    TapeCreateRestoreRequestNamespacesInnerToJSONTyped,
} from './TapeCreateRestoreRequestNamespacesInner';

/**
 * 
 * @export
 * @interface TapeCreateRestoreRequest
 */
export interface TapeCreateRestoreRequest {

    /**
     * Drive Identifier.
     * @type {string}
     * @memberof TapeCreateRestoreRequest
     */
    drive: string;

    /**
     * Media set UUID.
     * @type {string}
     * @memberof TapeCreateRestoreRequest
     */
    mediaSet: string;

    /**
     * List of namespace to restore.
     * @type {Array<TapeCreateRestoreRequestNamespacesInner>}
     * @memberof TapeCreateRestoreRequest
     */
    namespaces?: Array<TapeCreateRestoreRequestNamespacesInner>;

    /**
     * Configure how notifications for this datastore should be sent.
     * `legacy-sendmail` sends email notifications to the user configured
     * in `notify-user` via the system's `sendmail` executable.
     * `notification-system` emits matchable notification events to the
     * notification system.
     * @type {PbsNotificationModeEnum}
     * @memberof TapeCreateRestoreRequest
     */
    notificationMode?: PbsNotificationModeEnum;

    /**
     * User ID
     * @type {string}
     * @memberof TapeCreateRestoreRequest
     */
    notifyUser?: string;

    /**
     * Authentication ID
     * @type {string}
     * @memberof TapeCreateRestoreRequest
     */
    owner?: string;

    /**
     * List of snapshots.
     * @type {Array<string>}
     * @memberof TapeCreateRestoreRequest
     */
    snapshots?: Array<string>;

    /**
     * A list of Datastore mappings (or single datastore), comma separated. For example 'a=b,e' maps the source datastore 'a' to target 'b and all other sources to the default 'e'. If no default is given, only the specified sources are mapped.
     * @type {PbsStoreField}
     * @memberof TapeCreateRestoreRequest
     */
    store: PbsStoreField;

}



/**
 * Check if a given object implements the TapeCreateRestoreRequest interface.
 */
export function instanceOfTapeCreateRestoreRequest(value: object): value is TapeCreateRestoreRequest {
    
    if (!('drive' in value) || value['drive'] === undefined) return false;
    
    if (!('mediaSet' in value) || value['mediaSet'] === undefined) return false;
    
    
    
    
    
    
    if (!('store' in value) || value['store'] === undefined) return false;
    
    return true;
}

export function TapeCreateRestoreRequestFromJSON(json: any): TapeCreateRestoreRequest {
    return TapeCreateRestoreRequestFromJSONTyped(json, false);
}

export function TapeCreateRestoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TapeCreateRestoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'drive': json['drive'],
        
        'mediaSet': json['media-set'],
        
        'namespaces': json['namespaces'] == null ? undefined : ((json['namespaces'] as Array<any>).map(TapeCreateRestoreRequestNamespacesInnerFromJSON)),
        
        'notificationMode': json['notification-mode'] == null ? undefined : PbsNotificationModeEnumFromJSON(json['notification-mode']),
        
        'notifyUser': json['notify-user'] == null ? undefined : json['notify-user'],
        
        'owner': json['owner'] == null ? undefined : json['owner'],
        
        'snapshots': json['snapshots'] == null ? undefined : json['snapshots'],
        
        'store': PbsStoreFieldFromJSON(json['store']),
        
    };
}

export function TapeCreateRestoreRequestToJSON(json: any): TapeCreateRestoreRequest {
    return TapeCreateRestoreRequestToJSONTyped(json, false);
}

export function TapeCreateRestoreRequestToJSONTyped(value?: TapeCreateRestoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'drive': value['drive'],
        
        'media-set': value['mediaSet'],
        
        'namespaces': value['namespaces'] == null ? undefined : ((value['namespaces'] as Array<any>).map(TapeCreateRestoreRequestNamespacesInnerToJSON)),
        
        'notification-mode': PbsNotificationModeEnumToJSON(value['notificationMode']),
        
        'notify-user': value['notifyUser'],
        
        'owner': value['owner'],
        
        'snapshots': value['snapshots'],
        
        'store': PbsStoreFieldToJSON(value['store']),
        
    };
}

