/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsActivityEnum } from './PbsActivityEnum';
import {
    PbsActivityEnumFromJSON,
    PbsActivityEnumFromJSONTyped,
    PbsActivityEnumToJSON,
    PbsActivityEnumToJSONTyped,
} from './PbsActivityEnum';

/**
 * 
 * @export
 * @interface TapeDriveGetDriveResponseDataInner
 */
export interface TapeDriveGetDriveResponseDataInner {

    /**
     * The DT Device Activity from DT Device Status LP page
     * @type {PbsActivityEnum}
     * @memberof TapeDriveGetDriveResponseDataInner
     */
    activity?: PbsActivityEnum;

    /**
     * Tape Changer Identifier.
     * @type {string}
     * @memberof TapeDriveGetDriveResponseDataInner
     */
    changer?: string;

    /**
     * Associated changer drive number (requires option changer)
     * @type {number}
     * @memberof TapeDriveGetDriveResponseDataInner
     */
    changerDrivenum?: number;

    /**
     * Model (autodetected)
     * @type {string}
     * @memberof TapeDriveGetDriveResponseDataInner
     */
    model?: string;

    /**
     * Drive Identifier.
     * @type {string}
     * @memberof TapeDriveGetDriveResponseDataInner
     */
    name: string;

    /**
     * The path to a LTO SCSI-generic tape device (i.e. '/dev/sg0')
     * @type {string}
     * @memberof TapeDriveGetDriveResponseDataInner
     */
    path: string;

    /**
     * Serial number (autodetected)
     * @type {string}
     * @memberof TapeDriveGetDriveResponseDataInner
     */
    serial?: string;

    /**
     * the state of the drive if locked
     * @type {string}
     * @memberof TapeDriveGetDriveResponseDataInner
     */
    state?: string;

    /**
     * Vendor (autodetected)
     * @type {string}
     * @memberof TapeDriveGetDriveResponseDataInner
     */
    vendor?: string;

}



/**
 * Check if a given object implements the TapeDriveGetDriveResponseDataInner interface.
 */
export function instanceOfTapeDriveGetDriveResponseDataInner(value: object): value is TapeDriveGetDriveResponseDataInner {
    
    
    
    
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    if (!('path' in value) || value['path'] === undefined) return false;
    
    
    
    
    return true;
}

export function TapeDriveGetDriveResponseDataInnerFromJSON(json: any): TapeDriveGetDriveResponseDataInner {
    return TapeDriveGetDriveResponseDataInnerFromJSONTyped(json, false);
}

export function TapeDriveGetDriveResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TapeDriveGetDriveResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'activity': json['activity'] == null ? undefined : PbsActivityEnumFromJSON(json['activity']),
        
        'changer': json['changer'] == null ? undefined : json['changer'],
        
        'changerDrivenum': json['changer-drivenum'] == null ? undefined : json['changer-drivenum'],
        
        'model': json['model'] == null ? undefined : json['model'],
        
        'name': json['name'],
        
        'path': json['path'],
        
        'serial': json['serial'] == null ? undefined : json['serial'],
        
        'state': json['state'] == null ? undefined : json['state'],
        
        'vendor': json['vendor'] == null ? undefined : json['vendor'],
        
    };
}

export function TapeDriveGetDriveResponseDataInnerToJSON(json: any): TapeDriveGetDriveResponseDataInner {
    return TapeDriveGetDriveResponseDataInnerToJSONTyped(json, false);
}

export function TapeDriveGetDriveResponseDataInnerToJSONTyped(value?: TapeDriveGetDriveResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'activity': PbsActivityEnumToJSON(value['activity']),
        
        'changer': value['changer'],
        
        'changer-drivenum': value['changerDrivenum'],
        
        'model': value['model'],
        
        'name': value['name'],
        
        'path': value['path'],
        
        'serial': value['serial'],
        
        'state': value['state'],
        
        'vendor': value['vendor'],
        
    };
}

