/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbsKindEnum } from './PbsKindEnum';
import {
    PbsKindEnumFromJSON,
    PbsKindEnumFromJSONTyped,
    PbsKindEnumToJSON,
    PbsKindEnumToJSONTyped,
} from './PbsKindEnum';

/**
 * 
 * @export
 * @interface TapeGetScanChangersResponseDataInner
 */
export interface TapeGetScanChangersResponseDataInner {

    /**
     * Kind of device
     * @type {PbsKindEnum}
     * @memberof TapeGetScanChangersResponseDataInner
     */
    kind: PbsKindEnum;

    /**
     * Device major number
     * @type {number}
     * @memberof TapeGetScanChangersResponseDataInner
     */
    major: number;

    /**
     * Device minor number
     * @type {number}
     * @memberof TapeGetScanChangersResponseDataInner
     */
    minor: number;

    /**
     * Model (autodetected)
     * @type {string}
     * @memberof TapeGetScanChangersResponseDataInner
     */
    model: string;

    /**
     * Path to the linux device node
     * @type {string}
     * @memberof TapeGetScanChangersResponseDataInner
     */
    path: string;

    /**
     * Serial number (autodetected)
     * @type {string}
     * @memberof TapeGetScanChangersResponseDataInner
     */
    serial: string;

    /**
     * Vendor (autodetected)
     * @type {string}
     * @memberof TapeGetScanChangersResponseDataInner
     */
    vendor: string;

}



/**
 * Check if a given object implements the TapeGetScanChangersResponseDataInner interface.
 */
export function instanceOfTapeGetScanChangersResponseDataInner(value: object): value is TapeGetScanChangersResponseDataInner {
    
    if (!('kind' in value) || value['kind'] === undefined) return false;
    
    if (!('major' in value) || value['major'] === undefined) return false;
    
    if (!('minor' in value) || value['minor'] === undefined) return false;
    
    if (!('model' in value) || value['model'] === undefined) return false;
    
    if (!('path' in value) || value['path'] === undefined) return false;
    
    if (!('serial' in value) || value['serial'] === undefined) return false;
    
    if (!('vendor' in value) || value['vendor'] === undefined) return false;
    
    return true;
}

export function TapeGetScanChangersResponseDataInnerFromJSON(json: any): TapeGetScanChangersResponseDataInner {
    return TapeGetScanChangersResponseDataInnerFromJSONTyped(json, false);
}

export function TapeGetScanChangersResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TapeGetScanChangersResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'kind': PbsKindEnumFromJSON(json['kind']),
        
        'major': json['major'],
        
        'minor': json['minor'],
        
        'model': json['model'],
        
        'path': json['path'],
        
        'serial': json['serial'],
        
        'vendor': json['vendor'],
        
    };
}

export function TapeGetScanChangersResponseDataInnerToJSON(json: any): TapeGetScanChangersResponseDataInner {
    return TapeGetScanChangersResponseDataInnerToJSONTyped(json, false);
}

export function TapeGetScanChangersResponseDataInnerToJSONTyped(value?: TapeGetScanChangersResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'kind': PbsKindEnumToJSON(value['kind']),
        
        'major': value['major'],
        
        'minor': value['minor'],
        
        'model': value['model'],
        
        'path': value['path'],
        
        'serial': value['serial'],
        
        'vendor': value['vendor'],
        
    };
}

