/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TapeDriveCreateBarcodeLabelMediaResponse
 */
export interface TapeDriveCreateBarcodeLabelMediaResponse {

    /**
     * 
     * @type {string}
     * @memberof TapeDriveCreateBarcodeLabelMediaResponse
     */
    data: string;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof TapeDriveCreateBarcodeLabelMediaResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof TapeDriveCreateBarcodeLabelMediaResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the TapeDriveCreateBarcodeLabelMediaResponse interface.
 */
export function instanceOfTapeDriveCreateBarcodeLabelMediaResponse(value: object): value is TapeDriveCreateBarcodeLabelMediaResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function TapeDriveCreateBarcodeLabelMediaResponseFromJSON(json: any): TapeDriveCreateBarcodeLabelMediaResponse {
    return TapeDriveCreateBarcodeLabelMediaResponseFromJSONTyped(json, false);
}

export function TapeDriveCreateBarcodeLabelMediaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TapeDriveCreateBarcodeLabelMediaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function TapeDriveCreateBarcodeLabelMediaResponseToJSON(json: any): TapeDriveCreateBarcodeLabelMediaResponse {
    return TapeDriveCreateBarcodeLabelMediaResponseToJSONTyped(json, false);
}

export function TapeDriveCreateBarcodeLabelMediaResponseToJSONTyped(value?: TapeDriveCreateBarcodeLabelMediaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

