/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Backup Server API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TapeGetScanChangersResponseDataInner } from './TapeGetScanChangersResponseDataInner';
import {
    TapeGetScanChangersResponseDataInnerFromJSON,
    TapeGetScanChangersResponseDataInnerFromJSONTyped,
    TapeGetScanChangersResponseDataInnerToJSON,
    TapeGetScanChangersResponseDataInnerToJSONTyped,
} from './TapeGetScanChangersResponseDataInner';

/**
 * 
 * @export
 * @interface TapeGetScanDrivesResponse
 */
export interface TapeGetScanDrivesResponse {

    /**
     * 
     * @type {Array<TapeGetScanChangersResponseDataInner>}
     * @memberof TapeGetScanDrivesResponse
     */
    data: Array<TapeGetScanChangersResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof TapeGetScanDrivesResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof TapeGetScanDrivesResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the TapeGetScanDrivesResponse interface.
 */
export function instanceOfTapeGetScanDrivesResponse(value: object): value is TapeGetScanDrivesResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function TapeGetScanDrivesResponseFromJSON(json: any): TapeGetScanDrivesResponse {
    return TapeGetScanDrivesResponseFromJSONTyped(json, false);
}

export function TapeGetScanDrivesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TapeGetScanDrivesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(TapeGetScanChangersResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function TapeGetScanDrivesResponseToJSON(json: any): TapeGetScanDrivesResponse {
    return TapeGetScanDrivesResponseToJSONTyped(json, false);
}

export function TapeGetScanDrivesResponseToJSONTyped(value?: TapeGetScanDrivesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(TapeGetScanChangersResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

